### ISSUE TITLE
No game listed in steam server list

### ISSUE THREAD

**Issue by AxelBremer** [lloesche/valheim-server-docker#1]
Hi!

Thanks for making this! When I run the container and wait for the server to be downloaded etc. it does show up in the steam server list but it doesn't list what game it is and in Valheim I don't see the server at all.

Would you maybe know how to fix this?

**Comment by lloesche** [comment]
Hi @AxelBremer,

the only networking related issue I've run into thus far where the server would start up and give a log message "Connected" with no indication of any errors but then not show up in-game was when the three UDP ports 2456-2458 were not publicly accessible from the Internet.

**Comment by anpross** [comment]
hi, noticed the same thing, however some of us where able to see the server and the others then joined via the steam buddy list to those. i was suspecting an issue with the central server list🤷‍♂️ - and also thanks!

**Comment by anpross** [comment]
did a quick search - maybe that helps: https://www.reddit.com/r/valheim/comments/lcn1i6/rented_servers_being_a_nightmare_to_find/

**Comment by kparkov** [comment]
This is server discovery related and probably out of scope for this repo. I am using it with a rented server without problems. Well, actually, it shows up in the game server list, but I can't add it as a favorite server in Steam. 🤷‍♂️

Thank you for this excellent initiative, @lloesche.
