### ISSUE TITLE
sudden issues with performance

### ISSUE THREAD

**Issue by SpiderKraken** [lloesche/valheim-server-docker#105]
Error seen is constant in the log. 

src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1276) : Assertion Failed: SDR service thread gave up on lock after waiting 55ms.  This directly adds to delay of processing of network packets! | stdout
-- | --

started very recently in the last 24 hours id say resulting in major lag and rubber banding along with multiple sudden kicks from server .

**Comment by InB4DevOps** [comment]
See #104
