### ISSUE TITLE
valheim plus part of Readme.md misleading

### ISSUE THREAD

**Issue by anpross** [lloesche/valheim-server-docker#108]
1st of all, thanks for all the work you guys put into this. 

I wanted to run Valheim plus for exactly the dataRate change you mention here:

> For most modifications the mod has to be installed both, on the server as well as all the clients that connect to the server. A few modifications, like for example changing the dataRate can be done server only.

however in my testing, you need to have the client-mod always installed. When try to connect without the mod installed in the client, i see the following in the server log:
`02/26/2021 19:42:37: Peer 76561197981153626 has incompatible version, mine:0.146.11@0.9 remote 0.146.11`
which to me indicates that V+ 0.9 is missing on the client.

In my special case, i'm running the client on GeForce NOW, so i cant even install the mod :/

**Comment by lloesche** [comment]
See https://github.com/lloesche/valheim-server-docker#server-data-rate for an example of how to solve this.

**Comment by anpross** [comment]
sorry... i did put a new `valheim_plus.cfg` into the wrong folder.
