### ISSUE TITLE
[Enhancement] Valheim+ config to ENV Variables

### ISSUE THREAD

**Issue by acidrs03** [lloesche/valheim-server-docker#109]
Really great work getting the Valheim+ mod supported in this image. 
Would love to see an enhancement to the image to allow the setting of the Valheim+ config.cfg settings as environment variables in docker.

**Comment by lloesche** [comment]
I love the idea! We would need to write a config parser/generator I suppose to adjust the existing config but doesn't sound too complicated and super useful.

**Comment by lloesche** [comment]
@acidrs03 I've added the tool to the `dev` branch. The docker image name is `lloesche/valheim-server:dev`.

From the new README:

ValheimPlus config can be specified in environment variables using the syntax `VPCFG_<section>_<variable>=<value>`.

Example:
```
-e VPCFG_Server_enabled=true -e VPCFG_Server_enforceMod=false -e VPCFG_Server_dataRate=500
```

turns into
```
[Server]
enabled=true
enforceMod=false
dataRate=60
```
All existing configuration in /config/valheimplus/valheim_plus.cfg is retained and a backup of the old config is created as /config/valheimplus/valheim_plus.old before writing the new config file.
