### ISSUE TITLE
Server requires 5 character password

### ISSUE THREAD

**Issue by nilsschweikhard** [lloesche/valheim-server-docker#11]
I noticed my valheim server would be caught in a startup error loop, if the chosen password is too short. 
It took me a while to figure this out. I've opened this issue in case someone else runs into this problem.
Valheim seems to expect at least 5 characters for the server password.

> 2021-02-10 18:37:58,636 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> WARNING: Shader Unsupported: 'Autodesk Interactive' - All passes removed
> WARNING: Shader Did you use #pragma only_renderers and omit this platform?
> HDR Render Texture not supported, disabling HDR on reflection probe.
> (Filename:  Line: 277)
> 
> HDR Render Texture not supported, disabling HDR on reflection probe.
> (Filename:  Line: 277)
> 
> Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
> UnloadTime: 6.205986 ms
> Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
> (Filename:  Line: 509)
> 
> HDR Render Texture not supported, disabling HDR on reflection probe.
> (Filename:  Line: 277)
> 
> Initializing Google Analytics 0.2.
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Initializing world generator seed: ( 0 )   menu:True  worldgen version:1
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Using mountain distance: 1000
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Render threading mode:SingleThreaded
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Get create world Default
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Loaded localization English
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> **02/10/2021 18:38:08: Error bad password:The password is too short**
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Missing audio clip in music respawn
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 02/10/2021 18:38:08: Builder started
> 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> 
> Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 85928.
> Total: 87.753374 ms (FindLiveObjects: 10.197371 ms CreateObjectMapping: 15.702577 ms MarkObjects: 61.427806 ms  DeleteObjects: 0.421070 ms)

I've started the container with the following arguments.

`docker run -d \
    --name valheim-server \
    -p 2456-2458:2456-2458/udp \
    -v $HOME/valheim/config:/config \
    -e SERVER_NAME="My Server" \
    -e WORLD_NAME="Default" \
    -e SERVER_PASS="test" \
    lloesche/valheim-server`

**Comment by lloesche** [comment]
Fixed in #15

**Comment by schildbach** [comment]
It's funny, the server that is embedded in the client is fine with 4 characters…
