### ISSUE TITLE
Valheim+ Passwordless Server Fix

### ISSUE THREAD

**Issue by acidrs03** [lloesche/valheim-server-docker#110]
Valheim+ has a setting in the config.cfg that allows for password less servers. However this does not work in this image. 
I posted on the Valheim+ github to see what is needed for this setting to work and recieved the following response
"What is your current batch file command to start your server?

If it has `-password "xxxxx"` in it, it will not work, as far as I know.

You have to remove all of `-password "xxxxx"` from your batch file startup command and also have;
`disableServerPassword=true` set in the ValheimPlus config."

So for this to work in this image we may need a check to see if `-password "xxxxx"` is set and if not run the start script without it included. 

I found in the valheim-server section [](https://github.com/lloesche/valheim-server-docker/blob/main/valheim-server)
there is the `run_server()` part at line 56ish

i dont know if this would work as a fix or not.

`run_server() {
    echo "Running Valheim Server"
	if [ $SERVER_PASS -eq "" ]; then
	    "$valheim_server" -nographics -batchmode -name "$SERVER_NAME" -port $SERVER_PORT -world "$WORLD_NAME" -public $SERVER_PUBLIC > >(filter stdout)  2> >(filter stderr >&2) &
		valheim_server_pid=$!
		unset LD_LIBRARY_PATH
		unset LD_PRELOAD
		echo $valheim_server_pid > "$valheim_server_pidfile"
		ensure_permissions_after_start &
		wait
	else
		"$valheim_server" -nographics -batchmode -name "$SERVER_NAME" -port $SERVER_PORT -world "$WORLD_NAME" -password "$SERVER_PASS" -public $SERVER_PUBLIC > >(filter stdout)  2> >(filter stderr >&2) &
		valheim_server_pid=$!
		unset LD_LIBRARY_PATH
		unset LD_PRELOAD
		echo $valheim_server_pid > "$valheim_server_pidfile"
		ensure_permissions_after_start &
		wait
}`

**Comment by lloesche** [comment]
You can now provide `-e VALHEIM_PLUS=true -e SERVER_PASS=""` and it will correctly start the server without the `-password` arg. It won't check however if you have configured ValheimPlus correctly to allow passwordless connections.

I just tested it and my client was able to connect without a password even without the mod using the following config:
```
[Server]
enabled=true
disableServerPassword=true
enforceMod=false
```

**Comment by LuminairPrime** [comment]
@lloesche FYI, the valheimplus example in the documentation mentions datarate=500:

https://github.com/lloesche/valheim-server-docker#event-hook-examples

But valheimplus mentions datarate was removed in March 23, 2021. Not sure what is right:

> Removed dataRate from [Server] section since this value has been removed in the latest valheim version, we might reintroduce this value with the next version of valheim plus.
https://github.com/valheimPlus/ValheimPlus/releases?q=datarate&expanded=true
