### ISSUE TITLE
Valheim+

### ISSUE THREAD

**Issue by ygagniere** [lloesche/valheim-server-docker#112]
Thanks for that awesome work! I'm trying to enable the valheim+ mod but cannot make it work. I've added the env variable but I might be missing something here because I don't see the Valheimplus folder being created in the directory. Is there something else I need to do?

Thank you,

**Comment by Nanolab53** [comment]
@ygagniere I had this issue too when I tried to upgrade my container. I resolved it by restarting from scratch : don't forget to backup your world before stopping your server, delete all your folders and recreate the container from the latest image.

**Comment by lloesche** [comment]
@ygagniere @Nanolab53 so there's definitely no need to change or delete anything in `/config`. Make sure to `docker pull lloesche/valheim-server:latest` for V+ support to be there.
Depending on how old the original container was it makes sense to mount a fresh volume to `/opt/valheim` just to have it download a clean install of everything as we cleaned up and moved the server directory structure quite a bit since adding the mod. Other than that the only thing that's required to activate V+ is setting the environment variable `VALHEIM_PLUS=true`.

**Comment by lloesche** [comment]
> I don't see the Valheimplus folder being created in the directory

There should be several new directories once you enable V+. The overall directory structure should look like this:
```
/opt/valheim/               <= this should be your data volume mount
        |___/dl/            <= downloads happen in here
        |     |___/server/  <= vanilla server download
        |     |___/plus/    <= ValheimPlus mod download
        |___/server/        <= vanilla server installation
        |___/plus/          <= merge of vanilla server and ValheimPlus mod

/config/                    <= this should be your config volume mount
    |___/worlds/            <= where the server stores the world(s)
    |___/backups/           <= hourly backups of the worlds/ folder go here
    |___/valheimplus/       <= ValheimPlus configuration files
```

The first thing to check for once you enable `VALHEIM_PLUS=true` is that `/opt/valheim/dl/plus` was created.

Also note that `/config/valheimplus` will only be created if it does not exist already. If you create the directory yourself but don't put any config files in it, the server won't create them for you. It is only if the directory does not exist that the server will create it for you and add a default copy of `valheim_plus.cfg` and `BepInEx.cfg`.

**Comment by ygagniere** [comment]
Pulling the latest image solved the issue.

Thank you.

**Comment by jackemerson** [comment]
Just to add another potential cause; I ran into the same problem, but incorrect case for boolean values was the culprit, in my case.

I was setting environment variable values by reference (through Azure ARM template parameters). Seems `True/False` are Azure's outputs for booleans ( `true/false` being the desired.)

V+ loaded without a hitch, following a fix to my template ... though I'm pretty fresh to Azure's offerings, so my understanding of this might be wrong from the ground up. 

In any case, I'll leave this comment here. Hopefully it will either help someone, or be corrected. 🔨
