### ISSUE TITLE
Steamcmd can't download server: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Nirco96** [lloesche/valheim-server-docker#120]
I'm setting up the docker image in an azure cloud instance and it seems like SteamCMD can't download anything because of the following error: 
`/opt/steamcmd/steamcmd.sh: line 37: /opt/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
`

Has anyone seen this before?

**Comment by lloesche** [comment]
This image is for x86. Are you trying to run it on an ARM CPU like a Raspberry PI?

**Comment by lloesche** [comment]
I just tested to run the container using `az container create` and can confirm that the default Azure container host in westeurope is unable to run 32bit Linux binaries.

I wonder how the guys in https://github.com/lloesche/valheim-server-docker/issues/84 are able to run the image.

**Comment by lloesche** [comment]
@Nirco96 the comments in #84 suggest that using a US location like e.g. `--location eastus2` might help. When I tried on a EU location I received the same 32 bit exec error you did. But in US Azure seems to be running 32 bit capable Kernels on their container hosts.

**Comment by jag43** [comment]
Hey I've been trying to run the container on Azure and getting the same issue as this. Running on US region doesn't really feel like a soltuion to me.

I admit I am new to Azure and Docker but this thread seems to suggest you can download a library to allow execution. Could that be an option?
https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error
