### ISSUE TITLE
Any advice on reverse proxying?

### ISSUE THREAD

**Issue by Typhonragewind** [lloesche/valheim-server-docker#121]
Hello!

I was wondering if you had any advice on how to properly reverse proxy this, using nginx?

**Comment by 86magic** [comment]
Hi! Do you mean to be able to access with a domain name instead of IP address? If yes, then it is currently not possible to use the domain but hopefully will be possible soon.

**Comment by Typhonragewind** [comment]
> 
> 
> Hi! Do you mean to be able to access with a domain name instead of IP address? If yes, then it is currently not possible to use the domain but hopefully will be possible soon.

Yeah, that was it. 
Thanks for the confirmation :)

**Comment by 86magic** [comment]
No worries. I am waiting for the game update to use this function as well. Once it is implemented I will share if it works with my docker setup.
In general I use the following containers for this:
- traefik as a reverse proxy
- codeworksio/dnsomatic for updating my IP to the DNS

**Comment by Mutmatt** [comment]
If you have the dns setup properly you should be able to use the domain with a specified port just fine. 

e.g. `games.example.com:2456`
