### ISSUE TITLE
Mention CPU and RAM requirements in README

### ISSUE THREAD

**Issue by schildbach** [lloesche/valheim-server-docker#123]
I take it this docker image needs signifcantly more resources than a basic image like nginx or bind. But what are the requirements?

- What server size should users pick? 1 core, 2 GB RAM seems a baseline here when renting virtual servers.
- Do requirements depend much on number of concurrently connected users, or game progress (e.g. number and size of player-built buildings)?

**Comment by Xav-Pe** [comment]
I think it  also depends of the speed. My server has a 8259U as CPU, and valheim-server uses a constant 60% of one core without any player on it.

2GB is also too short, mine us using 2.1GB (again without any player), and you need spare memory for system.

My volume (``/var/lib/docker/volumes/valheim-data``) is actually 4GB. I think the /dl is not used anymore :

```bash
    1,0 GiB [##########] /dl
    1,0 GiB [######### ] /plus
    1,0 GiB [######### ] /server
  905,1 MiB [########  ] /valheim_server_Data
```

So atleast i should be

- CPU 2cores atleast 2.5Ghz
- 4GB Memory
- 4GB disk

**Comment by lloesche** [comment]
Thank you for the recommendation. Will add them.
