### ISSUE TITLE
Backup auto delete not working (on synology?)

### ISSUE THREAD

**Issue by belleDESiRE** [lloesche/valheim-server-docker#129]
Hi,

For some reason, the world backups are not being deleted after (the default) 3 days on my synology nas.

![image](https://user-images.githubusercontent.com/24789925/109468176-8a489000-7a6c-11eb-9813-4f2860a074bf.png)
![image](https://user-images.githubusercontent.com/24789925/109469172-f8da1d80-7a6d-11eb-99ef-3643f415305b.png)
![image](https://user-images.githubusercontent.com/24789925/109468552-06db6e80-7a6d-11eb-9027-62c725c9b845.png)
![image](https://user-images.githubusercontent.com/24789925/109468845-810bf300-7a6d-11eb-9967-eda28087def8.png)

Enjoying the game and lovely docker container!!!

**Comment by lloesche** [comment]
@belleDESiRE thank you for your report.!
This is indeed a bug. It is working as designed by the `find` command that finds the old backups but I am using it wrong 🙂
Will submit a fix.

**Comment by belleDESiRE** [comment]
> 
> 
> @belleDESiRE thank you for your report.!
> This is indeed a bug. It is working as designed by the `find` command that finds the old backups but I am using it wrong 🙂
> Will submit a fix.

Tested, works. tx!
