### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by madhub0815** [lloesche/valheim-server-docker#130]
Hi, 

i saw in the Server Console some periodic erros:

Mar  1 09:02:00 Valheim-Server cron.err crond[11]: user root: parse error at 120
Mar  1 09:02:00 Valheim-Server cron.err crond[11]: user root: parse error at [
Mar  1 09:02:00 Valheim-Server cron.err crond[11]: user root: parse error at -f
Mar  1 09:02:00 Valheim-Server cron.err crond[11]: user root: parse error at "/var/run/valheim-updater.pid"
Mar  1 09:02:00 Valheim-Server cron.err crond[11]: user root: parse error at ]

Can you have a look at this?

**Comment by Xav-Pe** [comment]
I don't have these errors, and yet I also use cron.
I talk about cron because it's the component yelling your errors ``Valheim-Server cron.err crond[11]``.

Are you sure your cron string are corrects? Here is mine : 

```cron
      BACKUPS_CRON: "05 */6 * * *" 
      UPDATE_CRON: "01 */2 * * *" 
      RESTART_CRON: "30 02 * * *" 
```

**Comment by madhub0815** [comment]
Oh i see 
if i understand it correctly i have typed in 120 (every 2 hours)
Instead of that i have to set it to */120 * * * * in UPDTAE_CRON correct?
and in the BACKUP_CRON 6 * * * * for every 6 hours?

**Comment by Xav-Pe** [comment]
For every 6 hours at 05 (00:05, 06:05, 12:05...)  : ``BACKUPS_CRON: "05 */6 * * *" ``
For every 2 hours 30 :   ``UPDATE_CRON: "30 */2 * * *"``

See [cron creator](https://crontab.guru/#30_*/2_*_*_*)

**Comment by madhub0815** [comment]
Thank you very much ;-)
