### ISSUE TITLE
/opt/valheim_dl volume

### ISSUE THREAD

**Issue by Panderine** [lloesche/valheim-server-docker#132]
Hi, 

Even though I have mounted a local directory as recommended, I have a docker managed volume with the server files.

-v $HOME/valheim-server/config:/config \
 -v $HOME/valheim-server/data:/opt/valheim \

Both /valheim-server/data and /opt/valheim_dl have the same files. Aren't they supposed to use /data location only?

**Comment by Panderine** [comment]
switching to dev release fixed.

**Comment by lloesche** [comment]
There is no `/data` directory. `/opt/valheim_dl` is no longer used, only `/config` and `/opt/valheim`. You should see a warning about this upon startup.
the `dev` release is the same as `latest` currently so you likely just need to `docker pull lloesche/valheim-server:latest`.
