### ISSUE TITLE
Request: Expose Steam Server Ports as environment variable

### ISSUE THREAD

**Issue by podbiker** [lloesche/valheim-server-docker#146]
I discovered that changing the port for the Valheim server is not enough to run multiple instances behind one IP. The Steam game server ports must be altered as well.

Please add these ports to the environment variables to allow for hosting more than one instance.

Reference:
https://answers.unrealengine.com/questions/787258/view.html

**Comment by dhumphrey7** [comment]
Can't this be done using the STEAMCMD_ARGS variable?

**Comment by podbiker** [comment]
> Can't this be done using the STEAMCMD_ARGS variable?

Not as far as I can see:
http://manpages.ubuntu.com/manpages/xenial/man6/steamcmd.6.html

**Comment by dhumphrey7** [comment]
Sorry I misinterpreted what that variable was being used for.  So if I am now understanding this you would need a variable that would put QueryPort in the server start line something like -queryport "$QUERY_PORT".  If I am reading correctly default is 27015.

**Comment by podbiker** [comment]
@dhumphrey7 no worries, yes you are correct. 27015 is default and there is a range from 27016 to 27030 which is used if 27015 is not available or otherwise in use. Thwrefor I asked for a variable usable in the way you described.

**Comment by dhumphrey7** [comment]
I believe I have the changes needed to implement this and as long as I can figure out github will submit a pull request.

**Comment by lloesche** [comment]
I just added an env var `SERVER_ARGS` that allows you to supply arbitrary arguments to the Valheim server. Hope this helps.
