### ISSUE TITLE
feature request: only do scheduled restart if 'idle' (no players connected)

### ISSUE THREAD

**Issue by GMBridge** [lloesche/valheim-server-docker#157]
well, if you're going to add the ability to only update if there's no players connected, of course i'm going to request a feature to not do the scheduled restart if players are connected.

**Comment by GMBridge** [comment]
I just saw https://github.com/lloesche/valheim-server-docker/pull/142 and the pre-restart hook is probably a better way to approach this. i'll see if i can mangle something together using that.

**Comment by PsyKoMari** [comment]
Please update this issue with an example or with the link of your repo when you manage to use that hook

**Comment by GMBridge** [comment]
haven't worked with linux in a few decades (showing my age here), but i think something like this may work?

#!/bin/bash
# delay valheim server restart for up to 60 minutes if players are connected

# Include defaults
. /usr/local/etc/valheim/defaults
. /usr/local/etc/valheim/common

debug "Running Valheim Server idle check as user $USER uid $UID"

main() {
	for $RESTARTDELAY in 5 10 15 30
	do
		if  is_idle; then
			return
		else
			debug "Server not idle, delaying restart by $RESTARTDELAY minutes"
		fi
		SLEEPSECONDS=`echo "$RESTARTDELAY * 60" | bc`
		sleep $SLEEPSECONDS
	done
	return 0
}

is_idle() {
	if timeout 3 tcpdump udp port "$SERVER_PORT" -n -s 84 -c 1 > /dev/null 2>&1; then
		debug "Players connected to Valheim server"
		return 1
	else
		debug "No players connected to Valheim server"
		return 0
	fi
    return 0
}

**Comment by lloesche** [comment]
I feel like this is a solution looking for a problem. Like, for an update check that runs every 15 minutes and you never know when it'll restart the server I could see how it makes sense to not run when players are connected. For a once a day restart at a well known time (5 AM by default) just move it to a different time slot, make it a weekly restart or turn it off entirely. It'll take some real convincing arguments for me to put any time into building something around that.

That said I've moved the idle check into a dedicated function `server_is_idle()` in `common` for easier use in contrib scripts.
Feel free to build any solution that makes sense for your environment and send a PR if you think it is useful for others. 🙂

**Comment by GMBridge** [comment]
I mostly agree, this would really only address some edge cases such as someone trying to finish a brutal corpse recovery before logging off and then bumping against the restart schedule. I'm going to time (or check the logs to see) how long an actual restart takes (at least on my synology) to see how disruptive it could be.

**Comment by lloesche** [comment]
```
03/04/2021 22:58:53: Game - OnApplicationQuit
...
03/04/2021 22:59:29: DungeonDB Start 380
```
Here it's around 36 seconds from the moment it receives the shutdown signal to the moment it's fully started and accepting connections.

**Comment by GMBridge** [comment]
```
03/04/2021 05:00:02: Game - OnApplicationQuit
...
03/04/2021 05:01:25: DungeonDB Start 244
```

so 83 seconds on a Synology NAS (DS1817+ which has an intel Atom C2538 cpu), so yeah, not really worth the effort in my case (especially since I'll be moving it to some faster hardware soon), but thank you for moving the _server_is_idle()_ to _common_
