### ISSUE TITLE
Publish Docker images to GHCR

### ISSUE THREAD

**Issue by TheCatLady** [lloesche/valheim-server-docker#163]
With Docker Hub's addition of pull limits this past November, it would be nice if Docker images were mirrored on GitHub Container Registry, which doesn't have any limits (for now at least).

https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by TheCatLady** [comment]
Alternatively, it appears that Docker Hub waives pull limits for approved open-source projects: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

Just requires the completion of an application! I’m aware of another project/group which has been approved for this, and all of their images are now exempt from the pull limits.

**Comment by lloesche** [comment]
I filled out the form. It was all very corporate orientated, asking for my business name and website. Let's see what they say.

**Comment by TheCatLady** [comment]
@lloesche Publishing images to GHCR is pretty simple to do as well.  I can PR the GitHub workflows if you'd like, but you'd need to add the required repository secrets.  I see that you're leveraging the Docker Hub infrastructure for builds, but I personally like having CI in a GitHub workflow where the actions history is public, so anyone can check the status of a build.  Let me know what you think!

**Comment by lloesche** [comment]
That would be great! Thank you! I've created a PAT that allows packages read/write/delete. For startes I would leave Dockerhub as is and create a GH Workflow for publishing to GHCR only.

**Comment by TheCatLady** [comment]
@lloesche Just let me know what the PAT repo secret is named.  I'll submit a PR sometime today 😸

**Comment by lloesche** [comment]
Right, I imaginatively named the GHCR PAT repo secret `GHCR_PAT`.
