### ISSUE TITLE
Valheimplus fails to load

### ISSUE THREAD

**Issue by gitglennoo** [lloesche/valheim-server-docker#166]
This is more of a question than an issue. It's unclear to me whether the valheimplus mod is already in the package or I should download and implement it myself. I've tried using the "-e VALHEIM_PLUS=true" but to no avail. The folder and file neither get created.

using the following docker run command:

docker run -d \
    --name valheim-server-plus-true \
    -p 2456-2458:2456-2458/udp \
    -v /docker/valheim/config:/config \
    -e SERVER_NAME=**** \
    -e WORLD_NAME=Valhalla \
    -e SERVER_PASS=**** \
    -e VALHEIM_PLUS=true \
    -e VPCFG_Server_enabled=true \
    -e VPCFG_Server_enforceMod=false \
    -e VPCFG_Server_dataRate=200 \
    lloesche/valheim-server

**Comment by Hydeo** [comment]
I just got the same issue trying to add the V+ mod to a server i host. 

For now you can use the `:dev` version of the image, it pulling the mod, just tried it.

**Comment by lloesche** [comment]
Just like the Valheim dedicated server ValheimPlus is automatically downloaded by the container when you `VALHEIM_PLUS=true`.
There's no need for you to add anything. Also it's been part of the `:latest` main branch for a while. No need to use the `:dev` tag.
Just make sure to pull the `:latest` image tag and don't have an old version of the image on your container host.

**Comment by lloesche** [comment]
Looking at your command above I would also recommend creating `/docker/valheim/data` on your host and run with `-v /docker/valheim/data:/opt/valheim`. That way startup is faster as it doesn't have to download the 1 GB Valheim server from Steam each time you start.

**Comment by lloesche** [comment]
Also, on first start make sure that your `config/` folder has no directory named `valheimplus`. If the directory exists the installer assumes you have an existing ValheimPlus config and won't create it and copy the default V+ config.

**Comment by lloesche** [comment]
@gitglennoo did this answer your question? I'll close the issue but feel free to create a new one if there's anything that's unclear or not working.
