### ISSUE TITLE
Create second server from docker Synology

### ISSUE THREAD

**Issue by MAL0W** [lloesche/valheim-server-docker#172]
Please, what would be the variables to create a second server from Synology Docker?

**Comment by lloesche** [comment]
I don't think you would have to change any variables at all. Just mount a fresh volume to `/config` and `/opt/valheim` and map container ports `2456-2458` to something else on your Synology.

That is in this screen:
![Step 5](https://raw.githubusercontent.com/lloesche/valheim-server-docker/main/misc/step5.png "Step 5")

You use different "Local Ports" but the "Container Ports" stay the same.
For instance map 2466 to 2456, 2467 to 2457 and 2468 to 2457. And then in Steam/Valheim you connect to your Synology IP:2466.
