### ISSUE TITLE
Update Check disconnecting players

### ISSUE THREAD

**Issue by DevinSanders** [lloesche/valheim-server-docker#178]
I did not set a value for UPDATE_IF_IDLE since the default value is true. However, the update check still runs when there are active connections and all players that are currently logged into the server get disconnected. As a workaround I set UPDATE_CRON to only check for updates once per day, early in the morning when no one should be connected.

**Comment by lloesche** [comment]
So, the update check has never disconnected players. It is when the update check runs AND finds an update AND restarts the server that players would be disconnected. Which even with a lot of Valheim updates does not happen more than every other day or so.
The only thing `UPDATE_IF_IDLE` does is not check for updates if it finds that players are currently connected. Now the way it determines whether players are connected or not is not fool proof as Valheim server has no official API for that. So the updater will watch the server port for 3 seconds and if there's zero network packets (even with a single player connected there's typically dozens per second) it assumes that nobody is connected.

I just tested both scenarios, being connected:
```
2021-03-06 16:17:46 [34] (DEBUG) Received signal to check for update
2021-03-06 16:17:47 [34] (DEBUG) Players connected to Valheim server - skipping update check
```

and not being connected
```
2021-03-06 16:20:17 [34] (DEBUG) Received signal to check for update
2021-03-06 16:20:20 [34] (DEBUG) No players connected to Valheim server
2021-03-06 16:20:20 [34] (INFO) Downloading/updating/validating Valheim server from Steam
Redirecting stderr to '/root/Steam/logs/stderr.txt'
...
...
 Update state (0x5) verifying install, progress: 84.94 (893249087 / 1051599543)
Success! App '896660' fully installed.
.d..t...... ./
2021-03-06 16:20:33 [34] (INFO) Valheim Server is already the latest version
2021-03-06 16:20:33 [34] (DEBUG) ValheimPlus is enabled - running updater
2021-03-06 16:20:33 [661] (DEBUG) Local ValheimPlus archive is identical to remote archive - no update required
```

and in both cases the server was not restarted. So even if the "are players connected" check failed, nobody would have been disconnected.

Meaning whatever is going wrong on your server is very likely not the update check. But without logs or any technical details whatsoever it's hard to say what the issue is.

**Comment by lloesche** [comment]
@DevinSanders were you able to get the logs? Feel free to post them in here. Without them I'm afraid there's not much we can do to figure out the root of your disconnection issues.

**Comment by DevinSanders** [comment]
Unfortunately I did not save the logs. I realize it is not the update check itself that causes the disconnection, but the log said "No Players Connected" even though I was connected at the time, and it had happened previously with two players connected. In both cases I watched the logs while the download progress slowly incremented and could not reconnect to the server until after the update had completed. From the time we were disconnected until the logs showed the server running and accepted new connections took about 10 minutes.

I am using the GCP Kubernetes Engine to host the server. Maybe that has something to do with the update check not being able to detect connections.

**Comment by lloesche** [comment]
> could not reconnect to the server until after the update had completed. From the time we were disconnected until the logs showed the server running and accepted new connections took about 10 minutes.

But downloading the update does not stop the server?! It is not even happening within the server's directory.

Downloads go to `/opt/valheim/dl/server` and only after the download is finished files that have changed get rsynced over to `/opt/valheim/server`. When that is done the server process is being restarted. Which typically takes around 30-40 seconds before the server accepts connections again.

I would love to know what's going on there but without logs this is all just guesswork I'm afraid.

**Comment by DevinSanders** [comment]
I understand. I am new to using containers so GCP was probably not the best platform to go with given that there were no GCP examples for your image. I probably just configured something wrong, but this is the only issue that we have had over the past couple of weeks. If it happens again, I will be sure to get you the logs.

**Comment by lloesche** [comment]
No worries, we'll figure it out next time it happens. Another thing to consider are system resources. Did you make sure that https://github.com/lloesche/valheim-server-docker#system-requirements is met? I was thinking about the extremely long times you described like 10 minutes for an update check and restart that should finish under 1 minute and figured maybe the container is just under provisioned. Depending on the number of players you'd want 2-4 of the highest clocked cores available and at least 4 GB better 8-12 GB of RAM (depending on whether the container is allowed to swap or not). Valheim server is pretty resource intensive.

**Comment by DevinSanders** [comment]
I had the same thought when you said it normally takes 30-40 seconds to start accepting connections. GKE defaults to very low resources so I am going to increase the resource limits to see if that resolves the issue.

**Comment by lloesche** [comment]
@DevinSanders did increasing the resources help your issue?

**Comment by DevinSanders** [comment]
So far, the additional CPU and RAM seems to have improved performance and we have not had any further issues. Even if it happens again, I understand that it is not your update check that is disconnecting us so this issue can be closed.
