### ISSUE TITLE
Automatic memory clearing causes major lag

### ISSUE THREAD

**Issue by alexiuhas** [lloesche/valheim-server-docker#182]
Hello,
I wanted to ask if anyone else encountered this issue. Every 10 minutes there's a major lag spike ingame. When I looked at the logs, it seemed the lag spikes coincide with these events:
`03/06/2021 21:21:38:  Connections 6 ZDOS:559359  sent:248 recv:271
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 1116808.
Total: 34845.626088 ms (FindLiveObjects: 17843.190284 ms CreateObjectMapping: 57.075394 ms MarkObjects: 16937.076990 ms  DeleteObjects: 8.281471 ms)`

Is it normal for this to happen every 10 minutes? Is there a way to disable it/reduce it's frequency?

**Comment by Shawak** [comment]
Your CPU is propably not good enough to run this server. Any chance you are probably using a VPS with shared cores? I had a similar issue and it was fixed when I usead dedicated cores instead.

**Comment by alexiuhas** [comment]
> Your CPU is propably not good enough to run this server. Any chance you are probably using a VPS with shared cores? I had a similar issue and it was fixed when I usead dedicated cores instead.

I have an older PC with an i5-4690k cpu that I turned into a proxmox host. CPU usage averages around 30-40% on the whole system and spikes at 50%. Not much else is running on the server atm.

**Comment by Shawak** [comment]
Are you using Linux or Windows? And in case you are using windows, do you have your resources limited in the Docker App (Settings -> Resources -> Advanced)?

**Comment by alexiuhas** [comment]
It's an ubuntu server installation and I use rancher to manage the docker containers. Haven't set any limits on resources but I will check for any default limitations

**Comment by alexiuhas** [comment]
UPDATE: Restarting the entire docker host vm seems to have fixed the issue for now. The total time for unloading assets is around 800ms now instead of 35000ms. Will continue to monitor it.
