### ISSUE TITLE
"has Incompatible version" error after enabling ValheimPlus

### ISSUE THREAD

**Issue by simkin** [lloesche/valheim-server-docker#194]
I see the following error in the log when I try to join:
`has incompatible version, mine:0.147.3@0.9.4 remote 0.147.3`

This while both Steam as the dedicated server say they are on the latest versions.

This happend after I changed my docker ENV variables to enable the ValheimPlus mod. When i remove the container and re-create it with the mod disabled I can join again.

Kindly elaborate if this is a bug or user error

**Comment by InB4DevOps** [comment]
I found the solution:
stop the container, open the file valheim_plus.cfg in /config/ValheimPlus and change `enforceMod=true` to `enforceMod=false` 

the environment variable `VPCFG_Server_enforceMod` doesn't seem to work any more or is overwritten by ValheimPlus.

**Comment by anpross** [comment]
common user error - i opened the same: #108.

if you dont want to use the client features, you need so set ‚enforceMod‘ to false as described in the readme.md.

**Comment by InB4DevOps** [comment]
In your log, did you also see something like this?

https://github.com/lloesche/valheim-server-docker/issues/171#issuecomment-792766763
