### ISSUE TITLE
Server not showing in community list

### ISSUE THREAD

**Issue by AyRandomUsr** [lloesche/valheim-server-docker#198]
not sure if im missing something.
under the environment tab i have 
server_pass = Mypassword 
and 
server_name = Aname
however the server is not popping up in the community tab. i can connect directly through the ip as well as my friends we just cant get it to show up under community

**Comment by lloesche** [comment]
Also see https://github.com/lloesche/valheim-server-docker#steam-server-favorites--lan-play for details.
