### ISSUE TITLE
Valheim PLUS and variables on dedicated server

### ISSUE THREAD

**Issue by inyfinn** [lloesche/valheim-server-docker#203]
I'm running the server on V+. Client is on V+ too, everything is good but sadly, the server doesn't read my valheim plus config file. Is there an option or a way to make a server to read it? Or (I hope not) do I have to type every variable in sequence, one at a time?

And if so, How to write this variables when there are two windows to fill like name and value, and only one variable?

**Comment by inyfinn** [comment]
Ok. 

i figured it out. Iloesche/valheim-server is creating his own folder "$HOME/config/valheimplus"

And there we have config file to edit, instead of editing file "valheim_plus.cfg" in BepInEx/config.
for u to know

**Comment by lloesche** [comment]
Another way to configure ValheimPlus with this container is through environment variables.
See https://github.com/lloesche/valheim-server-docker#valheimplus-config-from-environment-variables
