### ISSUE TITLE
Server Always Reboots at 9PM PST and 12AM PST (My Time)

### ISSUE THREAD

**Issue by Simpuhl** [lloesche/valheim-server-docker#204]
So I was playing and we all got dced at 9pm PST, and then I was informed by all my buddies playing that it always happens at the exact same time.. so for me its 9pm and then 12pm. Any idea why?

**Comment by InB4DevOps** [comment]
See this

https://github.com/lloesche/valheim-server-docker/issues/65#issuecomment-782759718

The server restarts every day at 5AM (I believe it's UTC). 5AM UTC happens to be 9PM PST. 
I have no idea why it also restarts at 12PM. Maybe it's your router resetting its connection to the ISP?

**Comment by Simpuhl** [comment]
Interesting. Let me read about that and maybe change it to different time. ty for pointing that out.

Hopefully I can change it to a different time

**Comment by InB4DevOps** [comment]
I'd rather change the timezone and leave the restart cron untouched. In the end it's a matter of taste.

**Comment by Simpuhl** [comment]
That's what they are telling me. I don't have my router auto rebooting. It only reboots once a month on Mondays at 3am... 

So do I just type "TZ" for the Environmental Variable and "PST" for the value?

**Comment by Simpuhl** [comment]
I don't see restart other than the one you are saying... here is a screenshot. I'll change it to PST and then try to confirm for sure if its doing it... or it could be something on my end

![image](https://user-images.githubusercontent.com/262571/110589841-d742fb00-812b-11eb-869c-d7b550b655f8.png)

**Comment by Simpuhl** [comment]
Would it be TZ=PST8PDT or TZ=PST ?

**Comment by InB4DevOps** [comment]
PST8PDT is Deprecated. Try TZ=America/Los_Angeles

**Comment by Simpuhl** [comment]
Ok, I will do this tomorrow as they are playing right now. TY. going to mark this resolved!
