### ISSUE TITLE
Synology: new image version fails to start. Uses old version's CMD

### ISSUE THREAD

**Issue by belleDESiRE** [lloesche/valheim-server-docker#208]
On my synology I get this error after updating to the latest version:

Start  container Valheim-Server failed: {"message":"OCI runtime create failed:  container_linux.go:345: starting container process caused \"exec:  \\\"/usr/bin/supervisord\\\": stat /usr/bin/supervisord: no such file or  directory\": unknown"}.

**Comment by laneyweb** [comment]
I have the same error after updating to the latest build.

Start container lloesche-valheim-server1 failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/usr/bin/supervisord\\\": stat /usr/bin/supervisord: no such file or directory\": unknown"}.

**Comment by EnigmaRaptor** [comment]
Same here

**Comment by laneyweb** [comment]
OK, I have it running now again. In the end I decided to delete the docker container (after double checking the config/world data is persistent). I then built a new container with all the settings I had on the other one. It started up OK and is running now.

Just in case this helps anyone else, I'm not sure what happened but I run on a Synology using the UI there and Portainer to manage the containers. I assume there was a config issue when getting the latest build updated. 

Also, yesterday, I had tried to add the persistent _-v $HOME/valheim-server/data:/opt/valheim \_ - I didnt use that on the new build. Maybe a coincidence.

**Comment by belleDESiRE** [comment]
> 
> 
> OK, I have it running now again. In the end I decided to delete the docker container (after double checking the config/world data is persistent). I then built a new container with all the settings I had on the other one. It started up OK and is running now.
> 
> Just in case this helps anyone else, I'm not sure what happened but I run on a Synology using the UI there and Portainer to manage the containers. I assume there was a config issue when getting the latest build updated.
> 
> Also, yesterday, I had tried to add the persistent _-v $HOME/valheim-server/data:/opt/valheim _ - I didnt use that on the new build. Maybe a coincidence.

laneyweb, tx for the tip!

I also deleted the container and the image, re-downloaded the image and recreated the container.
That fixed the issue also for me

note that the thing that changed between the exported config files was the following line:
"cmd" : "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"   --->   "cmd" : "/usr/local/sbin/bootstrap"

**Comment by lloesche** [comment]
When you update the container you'll also have to use that container's entrypoint. Using a new container version with an old container's entrypoint will likely break things. I'm assuming that's some odd Synology specific behavior as Docker by default uses the entrypoint of the image it is running unless you manually override it using the `--entrypoint` commandline argument.

**Comment by belleDESiRE** [comment]
Yep,

up until now the procedure you shared in the readme.md for synology worked every time (re-download latest image, clear container and start)

It only broke with this latest version, so maybe something to mention in the synology section as a potential solution for future issues?

**Comment by lloesche** [comment]
@belleDESiRE already done. Added a dedicated section to the README right underneath the update procedure: https://github.com/lloesche/valheim-server-docker#error-after-download-of-new-container-image

**Comment by EnigmaRaptor** [comment]
Just a comment for clarification. I am running Docker on a Dell Elite Desk with Ubuntu, and I had this problem.  It is definitely not a Synology exclusive issue.  I resolved the issue by switching the option in Portainer to default, which reset the entrypoint to "/usr/local/sbin/bootstrap".  It had previously been set to "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf" in the container from when I first deployed it.  Though, unlike all of my other containers, this container sets the entrypoint to override when it deploys for some reason.  So I expect that if the entrypoint changes again in the future I will have to redeploy and manually set to default to get it to pick up the new configuration.

**Comment by lloesche** [comment]
@EnigmaRaptor yup we have a whole section in the README now https://github.com/lloesche/valheim-server-docker#changing-startup-cmd-in-portainer for Portainer users.

I also pushed a fix that makes it so the old CMD redirects to the new CMD but first prints a warning message notifying users.
