### ISSUE TITLE
How to restore from backup?

### ISSUE THREAD

**Issue by Jwely** [lloesche/valheim-server-docker#209]
I followed the instructions to copy an existing world and spinning up a server with [basic docker usage](https://github.com/lloesche/valheim-server-docker#basic-docker-usage). It ran great for a few days. 

I took the container offline to restore from a recent backup, and removed it: `docker rm my-valheim-server-container`

I extracted one of the backups, slid the files right back into `config/worlds` just as before when transferring the world from windows. Then used the same `docker run` command (with the same args) as before.

Now, the server has a freshly generated world with a new seed, ignoring my world file. 

I've pulled the repo and rebuilt the image but still see the same behavior. What am I missing?

**Comment by davidzyx** [comment]
Make sure the world name is correct for the environment variable `WORLD_NAME` you passed in. It should be the same name as the backup files (`<WORLD_NAME>.fwl`, etc). Another thing you can check is if you actually have another `worlds` directory under `config/worlds`, making it unrecognizable. This can happen very often when you try to unzip an archive into another folder. Just do a quick `ls` check. Also look into `docker logs <container-id>` to see what's going on.

**Comment by lloesche** [comment]
@Jwely were you able to successfully restore your world backup using @davidzyx's instructions? If you still have any trouble let us know and we'll figure it out.
