### ISSUE TITLE
OCI runtime create failed: container_linux.go

### ISSUE THREAD

**Issue by Dekryptid** [lloesche/valheim-server-docker#213]
Pulled the latest image this morning. When I went to start the container again, I'm getting an error. The log shows a message saying:

> OCI runtime create failed: container_linux.go:345: starting container process caused exec: /usr/bin/supervisord: stat /usr/bin/supervisord: no such file or directory: unknown

![image](https://user-images.githubusercontent.com/6528118/110818877-a9f56a80-825b-11eb-8901-ddf7cfd953ae.png)

**Comment by laneyweb** [comment]
Is it possible that it's related to this known issue? https://github.com/lloesche/valheim-server-docker/issues/208

**Comment by lloesche** [comment]
Check https://github.com/lloesche/valheim-server-docker#error-after-download-of-new-container-image

**Comment by Dekryptid** [comment]
Yes. Thank you. I did not peruse the closed items. Apologies.
