### ISSUE TITLE
Error on Container start when updating to latest image

### ISSUE THREAD

**Issue by podbiker** [lloesche/valheim-server-docker#214]
I tried to update to the latest image using Portainer a few minutes ago.

The following messages is displayed and the new container does not start:

Failure
OCI runtime create failed: container_linux.go:367 starting container process caused: exec_ "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directory: unknown

The new image was downloaded at 2021-03-11 20:01:40 TZ Europe/Berlin
Digest:sha256:8e57d4f0a8e3270f23ace0bb5c1ce957c537d1e859695411edf5215089cd1fde

The old image dates from at 2021-03-08 22:44:40 TZ Europe/Berlin

Luckily Portainer does not discard the old container until the new copy is started successfully, therefore recovery was easy and I am running the old image for now.

I suspect the addition of Supervisor has something to do with this. If so, is there a specific image version I need to pull and start first before switching to the latest image or is this something that needs to be fixed within the image?

Thanks in advance.

**Comment by lloesche** [comment]
I just pushed a fix for users with this issue. If you pull the `:latest` image you'll be greeted with the following info now:

```
!!! ATTENTION !!!

You are seeing this message because your container manager is executing the wrong startup CMD.

It is running the CMD from an old version of lloesche/valheim-server on a new version of lloesche/valheim-server

If you are using a Synology NAS check this help page:
https://github.com/lloesche/valheim-server-docker#error-after-download-of-new-container-image

If you are on a different system like e.g. Portainer you have to delete the container and re-create it.

All the files in `/config` and `/opt/valheim` can be retained of course!

!!! ATTENTION !!!
```
and then the container will start as normal. Would still recommend to re-create.

Also see #208, #213 and #211 🙂

**Comment by podbiker** [comment]
Portainer remembers the startup CMD when "recreate" is used to update the container by pulling the new image in the process.

It can be changed in the "CMD" field when using "dublicate/edit".

When doing so the original container must be stopped and renamed (append _old or similar) and also stopped prior to using "dublicate/edit". Otherwise problems with already used ports and IPs will prevent the creation of the new container.

After the new container is up, the old container can be deleted alongside the old image.

**Comment by lloesche** [comment]
@podbiker can you create screenshots and send a PR for the README? This might be useful for others.

**Comment by podbiker** [comment]
I can try
