### ISSUE TITLE
/config/worlds does not contain any .db files

### ISSUE THREAD

**Issue by ckoryom** [lloesche/valheim-server-docker#221]
Hi @lloesche thank you for your great contribution!

I'm having a small issue right now, none of the backups that are generated contain any .db files. I'm not sure why.

I've also attached into the container with bash and went to the /config/worlds and the world folder also doesn't have any .db files. Just the .fwl file.

Do you have any idea what might be the issue?

Thanks!

**Comment by lloesche** [comment]
I mean it makes sense that the backups don't have any `.db` files if your `/config/worlds` folder has none. The backup script just backups whatever it finds in `/config/worlds`.

The `.db` files are created the first time the server saves a new world. If you create a new server only the `.fwl` file will exist.
Is `/config` mounted to a persistent directory on the host? The only situation I can think of right now is if you haven't persisted the config data. But you'd notice that pretty soon as your server would always start from a freshly generated world instead of loading the old one.

**Comment by ckoryom** [comment]
@lloesche interesting. I'm not mounting the /config directory with a volume. Just testing inside the container without the volume.

Just started a fresh new world, same thing. No .db file was created.

**Comment by ckoryom** [comment]
Another try with the volume:  -v $HOME/valheim-server/config:/config

Same thing, when the World is created. The "world" folder only has the .fwl file. That's weird.

**Comment by lloesche** [comment]
I just explained that when the world is created there's only a `.fwl` file. Nothing weird about it. It is the first time the server saves the world that the `.db` files are stored on disk. Make sure to run with `-v $HOME/valheim-server/config:/config -v $HOME/valheim-server/data:/opt/valheim`, play the game and after half an hour or so the `.db` files will show up.

**Comment by InB4DevOps** [comment]
Did you actually change something in the world eg build or destroy something?
Maybe the file is only written once you make changes?

**Comment by lloesche** [comment]
@InB4DevOps in my tests building doesn't create the `.db` files. The server is on like a 20 minute interval after which the world is stored. With ValheimPlus mod you can manipulate the `autoSaveInterval`. Also you have to connect to the server once for parts of the world to be instantiated. You can also enforce saving by gracefully stopping the server or executing the `save` admin command.

**Comment by ckoryom** [comment]
So I played 10 min to test it, build a small house just for testing etc. 

Never ran the save command actually, as you say building doesnt create the db file.

Also stopped the container, but didn't see a db file there either.

looks like the db file might not be created after playing for a 20 min like you mention or hit the save command.

I'm going to test that right now

**Comment by ckoryom** [comment]
Ok just figured it out:

You were right: there's an automatic save after around 20min or so. Running save creates the actual db files.

I thought SIGTERM was also executing the valheim-backup script but it's not. Just modified it a bit on my end so whenever there is a SIGTERM I can backup the files with your script and send them to s3. This is working pretty good now.

Thanks!

**Comment by lloesche** [comment]
@ckoryom the backup script reacts to `SIGHUP`.
