### ISSUE TITLE
Possible for instructions on QNAP? 

### ISSUE THREAD

**Issue by wolvyreen** [lloesche/valheim-server-docker#224]
Incredible job on this container. Thank you so much but I have not been able to get it to work on my QNAP Container app.

The image shows up and I can set it up just fine.

The server starts up and says Game server connected but never shows up in the Steam/Valheim server list. I've tried manually connecting to it using ip:2457 but still no luck. Ports are all forwarded on QNAP as well as Router.

Firewall on PC disabled. Still nothing.

Not sure what I'm doing wrong. Done my best to follow every instruction but none of them are for QNAP.

Any chances of screenshots for QNAP like you did for Synology?

**Comment by lloesche** [comment]
I don't have a QNAP but if anyone who's running this on a QNAP would like to submit a PR for the README I'll happily merge it.

**Comment by Shawak** [comment]
Did you try connecting on port 2456 also?

**Comment by wolvyreen** [comment]
> Did you try connecting on port 2456 also?

Yes I did. :-)  but the server doesnt even show up in the steam server list or the Valheim community list.  So I tried manually adding the server with port 2456 and 2457 but the steam server directory just shows not running.

I am suspecting it has something to do with the QNAP configuration and the networking. Unfortunately I am no network guru so don't even know where to start...

:-(

**Comment by InB4DevOps** [comment]
Can you post a screenshot of your port configuration in docker?

**Comment by wolvyreen** [comment]
Hello :-)

This is the output of the command you gave me:

[~] # docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a
CONTAINER ID   NAMES               PORTS
1098eaf9b914   My-Valheim-Server
[~] #

![bridge-settings](https://user-images.githubusercontent.com/8437176/111127118-1f26af80-857c-11eb-84d0-45ff3d8fca5b.png)

Qnap does not allow you to specify ports for the container in order to bridge the connection.  I assumed the bridging of it would take on the settings of the main adapter switch which has those ports opened.

**Comment by InB4DevOps** [comment]
Well, the game server is connected to Steam - that's an outgoing connection. 
But since you didn't map the ports into the container the server can not handle incoming connections. 

In your screenshot in the top left it says "Advanced settings". Do you have port mapping options hidden there?

**Comment by InB4DevOps** [comment]
Since you seem to have shell access to the docker command you can also run the container via a docker command as shown here:
https://github.com/lloesche/valheim-server-docker#basic-docker-usage

You will of course have to specify your volume mappings etc.

**Comment by wolvyreen** [comment]
That makes sense.  However, we do not have the option mapping ports when the container is in bridged mode.

Regarding your question about Advanced Settings: The screenshot is the screen you see when you click advanced settings.

The only time I can see the port forwarding options is if I change Bridge to NAT but then what IP do I use to connect to the server from within the Game as the IP that is allocated when using NAT is not the same subnet as the adapter.

![nat-settings](https://user-images.githubusercontent.com/8437176/111136743-b8f35a00-8586-11eb-9e2f-c21d9e14700a.png)

**Comment by InB4DevOps** [comment]
> The only time I can see the port forwarding options is if I change Bridge to NAT but then what IP do I use to connect to the server from within the Game as the IP that is allocated when using NAT is not the same subnet as the adapter.

Use the IP of your QNAP or if you have forwarded the ports in your router to the QNAP use your external IP.

**Comment by wolvyreen** [comment]
> > The only time I can see the port forwarding options is if I change Bridge to NAT but then what IP do I use to connect to the server from within the Game as the IP that is allocated when using NAT is not the same subnet as the adapter.
> 
> Don't use the container IP, use the IP of your QNAP or - if you have forwarded the ports in your router to the QNAP - use your external IP.
> 
> Oh, and use NAT. The container must noch have the same IP as your QNAP. That's what NAT is for ;-)

ok, let me test the NAT options and see how it goes.  Thanks friend!  I will let you know.

**Comment by wolvyreen** [comment]
Ok, after some extensive testing, I managed to get everything working. Connected to the server and a friend also did.

Strange though, I was able to see the server in the community list but my friend had to connect using the IP and port 2456.  Not 2457 because she couldn't see the server in the list. Very strange because everyone says to connect on 2457.

Anyway...

I only now need to figure out how to mount the config folder and /opt/Valheim folder so that I don't have to download it on every start.  No clue how to do that.

Any suggestions?

**Comment by lloesche** [comment]
@wolvyreen in the game you connect to 2456. In Steam server browser you query 2457. That's the Steam library query port which then tells the Steam client that there's a server running on 2456 🙂

**Comment by wolvyreen** [comment]
> @wolvyreen in the game you connect to 2456. In Steam server browser you query 2457. That's the Steam library query port which then tells the Steam client that there's a server running on 2456 🙂

Ah ok. Cool.  Any idea how to mount the config and data folders in these containers?? Synology has the option to set volumes but it doesn't look like QNAP does the same.

**Comment by InB4DevOps** [comment]
Check this page and search for shared folders. You can also see that settings page in your screenshot.

https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/

**Comment by wolvyreen** [comment]
I see there has been some QNAP Screenshots uploaded to the instructions.  :-D  This is awesome.  going to test the instructions out

**Comment by lloesche** [comment]
@wolvyreen perfect! let me know if anything does not work.

**Comment by lloesche** [comment]
Big thank you to @mmalyska for submitting this PR #234

**Comment by wolvyreen** [comment]
I tested the instructions out. Works ALMOST perfectly😊

A little more explanation is needed when submitting the YAML to say that before your can click the create button, you need to verify the YAML.

One thing I did in the YAML was change the resources to limit the CPU and memory. I have found on QNAP that sometimes the server can completely consume all the CPU resources and kill the server so I limit the core usage to 60% and memory to 50% but I have 8GB ram in mine so 50% is 4GB. It will be different for everyone.

How do the instructions work for updating the image? Synology requires you to clear the container but with an APP on QNAP, you can't do that as far as I can see.

**Comment by mmalyska** [comment]
@wolvyreen Regarding updating image. The steps for getting new version are in README too. 
But you can always recreate container. All you need to do is to have your **yml** definition backed up somewhere. You can delete container safely and recreate it. All your data is saved in volumes defined in **yml**.
One think I noticed is that when you stop the server and start it manually QNAP sometimes updates image, but to be sure it's better to pull image manually and restart container.

**Comment by wolvyreen** [comment]
Thanks  :-)  I will just use the instructions ion the read me.

I do feel that the resources allocation in the yaml should be mentioned though as it can render the entire QNAP useless and the end user might have no clue why.

thanks for all the work around this. :-)

**Comment by mmalyska** [comment]
And just out of curiosity what settings have you used for limiting resources?

**Comment by wolvyreen** [comment]
cpus: 0.6
mem_limit: 4096M

the 4096M is only because I have 8GB in my NAS

**Comment by mmalyska** [comment]
I added deploy limits for QNAP. https://github.com/lloesche/valheim-server-docker/pull/238
I added minimal resources according to documentation.

**Comment by lloesche** [comment]
Awesome, this sounds great! Thank you @wolvyreen for testing, and thank you @mmalyska for writing the instructions and submitting the two PRs!
I'll close the issue but feel free to open a new one or keep discussing in here if you find anything else that could be improved.

**Comment by owlery7** [comment]
![qnap container](https://github.com/lloesche/valheim-server-docker/assets/89202712/6b6f19c6-a8bf-44c3-8010-b47c23bbee21)
I have never used container station before and am having trouble following the instructions from the readme file as the GUI has changed.
Is there any good pre requisite instruction for setting up the server?

Thanks
