### ISSUE TITLE
(DEBUG) Waiting for server to listen on port 2456

### ISSUE THREAD

**Issue by keinou** [lloesche/valheim-server-docker#226]
(DEBUG) Waiting for server to listen on port 2456
In log only see this message.

**Comment by bonesoul** [comment]
same here, what was the issue caused by?

**Comment by eddieowens** [comment]
@bonesoul I stumbled upon this issue with the same problem and it turned out to be a resource issue. In my case I was being throttled by CPU so it may be that you're short on resources. You can check out https://github.com/lloesche/valheim-server-docker#system-requirements for more info.
