### ISSUE TITLE
Complication related to 'Deploying with docker-compose'

### ISSUE THREAD

**Issue by brt-h** [lloesche/valheim-server-docker#228]
Thank you for making this! 

This was my first time using Docker so I might be totally wrong, but I think the readme may benefit from clarification with regard to deploying with docker-compose as root.

I am not managing docker as a non-root user so when entered `sudo docker-compose up` I encountered `ERROR: Couldn't find env file: /root/valheim-server/valheim.env`

I was able to solve this by going into the `docker-compose.yaml` and changing `$HOME/valheim-server/valheim.env` to the specific path for my computer `/home/brt/valheim-server/valheim.env` 

EDIT: Looks like the mounted volumes need to be specified as well in the `docker-compose.yaml` (or I need to copy my existing world into the `admin:///root/valheim-server/config/worlds` folder) -- maybe I should start fresh after setting up a non-root user to manage docker

EDIT2: Was able to load into the world I imported but there were strange issues- could use workbench/forge to repair but couldn't open any boxes- could go through some portals, but not others. Probably a networking issue since someone was able to connect from outside my network with no problems, but my device being on the same network has issues.

**Comment by lloesche** [comment]
You shouldn't have to `sudo`. This is less of an issue with this container and more of an issue with using Docker. I recommend https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

And then https://docs.docker.com/engine/security/userns-remap/ might also make sense. Depending on what kind of environment you're running in.

**Comment by brt-h** [comment]
Thanks for clearing that up!
