### ISSUE TITLE
Supervisor services not running

### ISSUE THREAD

**Issue by turbo-david** [lloesche/valheim-server-docker#230]
I have added the following config to my docker-compose file for Supervisor to run
SUPERVISOR_HTTP=true
SUPERVISOR_HTTP_USER=admin
SUPERVISOR_HTTP_PASS=password

I see the port open on the docker container: 0.0.0.0:9001->9001/tcp   valheim-server_valheim_1

When I connect to it via HTTP i'm not able to hit the page. Any way to troubleshoot this?

**Comment by lloesche** [comment]
One of the first log lines should be
```
2021-03-15 23:11:06 [1] (INFO) Supervisor http server activated
2021-03-15 23:11:07,079 INFO Included extra file "/usr/local/etc/supervisor/conf.d/http_server.conf" during parsing
```

do you have that in your log?

**Comment by turbo-david** [comment]
2021-03-14 14:06:56 [1] (ERROR) SUPERVISOR_HTTP enabled but SUPERVISOR_HTTP_PASS is empty - ignoring request to run supervisor http server <<< I guess I can't have a basic password :-)

**Comment by turbo-david** [comment]
Actually it still will not load with that added to the .env

**Comment by turbo-david** [comment]
I was able to get it running without docker compose.

**Comment by turbo-david** [comment]
And now it is working only change I made was I removed PERMISSIONS_UMASK=022 from the .env file.

**Comment by lloesche** [comment]
> I guess I can't have a basic password :-)

You should be able to have any password, there's no complexity check or anything like that.

> And now it is working only change I made was I removed PERMISSIONS_UMASK=022 from the .env file.

That's peculiar. Shouldn't have any influence on other variables. And it's only used in scripts unrelated to the supervisor http server.

Anyway, glad it is working for you now! 👍 🎉
