### ISSUE TITLE
Way to specify the seed on creation?

### ISSUE THREAD

**Issue by wolvyreen** [lloesche/valheim-server-docker#237]
Is there a way to specify the seed of the world maybe in the environment variables or something?

**Comment by InB4DevOps** [comment]
WORLD_NAME

**Comment by wolvyreen** [comment]
> WORLD_NAME

Isn't that the name of the world?  I've specified the same WORLD_NAME in every one of my container tests and I get a different world everytime.

If the WORLD_NAME was the seed, then wouldn't I see the same world everytime I create a new container if I use the same name??

**Comment by InB4DevOps** [comment]
> > WORLD_NAME
> 
> 
> 
> Isn't that the name of the world?  I've specified the same WORLD_NAME in every one of my container tests and I get a different world everytime.
> 
> 
> 
> If the WORLD_NAME was the seed, then wouldn't I see the same world everytime I create a new container if I use the same name?? 

Good point. Up until now I thought the world name was also the seed. Sorry if this cause any confusion 🙂

**Comment by lloesche** [comment]
You will have to create the world in client and then copy the world file. I don't know of any cli arg that would allow specifying the seed.

**Comment by wolvyreen** [comment]
> You will have to create the world in client and then copy the world file. I don't know of any cli arg that would allow specifying the seed.

That sucks but it's a workaround. Thanks 😊👍🏻

**Comment by Dani20000** [comment]
Sorry if i ask, i'm new on using Docker... how to do that? I already volume mounted into /config, and with "docker cp" i can copy files from volume to pc but how to do the opposite (overwriting them obviously, otherwhise there will be 2 worlds in the folder)? Thank u

**Comment by Shawak** [comment]
You can also use `docker cp` to copy from your file system into the container, just check out the [docs](https://docs.docker.com/engine/reference/commandline/cp/). Depending on your setup, you can also just copy your world files to the mounted volume.

**Comment by Dani20000** [comment]
> You can also use `docker cp` to copy from your file system into the container, just check out the [docs](https://docs.docker.com/engine/reference/commandline/cp/). Depending on your setup, you can also just copy your world files to the mounted volume.

Thank you
