### ISSUE TITLE
Unable to import save

### ISSUE THREAD

**Issue by sroche0** [lloesche/valheim-server-docker#242]
I've tried several times to import my save from another dedicated server and the container seems to generate a new world on every launch. The initial launch after wiping the mounted folders and starting fresh seems to work. The settings/worlds directory is created and the server launches.

    shawn@citadel:~/dotfiles/docker > \ls -la /opt/valheim-server/settings/worlds/
    total 192
    drwxr-xr-x 2 root root   4096 Mar 19 10:58 .
    drwxr-xr-x 4 root root   4096 Mar 19 10:59 ..
    -rw-r--r-- 1 root root 180545 Mar 19 10:57 pigeon-grindhouse.db
    -rw-r--r-- 1 root root     45 Mar 19 10:58 pigeon-grindhouse.fwl

Then I stop the container and copy the existing world files i have over the ones that were generated, then restart the container. For some reason i still see world generation in the docker logs even though it should be loading the existing save. When i connect to the server it's a new world starting on day 1 with nothing in it. Restarting the container with docker-compose at this point seems to generate completely different save named Dedicated which is oddly also an order of magnitude larger than the existing save im using on my non docker server

    shawn@citadel:~/dotfiles/docker > \ls -la /opt/valheim-server/settings/worlds/
    total 2056
    drwxr-xr-x 2 root root    4096 Mar 19 11:01 .
    drwxr-xr-x 4 root root    4096 Mar 19 10:59 ..
    -rw-r--r-- 1 root root 1903817 Mar 19 11:01 Dedicated.db
    -rw-r--r-- 1 root root      45 Mar 19 11:01 Dedicated.fwl
    -rw-r--r-- 1 root root  180545 Mar 19 10:57 pigeon-grindhouse.db
    -rw-r--r-- 1 root root      45 Mar 19 10:58 pigeon-grindhouse.fwl

It almost seems like the server is not able to read the existing save so generates a new one, but i dont see anything in the logs about it failing to load the pigeon-grindhouse world. The permissions of the files are identical so it should be able to load the old save, it just doesnt. Here is my docker-compose block for valheim. Im using non standard ports for the moment so the existing server can stay up while i work on migrating it to docker.

    valheim:
      image: lloesche/valheim-server
      container_name: valheim
      volumes:
        - /opt/valheim-server/settings:/config
        - /opt/valheim-server/data:/opt/valheim
      ports:
        - "2460-2462:2456-2458/udp"
      environment:
        - SERVER_NAME=redacted
        - SERVER_PASS=redacted
        - SERVER_PUBLIC=1
        - WORLD_NAME=pigeon-grindhouse
        - VALHEIM_PLUS=false

Here are the docker logs from the second launch. [valheim.log](https://github.com/lloesche/valheim-server-docker/files/6172365/valheim.log)

**Comment by lloesche** [comment]
What if you `docker exec -it valheim env`?
Is `WORLD_NAME` set to the right value?

**Comment by sroche0** [comment]
Yes it is 

    shawn@citadel:~/dotfiles/docker > docker exec -it valheim env
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    HOSTNAME=329e197aeb1d
    TERM=xterm
    SERVER_NAME=redacted
    SERVER_PASS=redacted
    SERVER_PUBLIC=1
    WORLD_NAME=pigeon-grindhouse
    VALHEIM_PLUS=false
    DEBIAN_FRONTEND=noninteractive
    HOME=/root

**Comment by lloesche** [comment]
That's very peculiar can you please paste the output of:
```
docker exec -it valheim bash -c "ps ax | cat"
```

I'm especially interested in the line containing `/opt/valheim/server/valheim_server.x86_64`.

**Comment by sroche0** [comment]
root@329e197aeb1d:/# ps -aux | grep valheim
    root        36  0.0  0.0   7088  2900 ?        S    Mar19   0:04 /bin/bash /usr/local/bin/valheim-updater
    root       159  0.0  0.0   6992  2368 ?        S    Mar19   0:04 /bin/bash /usr/local/bin/valheim-backup
    root      1827  0.0  0.0   3084   888 pts/0    S+   14:47   0:00 grep valheim
    root     15348  0.0  0.0   6992  3568 ?        S    05:00   0:00 /bin/bash /usr/local/bin/valheim-server
    root     15352 19.8 10.1 8473024 1669280 ?     Sl   05:00 116:29 /opt/valheim/server/valheim_server.x86_64 -nographics -batchmode -name redacted -port 2456 -world pigeon-grindhouse -public 1 -password redacted
    root     15354  0.0  0.0   6992  1940 ?        S    05:00   0:00 /bin/bash /usr/local/bin/valheim-server
    root     15356  0.0  0.0   6992  1940 ?        S    05:00   0:00 /bin/bash /usr/local/bin/valheim-server

**Comment by lloesche** [comment]
Okay I added some more debug logging.
Delete the `worlds/Dedicated.*` files. Then pull the latest version of the container and run it with `DEBUG_START_FRESH=true` to make it wipe all existing downloaded server files (config/worlds are not touched). 

Then attach the startup log here. Right after `Running Valheim Server` there's now a new log line starting with `Server config is`.

**Comment by TomatoPal** [comment]
I was having this same issue and this is how I resolved it.

I was downloading files from my current host then moving them over to my server doing a "chmod/chgrp root" and renaming the .db/.fwl files from the current name to the matching name for what I set in WORLD_NAME. I tried launching this with ECS on Fargate and with Docker on an EC2 instance and got the same result. 

Then I was looking through the output of the container after doing "docker-compose up" and I found this:
`valheim_1  | Mar 24 00:28:25 /supervisord: valheim-server 03/24/2021 00:28:25: Load world redacted
valheim_1  | Mar 24 00:28:25 /supervisord: valheim-server 03/24/2021 00:28:25:   missing world.dat`

So "redacted" is the original name of the .db/.fwl files from my host, so I moved the .db/.fwl files back to the original naming, as well as changing the WORLD_NAME to redacted, and the world loaded with no problem at all.

I have not tried this again on Fargate but I suspect it will work and I will test it shortly. 

@sroche0 - I am not sure if you are changing the name at all when moving it to the new location but if you are it would be a good test to try leaving them as is and changing the WORLD_NAME variable. I do see you said "copy the existing world files I have over the ones that were generated" but I am not sure if you are making any other changes. 

Hope this helps!

**Comment by chdesigns** [comment]
I am having similar issues to this. It appears it is loading some of the saves file but not all. The map discovered is being loading but no structures. Everything I have built is gone. 


valheim-server-pers | Mar 25 15:46:59 /supervisord: valheim-server [Info   : Unity Log] Version generator started.
valheim-server-pers | Mar 25 15:46:59 /supervisord: valheim-server Version generator started.
valheim-server-pers | Mar 25 15:46:59 /supervisord: valheim-server [Info   : Unity Log] 03/25/2021 15:46:59: Registering lobby
valheim-server-pers | Mar 25 15:46:59 /supervisord: valheim-server 03/25/2021 15:46:59: Registering lobby
valheim-server-pers | Mar 25 15:47:02 /supervisord: valheim-server DEBUG - [142] - Server is now listening on UDP port 2456
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server [Info   : Unity Log] 03/25/2021 15:47:04: Load world FirstWorld
**valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server 03/25/2021 15:47:04: Load world FirstWorld
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server [Info   : Unity Log] 03/25/2021 15:47:04:   missing world.dat**
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server 03/25/2021 15:47:04:   missing world.dat
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server [Info   : Unity Log] 03/25/2021 15:47:04: Audioman already exist, destroying self
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server 03/25/2021 15:47:04: Audioman already exist, destroying self
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server [Info   : Unity Log] Version generator started.
valheim-server-pers | Mar 25 15:47:04 /supervisord: valheim-server Version generator started.
valheim-server-pers | Mar 25 15:47:05 /supervisord: valheim-server Unloading 508 unused Assets to reduce memory usage. Loaded Objects now: 86413

root@docker-game:/home/valheim/valheim-server/config-pers/worlds# ll
total 6728
drwxr-xr-x 2 root root    4096 Mar 25 15:45 ./
drwxr-xr-x 7 root root    4096 Mar 25 14:52 ../
-rw-r--r-- 1 root root 6873730 Mar 25 15:45 WorldPluspriv.db
-rw-r--r-- 1 root root      46 Mar 25 15:45 WorldPluspriv.fwl

**Comment by sroche0** [comment]
@lloesche the extra DEBUG log shows the world name as the save file,, pigeon-grindhouse but i still have the same problem where its dropping me in a fresh world. I also see later in the logs it loads world Dedicated.
    
    shawn@citadel:~/dotfiles/docker > docker stop valheim
    valheim

    shawn@citadel:~/dotfiles/docker > docker pull lloesche/valheim-server
    Using default tag: latest
    latest: Pulling from lloesche/valheim-server
    1cb497e05df3: Pull complete
    4f483f906707: Pull complete
    d9e847789c8c: Pull complete
    cc24256a3085: Pull complete
    Digest: sha256:5902ebf1b80ef2e4420a20ce8d473b17b5223ce730d1bbb5b868df1d9a211fc3
    Status: Downloaded newer image for lloesche/valheim-server:latest
    docker.io/lloesche/valheim-server:latest

    shawn@citadel:~/dotfiles/docker > sudo rm /opt/valheim-server/settings/worlds/Dedicated.*

    shawn@citadel:~/dotfiles/docker > grep -A10 valheim docker-compose.yaml
      valheim:
        image: lloesche/valheim-server
        container_name: valheim
        volumes:
          - /opt/valheim-server/settings:/config
          - /opt/valheim-server/data:/opt/valheim
        ports:
          - "2460-2462:2456-2458/udp"
        environment:
          - SERVER_NAME=redacted
          - SERVER_PASS=redacted
          - SERVER_PUBLIC=1
          - WORLD_NAME=pigeon-grindhouse
          - VALHEIM_PLUS=false
          - DEBUG_START_FRESH=true

    shawn@citadel:~/dotfiles/docker > docker-compose up -d
    Recreating valheim ... done

    shawn@citadel:~/dotfiles/docker > docker logs -f valheim


    Mar 25 19:45:28 /supervisord: valheim-server INFO - Running Valheim Server
    Mar 25 19:45:28 /supervisord: valheim-server DEBUG - [143] - Server config is name: The Pigeon Coop, port: 2456/udp, world: pigeon-grindhouse, public: 1, V+ mod: false
    Mar 25 19:45:28 /supervisord: valheim-server DEBUG - [143] - Waiting for server to listen on UDP port 2456
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968705     150 main.go:63] Configuring Valheim server log filter
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968819     150 main.go:83] Removing log lines starting with '(Filename:'
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968846     150 main.go:76] Removing log lines matching ' '
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968863     150 main.go:112] Removing invalid UTF-8 chars: true
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968880     150 main.go:109] Removing empty log lines: true
    Mar 25 19:45:28 /supervisord: valheim-server I0325 19:45:28.968896     150 main.go:83] Removing log lines starting with 'src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp'
    Mar 25 19:45:28 /supervisord: valheim-server Found path: /opt/valheim/server/valheim_server.x86_64
    Mar 25 19:45:28 /supervisord: valheim-server Mono path[0] = '/opt/valheim/server/valheim_server_Data/Managed'
    Mar 25 19:45:28 /supervisord: valheim-server Mono config path = '/opt/valheim/server/valheim_server_Data/MonoBleedingEdge/etc'
    Mar 25 19:45:28 /supervisord: valheim-server Preloaded 'libsteam_api.so'
    Mar 25 19:45:28 /supervisord: valheim-server Initialize engine version: 2019.4.20f1 (6dd1c08eedfa)
    Mar 25 19:45:28 /supervisord: valheim-server [Subsystems] Discovering subsystems at path /opt/valheim/server/valheim_server_Data/UnitySubsystems
    Mar 25 19:45:28 /supervisord: valheim-server Forcing GfxDevice: Null
    Mar 25 19:45:28 /supervisord: valheim-server GfxDevice: creating device client; threaded=0
    Mar 25 19:45:28 /supervisord: valheim-server NullGfxDevice:
    Mar 25 19:45:28 /supervisord: valheim-server     Version:  NULL 1.0 [1.0]
    Mar 25 19:45:28 /supervisord: valheim-server     Renderer: Null Device
    Mar 25 19:45:28 /supervisord: valheim-server     Vendor:   Unity Technologies
    Mar 25 19:45:28 /supervisord: valheim-server Begin MonoManager ReloadAssembly
    Mar 25 19:45:29 /supervisord: valheim-server - Completed reload, in  0.051 seconds
    Mar 25 19:45:29 /supervisord: valheim-server UnloadTime: 0.722716 ms
    Mar 25 19:45:29 /supervisord: valheim-server 03/25/2021 19:45:29: Starting to load scene:start
    Mar 25 19:45:33 /supervisord: valheim-server DEBUG - [143] - Waiting for server to listen on UDP port 2456
    Mar 25 19:45:38 /supervisord: valheim-server HDR Render Texture not supported, disabling HDR on reflection probe.
    Mar 25 19:45:38 /supervisord: valheim-server HDR Render Texture not supported, disabling HDR on reflection probe.
    Mar 25 19:45:38 /supervisord: valheim-server Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
    Mar 25 19:45:38 /supervisord: valheim-server UnloadTime: 4.309274 ms
    Mar 25 19:45:38 /supervisord: valheim-server Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
    Mar 25 19:45:38 /supervisord: valheim-server HDR Render Texture not supported, disabling HDR on reflection probe.
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Valheim version:0.148.6
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Render threading mode:SingleThreaded
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Get create world pigeon-grindhouse
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Using environment steamid 892970
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Using steam APPID:892970
    Mar 25 19:45:38 /supervisord: valheim-server [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
    Mar 25 19:45:38 /supervisord: valheim-server CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
    Mar 25 19:45:38 /supervisord: valheim-server CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamGameServer013 /
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamUtils009 /
    Mar 25 19:45:38 /supervisord: valheim-server Setting breakpad minidump AppID = 892970
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamGameServer013 / GameServer
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamUtils009 / Utils
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamNetworking006 / Networking
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamGameServerStats001 / GameServerStats
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): STEAMHTTP_INTERFACE_VERSION003 / HTTP
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): STEAMINVENTORY_INTERFACE_V003 / Inventory
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): STEAMUGC_INTERFACE_VERSION014 / UGC
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): STEAMAPPS_INTERFACE_VERSION008 / Apps
    Mar 25 19:45:38 /supervisord: valheim-server [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamNetworkingUtils003 /
    Mar 25 19:45:38 /supervisord: valheim-server RecordSteamInterfaceCreation (PID 146): SteamNetworkingSockets008 /
    Mar 25 19:45:38 /supervisord: valheim-server Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
    Mar 25 19:45:38 /supervisord: valheim-server Warning: failed to set thread priority: set failed for priority 8
    Mar 25 19:45:38 /supervisord: valheim-server Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Server ID 90071992547409920
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Authentication:k_ESteamNetworkingAvailability_Waiting
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Steam game server initialized
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Missing audio clip in music respawn
    Mar 25 19:45:38 /supervisord: valheim-server 03/25/2021 19:45:38: Builder started
    2021-03-25 19:45:38,973 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
    Mar 25 19:45:38 /supervisord: valheim-server DEBUG - [143] - Waiting for server to listen on UDP port 2456
    Mar 25 19:45:38 /supervisord: valheim-updater valheim-server: started
    Mar 25 19:45:39 /supervisord: valheim-server 03/25/2021 19:45:39: Loaded localization English
    Mar 25 19:45:39 /supervisord: valheim-server 03/25/2021 19:45:39: Game server connected
    Mar 25 19:45:39 /supervisord: valheim-server Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 86066.
    Mar 25 19:45:39 /supervisord: valheim-server Total: 53.554089 ms (FindLiveObjects: 3.294991 ms CreateObjectMapping: 11.122014 ms MarkObjects: 38.837293 ms  DeleteObjects: 0.286828 ms)
    Mar 25 19:45:39 /supervisord: valheim-server Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
    Mar 25 19:45:39 /supervisord: valheim-server UnloadTime: 14.689646 ms
    Mar 25 19:45:39 /supervisord: valheim-server HDR Render Texture not supported, disabling HDR on reflection probe.
    Mar 25 19:45:39 /supervisord: valheim-server HDR Render Texture not supported, disabling HDR on reflection probe.
    Mar 25 19:45:39 /supervisord: valheim-server 03/25/2021 19:45:39: Zonesystem Awake 219
    Mar 25 19:45:39 /supervisord: valheim-server 03/25/2021 19:45:39: DungeonDB Awake 219
    Mar 25 19:45:39 /supervisord: valheim-server 03/25/2021 19:45:39: Registering lobby
    Mar 25 19:45:43 /supervisord: valheim-server 03/25/2021 19:45:43: Load world Dedicated
    Mar 25 19:45:43 /supervisord: valheim-server 03/25/2021 19:45:43:   missing world.dat
    Mar 25 19:45:43 /supervisord: valheim-server 03/25/2021 19:45:43: Audioman already exist, destroying self
    Mar 25 19:45:43 /supervisord: valheim-server Unloading 508 unused Assets to reduce memory usage. Loaded Objects now: 86399.
    Mar 25 19:45:43 /supervisord: valheim-server Total: 71.515312 ms (FindLiveObjects: 4.734151 ms CreateObjectMapping: 12.251392 ms MarkObjects: 51.415428 ms  DeleteObjects: 3.101939 ms)
    Mar 25 19:45:43 /supervisord: valheim-server DEBUG - [143] - Server is now listening on UDP port 2456
    Mar 25 19:45:46 /supervisord: valheim-server 03/25/2021 19:45:46: Zonesystem Start 219
    Mar 25 19:45:46 /supervisord: valheim-server 03/25/2021 19:45:46: Generating locations
    Mar 25 19:45:46 /supervisord: valheim-server 03/25/2021 19:45:46: Checking for location duplicates
    Mar 25 19:46:10 /supervisord: valheim-server 03/25/2021 19:46:10:  Done generating locations, duration:23838.491 ms


If i remove the DEBUG_START_FRESH tag from the yaml and restart the container, Dedicated.db and Dedicated.fwl world files are generated again.

    shawn@citadel:~/dotfiles/docker > ls /opt/valheim-server/settings/worlds/
    total 2.1M
    -rw-r--r-- 1 1.9M Mar 25 15:55 Dedicated.db
    -rw-r--r-- 1   45 Mar 25 15:55 Dedicated.fwl
    -rw-r--r-- 1 177K Mar 25 15:58 pigeon-grindhouse.db
    -rw-r--r-- 1   45 Mar 25 15:58 pigeon-grindhouse.fwl

**Comment by sroche0** [comment]
Oh my god, i was copying the wrong world files. I copied them  my gaming PC and tried to open them as a local world and nothing was there. I forgot i run the bare metal server as a different user. IDK why there's even a `~/.config/unity3d/IronGate/Valheim/worlds/` for my admin user. It must be from one of the first time i attempted to set it up and is only half generated or something causing the server to generate a new world with the default name Dedicated.

Sorry for the wild goose chase @lloesche, looks like this was plain old PEBKAC
