### ISSUE TITLE
Env vars DNS_1 and DNS_2 only work for containers started using the systemd unit

### ISSUE THREAD

**Issue by lloesche** [lloesche/valheim-server-docker#25]
The documentation lists `DNS_1` and `DNS_2` as environment variables used to determine which DNS servers are used by the server inside the container. This currently only works for containers started using the systemd unit file. When running the container on say a Synology NAS or basically any environment other than the one described the variables have no effect.

We should either document this behavior or fix it.

**Comment by lloesche** [comment]
@sebbrandt87 ^

**Comment by Toucan-Sam** [comment]
Maybe a silly question, but what is the reason you implemented DNS settings for the container? Typically just letting the system handle it's own DNS is usually enough? Containers inherit the hosts DNS.

Docker containers also support this natively.
https://docs.docker.com/config/containers/container-networking/#dns-services
https://github.com/compose-spec/compose-spec/blob/master/spec.md#dns

Might save you some maintenance time? :)

**Comment by lloesche** [comment]
Good question. I believe I just copy'pasted it from one of my old images and that's how it sneaked in here. You're likely right, we should just remove them completely.

**Comment by sebbrandt87** [comment]
go ahead @lloesche 
both is valid ;)

**Comment by Toucan-Sam** [comment]
For what it's worth, I've been meaning to look at a PR for this. Just been a busy week. It's also not harmful so didn't feel like it was too much of a rush. :)

**Comment by lloesche** [comment]
DNS_1/2 have been removed from the container
