### ISSUE TITLE
Feature Request: Populating adminlist.txt with env vars

### ISSUE THREAD

**Issue by syntaxTerr0r** [lloesche/valheim-server-docker#257]
Is there any way to define the `adminlist.txt` easily?
Thanks!

**Comment by lloesche** [comment]
> Is there any way to define the adminlist.txt easily?

Implying opening a text file is not easy? 😹 Love it.
We can sure build something!

**Comment by lloesche** [comment]
There you go:

| Name | Default | Purpose |
|----------|----------|-------|
| `ADMINLIST_IDS` |  | Space separated list of admin SteamIDs. Overrides any existing adminlist.txt entries! |
| `BANNEDLIST_IDS` |  | Space separated list of banned SteamIDs. Overrides any existing bannedlist.txt entries! |

**Comment by syntaxTerr0r** [comment]
Thanks @lloesche!
