### ISSUE TITLE
Exit on host stop

### ISSUE THREAD

**Issue by fmdaboville** [lloesche/valheim-server-docker#261]
Hello,

I'm going to put this into a Digital Ocean droplet, very nice work, thanks a lot !
I have juste one question about the uptime of the container : should we stop it when no player is connected ? Or time is automatically stopping in game when there is no player ?
What about switching off the host machine directly in digital ocean, without stopping the container, is this can corupt saves or not ? What is the proper way to perform this ?

Thanks a lot :)

**Comment by InB4DevOps** [comment]
Time stops when no player is connected.

**Comment by lloesche** [comment]
I don't know about digital ocean, but if they run a regular `stop` on the container then the world is saved.
