### ISSUE TITLE
Updating on Synology

### ISSUE THREAD

**Issue by viab23** [lloesche/valheim-server-docker#262]
Sorry for the noob question. When I installed `latest` does this update automatically, or do I have to pull each time something is changed in the container (according to [this](https://github.com/lloesche/valheim-server-docker#updating-the-container-image-to-the-latest-version)). How can I see the version in Synology Docker?

Which string quoting for [discord notifications](https://github.com/lloesche/valheim-server-docker#notify-on-discord) is used in the Synology Env definition? Maybe add an example?

**Comment by lloesche** [comment]
See https://github.com/lloesche/valheim-server-docker#updating-the-container-image-to-the-latest-version

I don't know what quoting Synology uses, I'd try the env file one.

**Comment by viab23** [comment]
Thanks, the update worked.

Also the [env file](https://github.com/lloesche/valheim-server-docker#inside-an-env_file) format works
