### ISSUE TITLE
Fatal Error: Steamcmd needs 250MB of free disk space to update

### ISSUE THREAD

**Issue by MWestenberg** [lloesche/valheim-server-docker#263]
Appearently there is no space left in the steamcmd directory.

**Comment by lloesche** [comment]
How is that related to the container? Just give it more space?! 🤔

**Comment by MWestenberg** [comment]
Thank you for this quick response! Appreciate it! I gave the container 10GB so that cannot be the issue. When I check on the container I see 0 space free on /opt. Also I never got the server working with /opt/valheim mounted on my host. It tries to update steamcmd itself and that isn’t working somehow. Any ideas?

**Comment by lloesche** [comment]
Sounds either like a disk space or permission issue. The container itself has no disk-space like a VM would have. Whatever space is free on the host fs can be used by the container unless explicitly restricted. Can you paste your config?

**Comment by MWestenberg** [comment]
Im am using Docker desktop on a Macbook. So the global settings are set to use 60Gb as diskspace for all docker containers (only 1 available that is valheim) and 10Gb for memory. Config is simple:
{
  "features": {
    "buildkit": true
  },
  "experimental": false
}

**Comment by MWestenberg** [comment]
Ok i reinstalled the desktop version of Docker and adjusted the settings like above and started the server. Now it is working....I don't understand what happened here.
