### ISSUE TITLE
BepInEx Plugin

### ISSUE THREAD

**Issue by itsyoshio** [lloesche/valheim-server-docker#264]
Hi there, thanks for the Awesome Container.

I'd like to extend the Game with a [BepInEx Plugin](https://www.nexusmods.com/valheim/mods/274)
Is there currently any way i can add plugins?

I am using valheim-k8s.

Since `/data/valheim/valheim-plus` on my Host is mounted in the Container as `/opt/valheim/plus/BepInEx/config` i currently don't see a way to add anything to the `/opt/valheim/plus/BepInEx/plugins` Folder conveniently.

Any idea is greatly appreciated.

**Comment by lloesche** [comment]
Not sure I follow.

Why does mounting something to `/opt/valheim/plus/BepInEx/config` prevent you from also mounting a volume to `/opt/valheim/plus/BepInEx/plugins`?

Overall I would probably not mount any volumes to those directories and go with our standard scheme of only mounting `/opt/valheim` and `/config` and then use the `PRE_START_HOOK` and `PRE_RESTART_HOOK` to install your mods from a separate volume mount like `/mods` or something like that.

**Comment by lloesche** [comment]
@itsyoshio were you able to resolve your issue? I'll close this in a day or two if I don't hear anything.
