### ISSUE TITLE
Double timestamps in logs

### ISSUE THREAD

**Issue by silverwind** [lloesche/valheim-server-docker#265]
A recent update seems to have added duplicate timestamps to the container logs, I think https://github.com/lloesche/valheim-server-docker/pull/251:

```console
$ docker logs -f valheim
Mar 24 08:20:42 /supervisord: valheim-server 03/24/2021 08:20:42: Zonesystem Start 278
Mar 24 08:20:42 /supervisord: valheim-server 03/24/2021 08:20:42: DungeonDB Start 278
Mar 24 08:20:43 /supervisord: valheim-server 03/24/2021 08:20:43: Game server connected
```

I think one timestamp ought to be enough, maybe even zero because `docker logs` has a `-t` option to add timestamps itself.

**Comment by lloesche** [comment]
The update makes it so that all data is being logged via  a central syslog instance. All the components we have the source code for leave timestamp creation to syslog now. For Valheim server itself however we have no option of turning off their timestamps so you'll have them twice for now.
