### ISSUE TITLE
ValheimPlus config setting being ignored.

### ISSUE THREAD

**Issue by chdesigns** [lloesche/valheim-server-docker#270]
Since the lastest update, none of the + setting are being used. No matter what changes are done in valheim_plus.cfg I am not seeing the changes in the server. I have re-created new server/docker images and still having the same issues. Server did get updated to the lastest version yesterday.

Any thoughts?

root@docker-game:/home/valheim/valheim-server# cat docker-compose.yaml
version: "3"

services:
  valheim-pers:
    image: lloesche/valheim-server
    container_name: valheim-server-pers
    cap_add:
      - sys_nice
    volumes:
      - /home/valheim/valheim-server/config-pers:/config
      - /home/valheim/valheim-server/data-pers:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - /home/valheim/valheim-server/valheim-pers.env
    restart: always
    stop_grace_period: 2m

root@docker-game:/home/valheim/valheim-server# cat valheim-pers.env
SERVER_NAME="***********"
WORLD_NAME="FirstWorldPlus"
SERVER_PASS=*************
VALHEIM_PLUS="true"

**Comment by chdesigns** [comment]
Figure out the issue was caused by the client files needing to be updated. I re-installed the game and V+ client files and that allowed the setting to work.

**Comment by lloesche** [comment]
@chdesigns glad you were able to figure it out!
