### ISSUE TITLE
supervisor http is not working

### ISSUE THREAD

**Issue by findanish** [lloesche/valheim-server-docker#273]
Hi there!

I have this server running on a Synology docker container, everything works fine but I cant seem to get the supervisor page working. I have opened/mapped port 9001 on both synology and my router (points to synology ip) but it still comes up with "This page isnt working error). Not sure how to get this working. Your help is appreciated!

![image](https://user-images.githubusercontent.com/7362613/112537321-c7522a80-8d6b-11eb-80f9-0bda11353b48.png)

**Comment by lloesche** [comment]
Not related to the page loading or not, but your password is `admin` and your user is blanked out?

**Comment by lloesche** [comment]
@findanish were you able to figure it out?

**Comment by findanish** [comment]
@lloesche 
Hi there! Unfortunately i gave up. It never came up. I did change the user name & pass to something else eventually.
