### ISSUE TITLE
names not showing in status.json

### ISSUE THREAD

**Issue by Sloth-on-meth** [lloesche/valheim-server-docker#283]
Hi there! status.json is not showing any of the player's names.

**Comment by lloesche** [comment]
You mean it is behaving exactly as [described in the README](https://github.com/lloesche/valheim-server-docker#status-web-server) where it says
> All the information in `status.json` is fetched from Valheim servers public query port. You will notice that some of the fields like player name or player score currently contain no information. However for completeness the entire query response is left intact.
