### ISSUE TITLE
Warning: failed to set thread priority - with solution

### ISSUE THREAD

**Issue by finndo77** [lloesche/valheim-server-docker#284]
I understand it is a warning, and I understand the server still runs even with this, but since I found a solution, you may want to implement it.

[Reddit post with solution](https://www.reddit.com/r/valheim/comments/lstk71/valheim_dedicated_server_fix_for_failed_to_set/)

I have no idea how creating or modifying docker images works, nor any clue how to incorporate changes to such an image into github for this, so I cannot put a pull request in myself.  I'm sure it is a simple thing (I already use github regularly at work and have used it extensively in the past personally, but have not looked into how docker images work on github) but at this point have not looked into it.

thanks!

**Comment by lloesche** [comment]
So , the warning doesn't really matter unless running on a very CPU constrained system. But also you would only get that warning if you do not follow the README. Literally every example in there is adding cap_sys_nice which makes it so the server can renice it's packet processing thread to a negative value and will no longer print the warning. Re-read the [`Basic Docker Usage`](https://github.com/lloesche/valheim-server-docker#basic-docker-usage) chapter, apply what's written there and the warning will be gone.
