### ISSUE TITLE
Error permissions

### ISSUE THREAD

**Issue by pedroavaria** [lloesche/valheim-server-docker#289]
When i start the docker-compose, i have this error:

valheim_1  | Mar 29 20:32:13 /supervisord: valheim-updater Logged in OK
valheim_1  | Mar 29 20:32:13 /supervisord: valheim-updater Waiting for user info...
valheim_1  | Mar 29 20:32:38 /supervisord: valheim-updater /opt/steamcmd/steamcmd.sh: line 38:    76 Killed                  $DEBUGGER "$STEAMEXE" "$@"
valheim_1  | Mar 29 20:32:38 /supervisord: valheim-updater ERROR - Failed to download Valheim server from Steam - retrying later - check your networking and volume access permissions

anyone know how to fix it ?

My docker-compose yml

```markdown
version: "3"
services:
  valheim:
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m
```

regards.

**Comment by lloesche** [comment]
@pedroavaria the `Killed` in there means that Steam was killed by an external force. The only obvious thing that comes to mind is the Kernel's OOM killer. Make sure you have the resources provisioned described here: https://github.com/lloesche/valheim-server-docker#system-requirements
I.e. at least 4 GB of RAM.

**Comment by pedroavaria** [comment]
> @pedroavaria the `Killed` in there means that Steam was killed by an external force. The only obvious thing that comes to mind is the Kernel's OOM killer. Make sure you have the resources provisioned described here: https://github.com/lloesche/valheim-server-docker#system-requirements
> I.e. at least 4 GB of RAM.

Thanks.
