### ISSUE TITLE
Suggestion - Multiple worlds, one setup

### ISSUE THREAD

**Issue by axelra82** [lloesche/valheim-server-docker#295]
First of 💯 👌  Great way to host a server for friends that you can join (when you have 10 spare minutes haha 😂)

I was looking to setup something similar myself, but seeing as my docker knowledge is novice and I just started reading up on it a couple of weeks ago I started looking for guids and found this!

A suggestion is that it would be really nice if we could add multiple worlds in one setup 😄

According to [this reddit post](https://www.reddit.com/r/valheim/comments/lioadq/how_to_multiple_dedicated_servers_on_one_machine/) it should be doable 🤔

Just to test it out (running two worlds on one machine) I cloned this repo and changed the `image` to use `build context` instead, i.e. from:
```
 image: lloesche/valheim-server
```
to
```
  build:
    context: ./docker-server
```

and pointed it to the repo, in the compose file. In the repo `Dockerfile` I change the expose ports to `2459-2461/upd` and `9002/tcp`. In the `docker-compose.yaml`
```
  ports: 
    - 2459-2461:2459-2461/udp
    - 9002:9002/tcp
```

**Worked like a charm!** 👍 

I do however believe that this proves my previous statement about me not being to well versed in Docker 😂  I'm sure some sort of array, comma seperated values etc could be used in the env file and simply loop that when building the container for a more stable and maintainable solution.

For per world port config I would suggest something in the line of:
- supply custom range (per world)
- increment UDP by 3 and TCP by 1

Or maybe there is some better way? 🤷‍♂️ 

Really great job! Let me know if this suggestion gets implemented and you want help testing/developing (to the extent I can help) 😄 

## EDIT

Almost forgot to add this... I also had to go in to the file `/usr/local/bin/valheim-server` (in the container) and change the port to `2459` in the `LD_PRELOAD` for this to work. This in turn means installing a text editor... I used `apt-get update && apt-get install vim`. **Which I realised I could just as easily edit** in the file `valheim-server` from the repo before starting the container.  Yea, again, not the smoothest solution, but it workes for now 🤓

**Comment by lloesche** [comment]
I don't really understand what problem you're trying to solve?!
If you e.g. want to run 10 worlds in parallel, why not just start the container 10 times, mapping 10 different port ranges? Provided your server has enough resources this would work and has been done.

**Comment by axelra82** [comment]
@lloesche you are absolutely right... It went completely over my head that I can just redeffine the ports (which I knew) 😂 

I made something, very simple, overly complicated... I wouldn't mind if you deleted this "non-issue" 😄 I think I'm just a little bit overworked and not thinkning straight.

**Comment by wcdanh2** [comment]
> `docker run -d --name valheim-server2 --cap-add=sys_nice --stop-timeout 120 -p 2466-2467:2456-2457/udp -v $HOME/valheim-server2/config:/config -v $HOME/valheim-server2/data:/opt/valheim -e SERVER_NAME="My 2nd server" -e WORLD_NAME="World2" -e SERVER_PASS="secret" lloesche/valheim-server `

Using the docker port mapping to change the ports instead of using the SERVER_PORT environment variable appears to cause the server to not be able to be listed in the community list (at least when you have multiple servers).  

>  -p 2466-2467:2456-2457/udp

When the ports are redirected in this way the server status info will still return that the connect port is the default 2456.  By changing the server port on my second instance and setting the docker ports to be a direct pass through instead of a remap my second server is able to be seen in the server list.

Hopefully this info might be helpful to someone since this took me a while to figure out why my second instance was not showing up in the community list.
