### ISSUE TITLE
BepInEx Mod fails to load with "Failed to extract and install BepInEx - retrying later"

### ISSUE THREAD

**Issue by vogeldm** [lloesche/valheim-server-docker#299]
Attempting to setup a new server. Kept docker config to bare minimum, server fails to load with "Failed to extract and install BepInEx - retrying later"

[_valheim-server_logs.txt](https://github.com/lloesche/valheim-server-docker/files/6253122/_valheim-server_logs.txt)

**Comment by lloesche** [comment]
@vogeldm thank you for your report! From the log it looks like it is failing somewhere in these lines:
https://github.com/lloesche/valheim-server-docker/blob/7e0da99e1d2e77916cffbe5ce9df34a95bc93c37/common#L411-L420

Most likely in `ensure_permissions()`.

I updated the container with more debug log and also made config permission change errors non-critical. Can you pull the latest version of the container and see if it makes a difference? If not please attach a new log with the added debug output.

**Comment by vogeldm** [comment]
Seems like the changes corrected the issue. I've included the logs for reference.
[_valheim-server_logs.txt](https://github.com/lloesche/valheim-server-docker/files/6259676/_valheim-server_logs.txt)
