### ISSUE TITLE
sharing k8s config

### ISSUE THREAD

**Issue by Addyvan** [lloesche/valheim-server-docker#30]
I made a basic kubernetes config using this docker setup: https://github.com/Addyvan/valheim-k8s

It's currently working great on my homelab!

The setup is currently somewhat specific to my hardware / homelab but could easily be templated to fit with various cluster environments. 

I figured I'd reach out and ask if you'd like the repo added to the README as deploying the container to kubernetes adds a later of persistence / safety.

**Comment by lloesche** [comment]
Hey @Addyvan that's really cool! I was thinking about adding K8S deployments and config maps.

I can add a link to the README or if you like you can submit a PR and add the code right to this repo. I can give you committer access so you can update at will. Then we would maintain everything in one place/repo. Let me know what you prefer.
We could add the helm chart and yaml files to a `k8s/` subdirectory and put an entire K8S related section in the README.

**Comment by lloesche** [comment]
I linked to your repo in https://github.com/lloesche/valheim-server-docker/commit/8eaf7b69a186afcfa371e33a782e02eb23a7db8a but the offer stands if you would like to have committer access to move everything into this project I'm happy to provide that.

**Comment by Addyvan** [comment]
Hi @lloesche thanks for getting back so quickly!

Since there seems to be more interest then I expected, I'd like to play around with the releases and expose the chart via gh-pages (so you can run `helm repo add ...`). Because of this it makes more sense to separate the repos for now IMO. Otherwise I believe would need elevated priviledges. 

What I'm thinking is that I set everything up devops wise then next week we could rehash this convo and consider a PR into `valheim-server-docker` with static manifests, a chart, and a proper release mechanism. This way the PR could also include some steps for you to follow in the GUI.

**Comment by Addyvan** [comment]
Sidenote: The basic kubernetes config I orgininally pushed up has been working for me and my buddies for a week now with no issues! Thanks for putting this together :)

OK, I went ahead and improved upon the basic hello world setup. 

I think it's best that we maintain separate repos since the CI/CD for the helm chart was a real pain to get going. That being said if you are ok using `hostVol` for persistence, running on k8s should now be as simple as: 

```bash
helm repo add valheim-k8s https://addyvan.github.io/valheim-k8s/
helm repo update
helm install valheim-server valheim-k8s/valheim-k8s  \
  --set worldName=example-world-name \
  --set serverName=example-server-name \
  --set password=password \
  --set storage.kind=hostvol \
  --set storage.hostvol.path=/data/valheim
```

This config is tied directly to this project so I'll have to keep tabs with it in case of any substancial changes that would require kubernetes updates.

**Comment by lloesche** [comment]
@Addyvan this is great work ! I always try my best to not do any breaking changes and make every new function backwards compatible to the way it worked before. I've invited you as a collaborator to this repo. Feel free to update the README on your own as you see fit. For any changes that change code/image functionality please use PRs.

**Comment by Addyvan** [comment]
@lloesche Awesome thanks. Will close this issue now.
