### ISSUE TITLE
ValheimPlus not working on Synology 

### ISSUE THREAD

**Issue by Fabninja** [lloesche/valheim-server-docker#307]
I tried adding the VALHEIM_PLUS=true variable to my container, but it just seems to ignore it.  I've attached my log file.

[ValheimLog.xls](https://github.com/lloesche/valheim-server-docker/files/6286535/ValheimLog.xls)

**Comment by Fabninja** [comment]
I figured it out. Forgot to hit clear after updating to the latest image

**Comment by lloesche** [comment]
@Fabninja glad you were able to figure it out! If you were updating from a very old version of the container there's also a couple of deprecated settings that you might still be using. Specifically `UPDATE_INTERVAL` and `BACKUPS_INTERVAL`.
They still work but you're missing out on a couple of new functions (like the container only running updates when there are no players connected). If you are still using either of those two you should remove them and replace with their new `UPDATE_CRON` and `BACKUPS_CRON` equivalents. If you haven't set them everything is fine and the new defaults will be used automatically.
