### ISSUE TITLE
Server only discoverable on port 2457

### ISSUE THREAD

**Issue by nminchow** [lloesche/valheim-server-docker#31]
When I rely on the default env var (or manually supply `SERVER_PORT: 2456`), the server seems to only be discoverable on steam at port 2457. My server isn't showing up in the server lists either, and I suspect the issues are related. This may not be a problem with this image, but I had noticed other users experiencing the same issue:

https://github.com/lloesche/valheim-server-docker/issues/26#issuecomment-779185280

**Comment by InB4DevOps** [comment]
The server will listen on SERVER_PORT + 1

The server not showing up in the server list is not related to the port.

**Comment by nminchow** [comment]
> The server will listen on SERVER_PORT + 1

Is this just a quirk of the executable? I spent nearly 2 hours trying to debug why I couldn't connect while specifying an IP.
