### ISSUE TITLE
PRE_RESTART_HOOK is not called during daily restarts

### ISSUE THREAD

**Issue by Outshynd** [lloesche/valheim-server-docker#310]
I am running the latest version of the container, pulled 2021/04/09, and have ENV set for **PRE_RESTART_HOOK**, **PRE_SERVER_SHUTDOWN_HOOK**, **POST_START_HOOK**, and **POST_SERVER_LISTENING_HOOK**.  I have the default server restart at 05:00:00 enabled, TZ set correctly, and my server DOES restart every day at 5am.  However, when restarting, it sends a Discord message based on my **PRE_SERVER_SHUTDOWN_HOOK** event, same as if I manually stop the server or restart the container.

```Apr 10 05:00:00 crond[25]: USER root pid 15423 cmd [ -f "/var/run/valheim-backup.pid" ] && kill -HUP $(cat /var/run/valheim-backup.pid)
Apr 10 05:00:00 crond[25]: USER root pid 15424 cmd [ -f "/var/run/valheim-updater.pid" ] && kill -HUP $(cat /var/run/valheim-updater.pid)
Apr 10 05:00:00 crond[25]: USER root pid 15425 cmd /usr/local/bin/valheim-is-idle && /usr/local/bin/supervisorctl restart valheim-server
2021-04-10 05:00:00,925 INFO waiting for valheim-server to stop
Apr 10 05:00:00 /supervisord: valheim-server DEBUG - [127] - Received signal to shut down valheim-server
Apr 10 05:00:00 /supervisord: valheim-server INFO - Running pre server shutdown hook: curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim Server\",\"content\":\"$DISCORD_PRE_SHUTDOWN_MESSAGE\"}" "https://discord.com/api/webhooks/..." && sleep 60
2021-04-10 05:00:02,925 INFO waiting for valheim-server to stop
2021-04-10 05:00:04,925 INFO waiting for valheim-server to stop
2021-04-10 05:00:06,925 INFO waiting for valheim-server to stop
```

&nbsp;

Is this this the correct behavior?  I had assumed that the daily restarts would trigger the restart event, not a shutdown event.  I have not yet had the server update and restart (due to not having run the server for very long) so I cannot confirm if the restart event is triggered by an update, though I would assume it would be.

Let me know if there's any other information I can provide, or if my assumptions are incorrect.

**Comment by lloesche** [comment]
https://github.com/lloesche/valheim-server-docker#event-hooks lists all the exact conditions under which individual hooks are called.

For `PRE_RESTART_HOOK` it is
```
Command to be executed before a server restart is performed by the valheim-updater.
```
I.e. whenever `valheim-updater` finds a new update of Valheim server or any mod and needs to restart the server this hook is called. If the server is not currently running (i.e. on container start) `PRE_START_HOOK` is called instead.

All the `PRE/POST_SERVER_*` hooks are called whenever the Valheim server process is being started or stopped.
