### ISSUE TITLE
Docker container disappears randomly

### ISSUE THREAD

**Issue by longdiddy** [lloesche/valheim-server-docker#315]
Hello,

Installed the docker container on my Synology DS 1520+. Runs great but the docker container randomly disappears/deletes itself overnight or randomly... I don't really know when it happens. The Docker logs don't show anything. Anybody else experience this issue and what is the fix?

**Comment by lloesche** [comment]
Does it happen with all Docker containers? I'm afraid the Synology forums are a better source for information than this container repo. I would actually ask Synology support for assistance. Pretty sure Docker is an official Synology feature.

**Comment by longdiddy** [comment]
> Does it happen with all Docker containers? I'm afraid the Synology forums are a better source for information than this container repo. I would actually ask Synology support for assistance. Pretty sure Docker is an official Synology feature.

No, it does not happen with all containers just the valheim server container.

**Comment by viab23** [comment]
As a sidenote, I had the valheim server container running for several weeks without issues on my Synology DS 218+. Have you tried updating the docker engine/ setting up the container from start/restart the NAS?
