### ISSUE TITLE
Exec user process caused: exec format error on Raspberry PI 4

### ISSUE THREAD

**Issue by SebastianLeborg** [lloesche/valheim-server-docker#317]
Hello,

I'm trying to run valheim-server on a Raspberry Pi 4. I have installed Ubuntu server 64bit on my PI, installed docker, copied over the world and made sure the paths are correct. However, when attempting to launch the docker container, it immediately exits with very little debug information.

![img](https://user-images.githubusercontent.com/8777642/114866459-e173ab80-9df3-11eb-8b9c-bfe11beeafb2.jpg)

What's going on here? Are there some more detailed logs I can check out to figure out what's going on here?

**Comment by InB4DevOps** [comment]
The explanation is right there: Valheim server is amd64, your host OS is arm64. 
As long as there is no arm64 server you will have a hard time getting it to work on your Pi.

**Comment by SebastianLeborg** [comment]
> The explanation is right there: Valheim server is amd64, your host OS is arm64.
> As long as there is no arm64 server you will have a hard time getting it to work on your Pi.

Hmm, that's too bad. Is this related to the CPU architecture or is it related to the OS? I've heard that Windows has a translation layer that can interpret ARM to x86 instructions. Is there any way to do this on a Linux distro?

**Comment by Outshynd** [comment]
Both MacOS and Windows for ARM have a fledgling translation layer that can SORTA run x86/64 instructions on ARM-based processors (and Apple is really pushing their M1 so theirs will continue to get better), but as far as I am aware there is no such thing for RPi and, even if there was, the performance hit for emulating x86/64 commands would be too great to sufficiently run a Valheim server.

I'm sorry to say that you're not going to find a workaround to run it on a RPi.  It's **possible** that the source code for the Valheim server would be released at some point in the future at which point it's **possible** it will be compiled for ARM and then something like an RPi **might** be able to handle a low-slot server, but even then I think you would run into performance issues.

Best of luck!
