### ISSUE TITLE
"Backups if idle" and "disableServerPassword" flags getting ignored in env file

### ISSUE THREAD

**Issue by SecretUnicorn** [lloesche/valheim-server-docker#320]
I'm using docker compose to run the server and this is my .env file

```
SERVER_NAME=AstroidField
WORLD_NAME=Ganymede
SERVER_PASS=ofc_I_blur_this_:)
SERVER_PUBLIC=false
VALHEIM_PLUS=true
STATUS_HTTP=true
STATUS_HTTP_PORT=81
VPCFG_Server_dataRate=500
VPCFG_Server_disableServerPassword=true
BACKUPS_IF_IDLE=false
BACKUPS_CRON=*/10 * * * *
```

The cron job works because I now have 10 minute intervalled backups but sadly even when nobody is connected which is not what I desire. In addition to that the option to disable the server password seems to be not working either. I set it in the valheim_plus.cfg in addition to the env file but a password is still necessary. I tried removing the password from the env file but that did not work either.

Help would be much appreciated ;)

Thanks for the docker image tho!

**Comment by lloesche** [comment]
Read https://github.com/lloesche/valheim-server-docker#backups specifically `BACKUPS_IDLE_GRACE_PERIOD`
as well as https://github.com/lloesche/valheim-server-docker#disable-server-password
specifically `set an empty password (SERVER_PASS="")`.
