### ISSUE TITLE
Steamcmd needs to be online to update

### ISSUE THREAD

**Issue by atripes** [lloesche/valheim-server-docker#321]
Hi,

and congrats for that great project!

I am having trouble with SteamCMD at setup. 
docker-compose deployment method logs read: 

```
valheim_1  | Apr 17 18:30:21 /supervisord: valheim-updater [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
valheim_1  | Apr 17 18:30:21 crash_20210417183021_7.dmp[185]: Uploading dump (out-of-process) /tmp/dumps/crash_20210417183021_7.dmp
valheim_1  | Apr 17 18:30:21 /supervisord: valheim-updater src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56db08f0/0x0xf772db'
valheim_1  | Apr 17 18:30:21 /supervisord: valheim-updater ERROR - Failed to download Valheim server from Steam - retrying later - check your networking and volume access permissions
```

I made sure to open all ports in ufw (2456:2457/tcp and 9001/tcp).
I am not exactly sure how to tackle the problem, can I provide some more information to make debugging easier?

Thanks for any help.
Cheers,

Alex

**Comment by lloesche** [comment]
This error is not about incoming ports. The container needs to be able to communicate with the Steam update servers. I.e. you have to allow any connections from the container to the Internet.

**Comment by atripes** [comment]
Thank you, the container indeed does not have an internet connection.
I solved it by editing the docker-compose file and adding
```
network_mode: host
```
Plus removing all port bindings.

It feels like there might be a more elegant solution. How do you go about this? 
Thanks again for the quick response and the help.

**Comment by lloesche** [comment]
The default is `bridge` networking. If it doesn't work out of the box and if only `host` networking works for you then the hosts Docker networking setup is broken in some way. See https://docs.docker.com/network/bridge/
