### ISSUE TITLE
Valheim Plus often not loaded

### ISSUE THREAD

**Issue by GimpArm** [lloesche/valheim-server-docker#328]
I have Valheim Plus enabled via "VALHEIM_PLUS=true" and often after a restart of the container it doesn't allow connections. There is a log entry:

Apr 25 15:49:26 /supervisord: valheim-server [Info   :Valheim Plus] Configuration file loaded succesfully.
Apr 25 15:49:27 /supervisord: valheim-server [Info   :Valheim Plus] ValheimPlus [0.9.7] is up to date.

But then when trying to connect:

Apr 25 15:49:59 /supervisord: valheim-server 04/25/2021 15:49:59: VERSION check their:0.150.3@0.9.7  mine:0.150.3

Here is the full log.

[_valheim_logs.txt](https://github.com/lloesche/valheim-server-docker/files/6372086/_valheim_logs.txt)

**Comment by lloesche** [comment]
Can you attach the full log? From container start to issue.

**Comment by GimpArm** [comment]
Here is the full log from starting the container to trying to connect.

[log.txt](https://github.com/lloesche/valheim-server-docker/files/6376633/log.txt)

**Comment by lloesche** [comment]
V+ is loaded, but you have set `enforceMod = false` which removes V+ from the version string and makes it incompatible with a client that has V+.

**Comment by GimpArm** [comment]
Ok, I thought enforceMod meant that it forces the client to have the mod and it was more of an optional thing. You should update your documentation because I just copied the example which shows enabled set to true but enforceMod as false:

```
[Server]
enabled=true
enforceMod=false
dataRate=500
```

**Comment by lloesche** [comment]
Good idea. Why don't you submit a PR with the documentation updated the way you think it makes most sense for newcomers?
