### ISSUE TITLE
Unable to load F5 menu

### ISSUE THREAD

**Issue by mixm1xmix** [lloesche/valheim-server-docker#334]
I have added my steam ID to the admin list (verified it was the correct one from another discussion here), but I cannot seem to get F5 to do anything. I can do so in single player, but not on the dedicated server I am running. I've tried the ADMINLIST_IDS argument as well, no dice. Is SERVER_ARGS needed to pass the -console that is set when running the game from steam? Unsure how to proceed.

_Originally posted by @mixm1xmix in https://github.com/lloesche/valheim-server-docker/discussions/331_

**Comment by mixm1xmix** [comment]
any idea where I'd even start to troubleshoot this?

**Comment by lloesche** [comment]
I started with Google "valheim admin console not working" and literally the first hit told me what to do
![image](https://user-images.githubusercontent.com/2124094/116673647-f465ae80-a9a3-11eb-8717-18122cd6d695.png)

I'm updating the README with the info.

**Comment by Danpiel** [comment]
Same for me, done everything is stated in readmes and still no console available in dedicated server. On local works fine.

**Comment by lloesche** [comment]
No idea, but it is nothing that the container is doing. I'm running my local vanilla client with `-console` and no modifications or extra arguments on the server and when connected to the server the console opens normal pressing ***F5***
![image](https://user-images.githubusercontent.com/2124094/116780665-60b4e080-aa7e-11eb-86e2-baee861124cd.png)

Also adding the ID to adminlist.txt has no effect on whether your client opens a console or not. I can open a console on any server. If your ID isn't added to adminlist.txt you just can't use admin commands like kick and ban. But the console will always open, independent of the server settings.

**Comment by mixm1xmix** [comment]
Thanks for clarifying. No idea why this is happening, F5 seems to otherwise respond fine across all applications (and indeed single player).

**Comment by MapleBZH** [comment]
Hi,
for information, adding `-console` in steam launcher (properties) solve the issue for me
