### ISSUE TITLE
5am restart cron Job doesn't seem to trigger POST_START_HOOK

### ISSUE THREAD

**Issue by Mist-Hunter** [lloesche/valheim-server-docker#336]
This cron job: 
0 5 * * * /usr/local/bin/valheim-is-idle && /usr/local/bin/supervisorctl restart valheim-server

properly triggers the POST_SERVER_SHUTDOWN_HOOK, which sends a corresponding Discord message to my server users, but it doesn't seem to trigger the POST_START_HOOK alerting said users to the fact the server is back up (which it is).

Maybe I'm using the wrong HOOK(s) or misunderstanding, but thought I'd post it here in case this isn't the intended behavior.

**Comment by Mist-Hunter** [comment]
Nevermind, I just noticed this POST_RESTART_HOOK, I will try that and reopen if I have a problem. Thanks for the great container!

**Comment by lloesche** [comment]
I recommend reading the description of each hook in https://github.com/lloesche/valheim-server-docker#event-hooks
They explain in detail under which conditions which hook is triggered.
For the 5am restart (or any server start for that matter) the `PRE/POST_SERVER_RUN_HOOK` might be interesting.
