### ISSUE TITLE
VALHEIM_PLUS not being passed from .env file

### ISSUE THREAD

**Issue by BackedUpBooty** [lloesche/valheim-server-docker#345]
Loving your work on this, my friends and I can't thank you enough. 

This is more of a 'worked but didn't' issue. We decided to try Valheim Plus, going through your docs I first tried to pass it to the container through the valheim.env file (VALHEIM_PLUS=true) as your notes seem to indicate that's possible. Although the server spun up and could be accessed with vanilla valheim client, I couldn't get it to recognise the variable (new image pull and docker-compose down && up [sic] among other things).

As soon as I add the `environment: VALHEIM_PLUS=true` into the .yaml, it worked. Not sure exactly what I did wrong, thought I'd followed instructions pretty well, maybe not though, so again this is more of an FYI for my experience.

Thanks again!

**Comment by lloesche** [comment]
If that's the case it's more of a Docker issue not an issue we can solve in this container.

That said I just tested on my system and it passes just fine:

```
lukas@macromi:~$ cat /home/lukas/valheim/valheim.env
SERVER_NAME=My Docker based server
SUPERVISOR_HTTP=true
SUPERVISOR_HTTP_PASS=letmein
STATUS_HTTP=true
VALHEIM_PLUS=true

lukas@macromi:~$ docker exec -it valheim-server env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=0ac8ec29bd21
TERM=xterm
SERVER_NAME=My Docker based server
SUPERVISOR_HTTP=true
SUPERVISOR_HTTP_PASS=letmein
STATUS_HTTP=true
VALHEIM_PLUS=true
DEBIAN_FRONTEND=noninteractive
HOME=/root
```

Not sure what else to test.

**Comment by BackedUpBooty** [comment]
Thanks for taking a look, I tried the .env again yesterday and it loaded up vanilla, wondering what's going on in my system that it doesn't even seem to see it. Ah well, like I said I've got it working through the yaml so no worries.
