### ISSUE TITLE
Can't change STATUS_HTTP_PORT 

### ISSUE THREAD

**Issue by kiwisaurio** [lloesche/valheim-server-docker#348]
Hi,

I'm trying to change the STATUS_HTTP_PORT from 80 to 8091 since I'm about to run a nginx reverse proxy on the same docker server, running on port 80, but everytime I try to change it, stays running on port 80. 

My docker container run command is: 
docker run -d     --name valheim-server     --cap-add=sys_nice     --stop-timeout 120     -p 2456-2457:2456-2457/udp -v $HOME/valheim-server/config:/config     -v $HOME/valheim-server/data:/opt/valheim     -e SERVER_NAME="///"     -e WORLD_NAME="///"     -e SERVER_PASS="///"  -e UPDATE_IF_IDLE="true" -e UPDATE_CRON="*/15 * * * *" -e SERVER_PUBLIC="true" -e STATUS_HTTP="false" -e STATUS_HTTP_PORT=8091   lloesche/valheim-server

After running that command, I run docker ps and prompts this output:
![image](https://user-images.githubusercontent.com/34544227/118659579-bcf16180-b7ed-11eb-9c3f-a66667b0c823.png)

I hide the server properties for security reasons. 

Any help on this? Am I doing something wrong?

**Comment by lloesche** [comment]
Your `docker run` command does not match what your `docker ps` output is showing. `STATUS_HTTP_PORT` changes the HTTP port inside the container. There's rarely any reason to do so. What you want to do is change your `docker run` command to port map the status http on a different host port. Right now your docker run must have something like `-p 80:80`. Which you could change to `-p 8091:80` to change the host port from 80 to 8091.

**Comment by kiwisaurio** [comment]
> Your `docker run` command does not match what your `docker ps` output is showing. `STATUS_HTTP_PORT` changes the HTTP port inside the container. There's rarely any reason to do so. What you want to do is change your `docker run` command to port map the status http on a different host port. Right now your docker run must have something like `-p 80:80`. Which you could change to `-p 8091:80` to change the host port from 80 to 8091.

I'm kinda new to docker but I found the solution on this answer on stackoverflow https://stackoverflow.com/a/38783433.
After changing it, worked like a charm. 

Btw thank you for your response and thank you for this amazing project, my friends love it!
