### ISSUE TITLE
Add possibility to store non-zip Backups

### ISSUE THREAD

**Issue by TheHades** [lloesche/valheim-server-docker#349]
I'm using [borgbackup](https://borgbackup.readthedocs.io/en/stable/) for creating backup, because it supports deduplication and compression.

How about adding an boolean option called "BACKUPS_ZIP" or "BACKUPS_COMPRESS" ?
If yes, then zip backups.
If false, then store "raw" backups of the worlds.

**Comment by lloesche** [comment]
Any solution will have to be backwards compatible. Esp. take `PRE_BACKUP_HOOK` and `POST_BACKUP_HOOK` into consideration which replace the `@BACKUP_FILE@` string in the executed hook command.

What should a "raw" backup of the worlds look like? Just a copy of the worlds directory with a timestamp in the name?

**Comment by TheHades** [comment]
> What should a "raw" backup of the worlds look like? Just a copy of the worlds directory with a timestamp in the name?

Yes, that should be sufficient.

I did a quick test with borgbackup (https://borgbackup.readthedocs.io/en/stable/index.html).

/tmp_valheim/backups = Contains unzipped Backups 
/tmp_borg = Borg Repository

Size of all unzipped Backups (25 backups * 60MB of Data * 2 (.db and .db.old file) = ~3GB)
```
root@server1 ~ # du -sh /tmp_valheim/
3.0G	/tmp_valheim/
```

```
# ls -al /tmp_valheim/backups/worlds-20210606-081010/worlds/
[...]
-rw-r--r-- 1 root root 61928780 Jun  6 10:01 'myworld.db'
-rw-r--r-- 1 root root 61928780 Jun  6 09:41 'myworld.db.old'
-rw-r--r-- 1 root root       49 Jun  6 10:01 'myworld.fwl'
-rw-r--r-- 1 root root       49 Jun  6 09:41 'myworld.fwl.old'
```

Now if we run a borgbackup on our "raw" backups, borg will compress those files AND it will detect duplicate blocks as well.

```
# borg info /tmp_borg/
Repository ID: f701065f547041e9ddfce587680f5ca86e1a592da93f7fb17ec0ccca1d0139cb
Location: /tmp_borg
Encrypted: No
Cache: /root/.cache/borg/f701065f547041e9ddfce587680f5ca86e1a592da93f7fb17ec0ccca1d0139cb
Security dir: /root/.config/borg/security/f701065f547041e9ddfce587680f5ca86e1a592da93f7fb17ec0ccca1d0139cb
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                3.13 GB              1.24 GB             63.59 MB

                       Unique chunks         Total chunks
Chunk index:                      43                  967
```

More Info: https://borgbackup.readthedocs.io/en/stable/usage/info.html#description

```
All archives / deduplicated size = amount of data stored in the repo = all chunks in the repository.
```

I will try to provide a PR within the next few days.

**Comment by ibex-are-goats** [comment]
Excellent feature request because Synology NAS have slow CPUs that get bogged down by zipping!

I would backup only the .old files, because they're very close to the files they're next to, so backing up both repeatedly will be redundant :)
