### ISSUE TITLE
AWS CDK Template to deploy via ECS Fargate

### ISSUE THREAD

**Issue by rileydakota** [lloesche/valheim-server-docker#35]
I have thrown together a CDK template that deploys and runs this using ECS Fargate on AWS. I saw the post about the K8s config - any interest in sharing this as well on the readme for AWS users?

**Comment by rileydakota** [comment]
For reference - code here (needs a good bit of templating/cleanup and documentation) https://github.com/rileydakota/valheim-ecs-fargate-cdk

**Comment by lloesche** [comment]
Hi @rileydakota, this is great work! I've linked to your repo in https://github.com/lloesche/valheim-server-docker/commit/8eaf7b69a186afcfa371e33a782e02eb23a7db8a and I'm making you the same offer I made @Addyvan. If you like you can have committer access to this repo and add your sources here directly. Whichever you prefer.

**Comment by rileydakota** [comment]
I think ill follow suit with @Addyvan and ask for committer access to update the readme - given that my code is for a specific type of deployment (AWS ECS) and that people may want to deploy to different things (K8s, Azure, GCP, Other AWS methods etc) it makes sense to just collect them in the readme and reference them with basic instructions :). Will submit a PR for the readme when you grant it!

**Comment by gotodeploy** [comment]
Yet another cdk construct built with [projen](https://github.com/projen/projen) here: https://github.com/gotodeploy/cdk-valheim

**Comment by rileydakota** [comment]
Hi @gotodeploy - nice work! We should consider collaborating on the template/construct. Looks like yours could extend mine with EFS Backups and a configurable play schedule to save money (very nice btw), and mine could extend yours with secrets injection into the container to eliminate the server password in the source code?

**Comment by gotodeploy** [comment]
@rileydakota I'd appreciate if we could collaborate with our work like sharing ideas, PRs and reviewing code. 😉

**Comment by rileydakota** [comment]
README looks good - closing
