### ISSUE TITLE
env vars table markup problem on dockerhub

### ISSUE THREAD

**Issue by mr-gosh** [lloesche/valheim-server-docker#353]
the markdown used in the env table (and a few others) doesn't render in [dockerub](https://hub.docker.com/r/lloesche/valheim-server#legal-disclaimer)
perhaps ot os possible do add some breaks to make it render?

**Comment by lloesche** [comment]
Fixed in https://github.com/lloesche/valheim-server-docker/commit/774fa61119242111c41da3006506519a9845b634
