### ISSUE TITLE
Bootstrap cannot set uid for `valheim-server` user 

### ISSUE THREAD

**Issue by Richardyang510** [lloesche/valheim-server-docker#355]
I think the bootstrap script is failing to set the uid for the `valheim-server` user since bootstrap is run as `valheim-server` itself. 

First, I set the following env vars:
```
PUID=1001
PGID=1001
```

Then, when I check the logs, I see:
```
INFO - Setting uid:gid of valheim-server to 1001:1001
usermod: user valheim-server is currently used by process 1
```

Exec-ing into the container and double checking the uid reveals it is still 0:
```
$ id -u valheim-server
0
```

I see that in the dockerfile, useradd is run with `PUID` and `PGID` vars, but then since I'm pulling the container from dockerhub, it would have been built with the defaults of 0:0.

Perhaps bootstrap can be run as root? Then usermod can change the uid.

**Comment by lloesche** [comment]
@Richardyang510 thank you for the report. This should be fixed now. It was caused by usermod wrongly assuming that the valheim-server user was in use when really bootstrap is being started as root. But because both had the same UID it couldn't distinguish.
