### ISSUE TITLE
valheim supervisor w/o password?

### ISSUE THREAD

**Issue by JakeDEvans** [lloesche/valheim-server-docker#357]
trying to run valheim with 802.1x authentication for supervisor (via nginx).

can I disable auth? I can't seem to get the workaround working - https://serverfault.com/questions/230749/how-to-use-nginx-to-proxy-to-a-host-requiring-authentication 

Thanks, awesome job on this

**Comment by lloesche** [comment]
In the latest version the default is to turn off auth if either `SUPERVISOR_HTTP_USER` or `SUPERVISOR_HTTP_PASS` are empty or not set.
