### ISSUE TITLE
Autodelete Discord BoT Messages

### ISSUE THREAD

**Issue by capo42** [lloesche/valheim-server-docker#358]
Hey

Is it possible to have an option to autodelete the messages from the Discord bot after a defined time?
Noone cares 2h later after the bot informed on Discord that the server got restarted.

Regards
Capo

**Comment by lloesche** [comment]
There is no Discord bot built into this container. All it can do is run commands when things happen. I'm guessing you implemented one of those hook examples to run `curl` against the Discord Webhook API to send messages to a server. You could use the same mechanism to run a tool that sends the message, waits for a while and then deletes the message 2h later. See https://discord.com/developers/docs/resources/webhook#delete-webhook-message

**Comment by capo42** [comment]
Thanks for the reply.
I could realy do it with the default Docker API. Thing is, i need to build a trigger to delete a message.
I think i will figure it out. Thanks anyway!

**Comment by lloesche** [comment]
@capo42 so what I would do is build a shellscript that you volume mount into the container. In that script you curl the Discord webhook to send a message, storing the returned message id. And then you background a subshell that waits 2h and then call the Discord webhook again to delete the previous message.

**Comment by capo42** [comment]
Sounds like a working idea.
Anyway an additional volume for such "cron'ed sideskripts" could be helpfull for serval things. It would open lots of opportunities. Also to tidy the the Valheim volume itself.
