### ISSUE TITLE
boolean environment variables 

### ISSUE THREAD

**Issue by axenic** [lloesche/valheim-server-docker#361]
You could say this is an Azure issue, perhaps.  When environment variable "Backups" environment variable is set to "true" in the azure container template, it  gets set as "True", in the linux container.   I suspect that true != True, as valheim backups are turned off.   

Possible fix would for the valheim scripts to handle all forms of "true".

Note: it's likely more than just environment variable "Backups", but that is were I saw it.   Sorry, I don't have a screenshot of the error output stating Backups is turned off since Backups=True (or something like that).   The workaround was to just not set the variable, since the default value is "true".

**Comment by lloesche** [comment]
Sounds odd and I couldn't find any documentation on this behavior. I know we have a bunch of Azure users and I'd be surprised if they hadn't run into this until now. Can you or somebody else verify this again?

Thing is, environment variables know nothing about Booleans. All env var values are case sensitive strings. I'd be very surprised if Azure was messing with that as it would break so many use cases. Just think of passing e.g. a DB password as an environment variable to a container. If they were capitalizing the first letter of every password it would break things left and right.
Anything is possible though I suppose.

**Comment by axenic** [comment]
No problem -- here is what I am observing:
![image](https://user-images.githubusercontent.com/1516498/120654097-f8736900-c446-11eb-9f43-99d28cae9f68.png)

My azure container template contains this:

    - name: BACKUPS
        value: true

**Comment by axenic** [comment]
I was able to fix this in the azure template by placing quotes around 'true', to force it to behave as a string.

- name: BACKUPS
    value: 'true'

Perhaps this is the correct fix, and no changes need to be made.

**Comment by lloesche** [comment]
It is. Without the quotes yaml turns it into a boolean which again, the shell knows nothing about. Passing it as a string is the correct thing to do.

**Comment by axenic** [comment]
I know this is closed, but just thought I'd put this out there as a possible solution:  

BACKUPS=TRUE
if [ `echo $BACKUPS | tr '[A-Z]' '[a-z]'` = true ]; 
  then echo 'true'; 
fi 

where BACKUPS could be True, TRUE, trUE, true, false, FALSE, False, etc

thanks again for your great work!
