### ISSUE TITLE
vplus not downloading - 403

### ISSUE THREAD

**Issue by FelixReuthlinger** [lloesche/valheim-server-docker#364]
This is something really weird. I have multiple servers running using this docker image build, some of them today and also yesterday started fine doing a fresh installation, but some server sometimes cannot properly download vplus and gets a 403 returned for the exact same download that succeeds at another server:

valheim_1  | Jun  2 10:10:51 /supervisord: valheim-updater INFO - Valheim Server is already the latest version
valheim_1  | Jun  2 10:10:51 /supervisord: valheim-updater DEBUG - [57] - ValheimPlus is enabled - running updater
valheim_1  | Jun  2 10:10:51 /supervisord: valheim-updater curl: (22) The requested URL returned error: 403
valheim_1  | Jun  2 10:10:51 /supervisord: valheim-updater FATAL - Error: could not retrieve ValheimPlus release info from Github API
valheim_1  | Jun  2 10:10:51 /supervisord: valheim-updater DEBUG - [57] - Writing file to start Valheim server
valheim_1  | 2021-06-02 10:10:51,933 INFO spawned: 'valheim-server' with pid 157
valheim_1  | Jun  2 10:10:51 /supervisord: valheim-server DEBUG - [157] - Valheim Server is not yet downloaded - waiting
valheim_1  | Jun  2 10:10:58 /supervisord: valheim-server DEBUG - [157] - Valheim Server is not yet downloaded - waiting

**Comment by lloesche** [comment]
403 means Github has blocked your IP from making any more requests. I believe the limit is 60 requests per hour. Each container with V+ enabled does 4 requests per hour by default. This can be changed using the `UPDATE_CRON`.

**Comment by FelixReuthlinger** [comment]
So, you would recommend to do less frequent updates? I think anyways doing it like once a day might be enough. We anyways usually update the v+ dll manually via scp action from out git that manages the config and plugins.

**Comment by lloesche** [comment]
Yes, although 60 per hour means you could run 15 servers in parallel before running into that limit. That said if you restart the container several times that can also add up. I've added a check now that makes it so that when the mod updater fails the entire valheim-updater script fails and does not try to start the server which currently leads to the issue you're seeing in #363
