### ISSUE TITLE
Notice: Port range

### ISSUE THREAD

**Issue by ibex-are-goats** [lloesche/valheim-server-docker#369]
FYI, I found a site that says Valheim uses more ports than 2456-2457. I don't know if that's true or not, but just trying to help. :) 

https://portforward.com/valheim/

> Valheim - Steam
> TCP: 2456-2457,27015-27030,27036-27037
> UDP: 2456-2457,4380,27000-27031,27036

Keep up the good work!

**Comment by lloesche** [comment]
By default Valheim server binds on udp/2456 and if the server is public the Steam query port will bind one up from the server so with default settings udp/2457. No other incoming ports are currently in use.
