### ISSUE TITLE
Unable to connect to private server

### ISSUE THREAD

**Issue by Nexlo** [lloesche/valheim-server-docker#37]
Hey guys,

I am trying to connect to my own Valheim server - unfortunately not working yet.
I am using the docker image of this repository.
Docker start command: `docker run -d --name valheim-server -p 2456-2458:2456-2458/udp -p 2456-2458:2456-2458/tcp -v /home/nexlo/valheim-config:/config -e SERVER_NAME="NexloTest" -e WORLD_NAME="Neotopia" -e SERVER_PASS="secret" <image-path>`
My server gets listed here: https://southnode.net/steamquery.php
If I start the same image locally, I am able to connect locally. Remote I only get the server listed (via port 2457) but unable to connect.
Host-Native OS is Debian10

Any suggestions? What do I miss? Thanks in advance! :)

**Comment by lloesche** [comment]
The tcp ports are not required but shouldn't harm either. Since you can connect locally but not remote by process of elimination it is very likely a packet filtering / firewalling issue. When you connect remotely what steps do you take? The ones described here? https://github.com/lloesche/valheim-server-docker#steam-server-favorites--lan-play

**Comment by Nexlo** [comment]
Hey @lloesche ,

thanks for your quick response!

Well, what should I say now... - its working :D - I have nothing changed - its really about the Steam-Server listing/connect... penetrating the refresh button was the solution *what the....*

I am used to use steam-connect links e.g. steam://connect/<IP-PORT>  (helped me with ARK servers), but in this case it seems **not** working well.

SumUp (if people encounter similar issues):
Add your sever to your favourite list (**with 2456**). It may will disappear - thats when you press "refresh" as much as you can and if the server is visible double click it. Do not use port 2457 for connection/favourites. Filtering for Game: Valheim may also help if your list is too long.

@lloesche Dank nochmals! :) Saubere Lösung ohne unnötiges Zeugs ;) <3
