### ISSUE TITLE
Feature request: more options for docker-compose

### ISSUE THREAD

**Issue by ibex-are-goats** [lloesche/valheim-server-docker#370]
Hello, I attempted to add a few options to the docker-compose.yml, but I wasn't able to figure it out. So it would be nice to add all the available options to the sample docker-compose.yml, then we can customize them accordingly. 

I attempted to use: timeout, cpu_priority, memory_limit.

**Comment by lloesche** [comment]
If we specify them in the compose file they would have to have default values that might conflict with global values people are currently using.
Also I don't feel this is something this game server container should solve as it's not specific to this container.

It is more an issue of reading the Docker documentation and applying it. I would suggest taking a simple container like `busybox` and create a compose file for it, then play around with the Docker options, exec into a shell, look at how the different options affect the shell environment and that way learn how they work.

**Comment by lloesche** [comment]
By the way, that is not to say you can't ask for help with specific options in the Discussions or an Issue here. I just won't put them into the compose file for thousands of users who don't need them.

**Comment by ibex-are-goats** [comment]
Is specifying restart but not stop-timeout arbitrary? Did you make one of those, and the other is part of the tool? Because I couldn't find half this stuff in the Docker documentation.

Maybe for consistency you should just add all the relevant options but #commented out. That way it acts as documentation, and people won't need to ask questions.

**Comment by lloesche** [comment]
You are mixing Docker cli options with compose file options. They, for whatever reason, are not the same. `--stop-timeout` on the command line is `stop_grace_period` in the compose file.

All the cli args are documented here https://docs.docker.com/engine/reference/commandline/run/
All the compose file options here https://docs.docker.com/compose/compose-file/compose-file-v3/

Generally speaking this repo is about packaging Valheim server into a Linux container image. It is up to you how you would like to run your containers. Docker is one way. You could also use podman or schedule it via Mesos or Kubernetes.

All the documentation is there to give you a good starting point and integrate the container into your own individual environment. I know of a game server provider who uses this container and sells it to their customers, running hundreds of instances in a K8S environment. Their requirements are different from the people who run the container on their NAS at home. And then there are people who run it on the same Linux box they also run their Valheim client on. Few environments look the same and so the documentation will never cover all use cases.

**Comment by ibex-are-goats** [comment]
That document seems to say that some of your v3 compose file options were removed or changed from v2 to v3, and the options in your compose file don't match the options in the command line example in the readme.

**Comment by ibex-are-goats** [comment]
Wow, I asked the Docker people for some clarity, and they said both v2 and v3 are deprecated, and they're now using this unversioned spec: https://github.com/compose-spec/compose-spec/blob/master/spec.md

So the official name and version of the compose specification is now just... "Compose Specification"
