### ISSUE TITLE
ARM64/v8 not working

### ISSUE THREAD

**Issue by chrenderle** [lloesche/valheim-server-docker#374]
Tried to run it on a Raspberry Pi 4 (CM) but got a warning 

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
The logs of the container:
`standard_init_linux.go:219: exec user process caused: exec format error`

So I guess arm is not supported? Is there a way to fix this?

**Comment by InB4DevOps** [comment]
No, the container requires amd64 architecture.
