### ISSUE TITLE
Log warning: "rm: missing operand"

### ISSUE THREAD

**Issue by ibex-are-goats** [lloesche/valheim-server-docker#378]
On Synology NAS, I noticed this in the logs. The rm command does exist and work.

```
INFO - Removing all but the newest 24 backups
rm: missing operand
Try 'rm --help' for more information.
INFO - Removing backups older than 9999 days
```

And then no warning after the last INFO. 

Docker compose includes:

```
      - BACKUPS=true
      - BACKUPS_MAX_COUNT=24
      - BACKUPS_MAX_AGE=9999
      - BACKUPS_IF_IDLE=false
```

**Comment by lloesche** [comment]
Seems like a bug. What is says is that `rm` was called without any arguments. I'm guessing the current code does not handle a situation where there's no more than 24 backups so it has none to delete, or something along those lines.

**Comment by Tremolo4** [comment]
I noticed this as well (only after my PR was merged 😅) and tried fixing it with `xargs --no-run-if-empty` but for some reason it still called `rm` with empty arguments... then I forgot about it. Thanks for the fix!
