### ISSUE TITLE
Massive hard drive usage every 20 minutes

### ISSUE THREAD

**Issue by salvoza** [lloesche/valheim-server-docker#379]
Good day,

I am seeing a massive spike to the hard drive usage every 20 minutes on the docker.

11:08:41  588879 be/4 root        0.00 B/s   42.10 M/s  0.00 %  0.01 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
11:28:43  590375 be/4 root        0.00 B/s   44.26 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
11:48:45  591985 be/4 root        0.00 B/s   45.60 M/s  0.00 %  0.00 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
12:08:48  593441 be/4 root        0.00 B/s   45.73 M/s  0.00 %  0.03 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
12:28:49  594942 be/4 root        0.00 B/s   43.17 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
12:28:50  594942 be/4 root        0.00 B/s   26.68 M/s  0.00 % 41.87 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
12:48:52  596479 be/4 root        0.00 B/s   44.91 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:08:54  598237 be/4 root        0.00 B/s   43.41 M/s  0.00 %  0.01 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:08:55  598237 be/4 root        0.00 B/s   25.41 M/s  0.00 % 24.55 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:28:56  599765 be/4 root        0.00 B/s   36.87 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:28:57  599765 be/4 root        0.00 B/s   32.48 M/s  0.00 % 24.39 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:48:58  601312 be/4 root        0.00 B/s   35.83 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
13:48:59  601312 be/4 root        0.00 B/s   35.01 M/s  0.00 % 16.47 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:09:00  602758 be/4 root        0.00 B/s   37.76 M/s  0.00 %  0.00 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:09:01  602758 be/4 root        0.00 B/s   27.07 M/s  0.00 % 40.21 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:29:03  604287 be/4 root        0.00 B/s   39.39 M/s  0.00 %  0.01 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:29:04  604287 be/4 root        0.00 B/s   21.77 M/s  0.00 % 52.69 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:49:05  605831 be/4 root        0.00 B/s   42.63 M/s  0.00 %  0.01 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
14:49:06  605831 be/4 root        0.00 B/s   29.95 M/s  0.00 % 22.46 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
15:09:07  607315 be/4 root        0.00 B/s   35.16 M/s  0.00 %  0.00 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
15:09:08  607315 be/4 root        0.00 B/s   29.61 M/s  0.00 % 21.42 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 
15:29:10  608818 be/4 root        0.00 B/s   42.62 M/s  0.00 %  0.02 % valheim_server.x86_64 -nographics -batchmode -name Salvo-Valheim 

This spike is causing there to be issues with some of the other processes on the box that are required to write to disk.

The hardware is as follows:

Intel Xeon E3-1246V3
2x HDD SATA 2,0 TB Enterprise | 
4x RAM 8192 MB DDR3

Thanks,
Salvo

**Comment by lloesche** [comment]
This is happening in Valheim server so you should contact the game devs about the issue. There's nothing we can do inside the container to change Valheim server disk activity.
