### ISSUE TITLE
Locally Server connects and disconnects then connects again.

### ISSUE THREAD

**Issue by baruchvlz** [lloesche/valheim-server-docker#380]
As the title says, when I run the image on my WSL environment, the server would connect, then disconnect and connect again. Then when I try to access it the server in game, it just lingers in a black screen after entering the password.

```bash
valheim_server_1  | Jul  6 11:33:52 /supervisord: valheim-server 07/06/2021 11:33:52: Game server connected
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Got status changed msg k_ESteamNetworkingConnectionState_Connecting
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: New connection
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Accepting connection k_EResultOK
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Connecting to Steamworks.SteamNetworkingIdentity
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Got status changed msg k_ESteamNetworkingConnectionState_Connected
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Connected
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Got connection SteamID [OMITTED]
valheim_server_1  | Jul  6 11:35:29 /supervisord: valheim-server 07/06/2021 11:35:29: Got handshake from client [OMITTED]
valheim_server_1  | Jul  6 11:35:31 /supervisord: valheim-server 07/06/2021 11:35:31: Game server disconnected
valheim_server_1  | Jul  6 11:35:45 /supervisord: valheim-server 07/06/2021 11:35:45: Game server connected
```

I saw that #335 could be related. I tried adding `cap_add: [sys_nice]` to my docker compose to no avail.

**Comment by lloesche** [comment]
Is the Windows client running on the same machine and you're just connecting to localhost:2456 which is the container running in WSL2 Docker?
I don't think the thread priority for which cap_sys_nice is relevant has any influence on this. Anytime that played a role the log would be flooded with latency error messages not just disconnects/reconnects. This feels more like a networking issue of sorts. 
Do I understand it correctly, that you've never been able to successfully join the game on this server?
Like, on the client the screen stays black and you get these log lines on the server?

**Comment by baruchvlz** [comment]
> Is the Windows client running on the same machine and you're just connecting to localhost:2456 which is the container running in WSL2 Docker?

I do this on my computer. I have a WSL2 instance for docker, this WSL2 instance has a dedicated IP. I do this to develop mods that require a server <-> client communication. To answer the question, yea the Windows client runs on the same machine as the WSL2 layer.

It's good to point out, that the docker image works like a charm in my dedicated servers (i have one that's public and one that's for friends).

> Do I understand it correctly, that you've never been able to successfully join the game on this server?

I used to be able to run it with no problems, I guess last time I ran it was probably 2 months ago.

> Like, on the client the screen stays black and you get these log lines on the server?

So I "Join Server" add the IP then that starts the server <-> client handshake. I enter the password and, in the game code, that finalizes the handshake and manages the user (kick, ban, or allow). This is where the black screen shows up and nothing happens (longest I tried was ~ 5 mins).

**Comment by lloesche** [comment]
Took me a while to reproduce the exact setup but I now have the container running in Docker on a Windows system in WSL2. I was able to connect to `localhost`. So doesn't seem to be a general issue with the container running on Docker in WSL2.
![image](https://user-images.githubusercontent.com/2124094/126623403-45269c47-fc4c-4711-849e-dcb1983a11d8.png)

The next lines that should come after the handshake are
```
Jul 22 10:07:21 /supervisord: valheim-server 07/22/2021 10:07:21: VERSION check their:0.156.2  mine:0.156.2
Jul 22 10:07:21 /supervisord: valheim-server 07/22/2021 10:07:21: Server: New peer connected,sending global keys
Jul 22 10:07:40 /supervisord: valheim-server 07/22/2021 10:07:40: Got character ZDOID from Luu : 2007633509:1
```

So it seems that in your environment it doesn't even get to do the version check. As to why that is I'm pretty clueless. Like, if it wouldn't be able to connect at all I'd say there's a networking issue with the virtual network on that system. But since it's doing the handshake it seems strange it wouldn't be able to exchange some more packets after that to do the version check.
It still all smells like a networking issue to me. I just have no idea where to look next.

**Comment by baruchvlz** [comment]
@lloesche I appreciate you checking the issue, it might be something wrong with my WSL2 network but since I have a dedicated server + a test server I can use those to test things.
