### ISSUE TITLE
Implement other command line tools for compression

### ISSUE THREAD

**Issue by TheHades** [lloesche/valheim-server-docker#389]
This is just a RFC.
Besides zip we could also implement zstd for compressing backups.
zstd is able to compress and decompress multi-threaded.

Maybe it is also useful to implement a variable (`BACKUP_METHOD`) for the various backup methods?
Setting `BACKUP_METHOD` to `zip` will use the "legacy" backup method. This should also be the default.
`raw` will store uncompressed backups (https://github.com/lloesche/valheim-server-docker/issues/349) and `zstd` will use zstd for compression of backups.

We could also add a variable called `BACKUP_COMPRESSION_LEVEL`, so it is possible to adjust the compression level?

I did some (quick) testing with my world. (size: 62MB)
`-1`is the lowest compression level, but it is faster and better than zip.

```
root@1377fa75870f:~# time zstd -1 world.db
world.db     : 29.66%   (62373157 => 18497247 bytes, world.db.zst)

real	0m0.425s
user	0m0.451s
sys	0m0.034s

root@1377fa75870f:~# time zip -v -1 world.db.zip world.db
updating: world.db .....	(in=62373157) (out=20168884) (deflated 68%)
total bytes=62373157, compressed=20168884 -> 68% savings

real	0m1.712s
user	0m1.650s
sys	0m0.060s
```

With zip default compression level (`-6`):
```
root@1377fa75870f:~# time zip -v world.db.zip world.db
updating: world.db .....	(in=62373157) (out=19356645) (deflated 69%)
total bytes=62373157, compressed=19356645 -> 69% savings

real	0m2.150s
user	0m2.117s
sys	0m0.032s
```

Any suggestions? :)

**Comment by lloesche** [comment]
So the idea behind using ZIP was that people can open the files on their Windows PCs by default. If it wasn't for that I'd likely just have created tarballs.

I think instead of adding more specific compression methods to the image I'd rather have people turn off compression (which they now can thanks to your patch) and then use the pre and post hooks to use whichever compression system they prefer.
