### ISSUE TITLE
Player name empty in status HTTP payload

### ISSUE THREAD

**Issue by ecotner** [lloesche/valheim-server-docker#391]
So I enabled the status HTTP server with the `STATUS_HTTP=true` flag, and am hitting the endpoint (http://localhost:9000/status.json) for a server I'm running locally. It appears that the Steam API is properly detecting when I log in/out because the number of players in the array in the payload increases/decreases appropriately. However, the information is incomplete - the player name is simply an empty string:
```json
{
  "last_status_update": "2021-09-05T08:59:14.112084+00:00",
  "error": null,
  "server_name": "Eric's test server",
  "server_type": "d",
  "platform": "l",
  "player_count": 1,
  "password_protected": true,
  "vac_enabled": false,
  "port": 2456,
  "steam_id": 90150931565623300,
  "keywords": "0.156.2",
  "game_id": 892970,
  "players": [
    {
      "name": "",
      "score": 0,
      "duration": 130.78070068359375
    }
  ]
}
```

I have the following relevant environment variables set; do you see any problem?
```bash
SERVER_PUBLIC=true
STATUS_HTTP=true
STATUS_HTTP_PORT=9000
```

**Comment by TheHades** [comment]
See https://github.com/lloesche/valheim-server-docker#status-web-server

> All the information in status.json is fetched from Valheim servers public query port. You will notice that some of the fields like player name or player score currently contain no information. However for completeness the entire query response is left intact.

**Comment by ecotner** [comment]
ahh didn't see that, thank you. so this is something that Steam or the Valheim developers will need to address themselves then?

**Comment by ecotner** [comment]
I think I found a bug report for this. if anyone else coming here would like to see this resolved, please upvote here to put it on the Valheim devs' radar:
https://valheimbugs.featureupvote.com/suggestions/160117/enhance-valve-protocol-support

I'll close the issue since there is nothing that can be done from our side
