### ISSUE TITLE
Can't start imported Worlds

### ISSUE THREAD

**Issue by fclante** [lloesche/valheim-server-docker#402]
HI im running the latest version of the docker image with VALHEIM_PLUS=true among others.

When I copy a world from my PC to  the server at ~/valheim-server/config/worlds  it fails to load that world and loads a new untouched one.

I've made sure that the WORLD_NAME is set correctly when starting the container. 
I've checked that the correct permissions were set on the files.

the world play perfect in a local game hosted on my own pc. 

Can it be due to the fact that this world started as a vanilla Valheim game and not as a Valheim Plus game? 
Any Ideas?

**Comment by lloesche** [comment]
> Can it be due to the fact that this world started as a vanilla Valheim game and not as a Valheim Plus game

No that shouldn't matter. I've been switching back and forth between V+ and vanilla.

Can you post the entire logfile from container start to when it starts the world?

**Comment by fclante** [comment]
Hi Thanks for the quick reply.
 I solved  it by:

- first stopping and removing the container.
- Then i copied the world
- Set permissions to on owner and group
- restarted the container

I don't know what I did wrong the first couple of time, but I suspect that I somehow did not get the permissions correct after copying them.
