### ISSUE TITLE
Documentation or Enhancement - Ability to send in-game shouts using pre and post hooks

### ISSUE THREAD

**Issue by maxfield-allison** [lloesche/valheim-server-docker#420]
Good morning,
I want to be able to send shout messages in game so that players know when the server is being shutdown or restarted. The pre and post hooks can be used for this and combine both discord and in-game shouts.

**Comment by TheHades** [comment]
Does it work, if you run the PRE_BOOTSTRAP_HOOK via bash?

```
docker exec -ti CONTAINERNAME bash
```

and then:  (don't forget to replace the Variables)

```
curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo Starting Valheim server $$SERVER_NAME)\"}" "https://discord.com/api/webhooks/yadayadayadayada"'
```

**Comment by maxfield-allison** [comment]
That gave me the info I needed to be able to test. it does work and I can control the payload. still having trouble getting the yaml to correctly recognize the string

**Comment by maxfield-allison** [comment]
Finally got it working with:
`- 'PRE_SERVER_SHUTDOWN_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim Server\",\"content\":\"$actualMessage\"}" "$actualwebhook" && sleep 60'`
