### ISSUE TITLE
mmhook files get deleted when starting server

### ISSUE THREAD

**Issue by lawl281** [lloesche/valheim-server-docker#422]
When starting server multiple times such as when setting up and verifying things sometimes mmhookgen files get deleted.

**Comment by lloesche** [comment]
Where are those files located? Are they in the `/config/bepinex/plugins` folder?
See https://github.com/lloesche/valheim-server-docker#bepinexpack-valheim for details.
If you manually copy anything to anywhere outside of `/config` like e.g. patching files in `/opt` chances are your changes will be replaced on the next server validation run.

**Comment by lawl281** [comment]
MMHook requires a config folder that is placed in data/plus/BepInEx (this replaces the 0kb config file), as well as a patcher folder that is placed in the data/plus/BepInEx patchers folder. There are several mods that require this to run including Jotunn the Valheim Library which is a library many mods require to run as it makes modding easier.

**Comment by lloesche** [comment]
This sounds related to #392 
Could their workaround work for your?
I'm not playing Valheim at the moment so have no way of confirming/testing.

**Comment by lawl281** [comment]
This does seem like a related issue, I'll test out their workaround and see if there is anything else that could be done as well. thanks
