### ISSUE TITLE
[shameless plug] Looking for a technical writer 👩‍🏫 🧑‍🏫 👨‍🏫

### ISSUE THREAD

**Issue by lloesche** [lloesche/valheim-server-docker#423]
Hi there 👋,

I'm looking for a technical writer 📚 for one of my other open source projects: https://github.com/someengineering/cloudkeeper

The current project docs are at https://docs.some.engineering/
I wrote a lot of them myself and I am not a native speaker. So they are pretty meh 😩.

I'm looking for someone with a good technical understanding around Linux 🐧, cloud technologies ☁️, query languages 📊 (think SQL, GraphQL) and containers 🚢. Roughly speaking. You don't have to be an expert in any of them, just have an understanding of what they are and how they are being used. Number one priority is preferably being a native speaker and mandatorily having mad writing skills ✍️. A deep understanding of where the comma belongs in the sentence and how to structure technical documentation. How to present information so it is easily consumable for newcomers.

This is a paid position 💵. Can be full-time, part-time or contracting. We have a US Inc. as well as a German GmbH, so can hire anyone in the US or EU or provide a contracting agreement worldwide.

I'm posting this here instead of some job portal, because the person I'm looking for is likely on Github.
I ❤️ open source and so should the ideal candidate.

If this speaks to you or you know someone who might be a good candidate, contact me at lukas@some.engineering or [join our Discord https://discord.gg/someengineering](https://discord.gg/someengineering) and PM me (Lukas) there.

P.S. Don't emoji make everything more fun to read? 📖 I think so! 😂
P.P.S. Our software is also pretty neat though still early alpha. If you're working with many AWS or GCP accounts it might be useful to you. Go check it out. It's all open source 💾.
P.P.P.S. This is my(!) personal Github repo. Any comments along the lines of "I'm not here to read job ads" will be quietly deleted.
P.P.P.P.S. Did you know this can go on ad infinitum ♾️ ?

**Comment by lloesche** [comment]
@TheCatLady you once mentioned you'd be willing to proof read documentation. Could this be something you're interested in as a side gig (or permanent - think of all the cat scratchers 🙀)?

**Comment by TheCatLady** [comment]
> @TheCatLady you once mentioned you'd be willing to proof read documentation. Could this be something you're interested in as a side gig (or permanent - think of all the cat scratchers 🙀)?

Yes!

**Comment by lloesche** [comment]
Position is filled. Thank you!
