### ISSUE TITLE
Name missing from status.json

### ISSUE THREAD

**Issue by CWSpear** [lloesche/valheim-server-docker#425]
The `status.json` seems to be updated timely, but it's missing the names. We were hoping to use it to quickly tell who's online, etc, but everyone is `""`.

```json
{
  "last_status_update": "2021-12-06T06:37:49.339136+00:00",
  "error": null,
  "server_name": "My Server",
  "server_type": "d",
  "platform": "l",
  "player_count": 2,
  "password_protected": true,
  "vac_enabled": false,
  "port": 1111,
  "steam_id": 11111111111111111,
  "keywords": "1.111.1@1.1.1",
  "game_id": 111111,
  "players": [
    { "name": "", "score": 0, "duration": 534.55029296875 },
    { "name": "", "score": 0, "duration": 484.1844787597656 }
  ]
}
```

**Comment by TheHades** [comment]
This is not a bug within the docker container.
See https://github.com/lloesche/valheim-server-docker/issues/391#issuecomment-914541460

**Comment by CWSpear** [comment]
As I dug more, I was beginning to think that that was the case! Thanks for the update. Hopefully it's something that can be resolved someday. :)
