### ISSUE TITLE
Server Name no longer appears in in-game search

### ISSUE THREAD

**Issue by flintstryker** [lloesche/valheim-server-docker#428]
With a recent Valheim update within the past month, my server name no longer appears in the in-game search under the Join Game tab. 
I've tried recreating my container a couple of times with different names, but not having any luck.

Let me know if there's a way to get any useful info to attach here.

**Comment by smosse** [comment]
are you sure you have both 2456 and 2457 ports open ? I think 2457 is used to be listed.
