### ISSUE TITLE
Flag to disable backups

### ISSUE THREAD

**Issue by zaldre** [lloesche/valheim-server-docker#43]
Hi, More of a question than an issue.

Can you advise on a method to disable the automated backups in the container? I am using an externally managed backup solution and it feels redundant to have the container backing up as well as snapshotting the disk

**Comment by DavidFuchs** [comment]
Not the author, but I peeked around, and it looks like there is no way to do this out of the box yet.

If it's not too much trouble for you, you could create a new Docker image that inherits from this one, and keep it all the same except provide your own copy of `/etc/supervisor/supervisord.conf` that doesn't have the `[program:valheim-backup]` section in it.

**Comment by zaldre** [comment]
No worries, I think that may be a little more effort than i wish to expend (Managing updates to the original container and re-pushing every few days sounds less than ideal)

I ended up just making the backup interval several hours and backing it up to the ephemeral storage inside the container (/tmp/backups).

Not the most elegant solution, but that should suffice for now.

**Comment by lloesche** [comment]
Fixed in https://github.com/lloesche/valheim-server-docker/commit/0e2ef3bc2ca9f53f21a9f0538239c63b38db0349
Providing `-e BACKUPS=false` will now turn off the valheim-backups process on start.
