### ISSUE TITLE
How to view logs

### ISSUE THREAD

**Issue by tomas-samot** [lloesche/valheim-server-docker#443]
How do you view these logs:
![image](https://user-images.githubusercontent.com/15977784/151454511-5dd3afb1-efc3-4909-b973-2c59c297ec69.png)

I tried to look for them in `/home/valheim/.steam/logs` and I checked `docker logs valheim-server | grep 'got handshake'`. `/home/valheim/.steam/logs` did not exist.

**Comment by lloesche** [comment]
The `G` in `Got` is a capital letter.

**Comment by tomas-samot** [comment]
Thank you for pointing that out. Late night sessions aren't always productive 👍
