### ISSUE TITLE
Question about $SERVER_ARGS and $STEAMCMD_ARGS

### ISSUE THREAD

**Issue by schloram** [lloesche/valheim-server-docker#446]
Hi,
first of all: Thanks for your effort in bringing us a ready to go Valheim Server! 🙏 It's awesome.

While I'm playing around a little with my Valheim Server there is just one thing that is not quite clear to me:
What exactly are the above env variables for? What can I achieve with them? Is there an external documentation about the possible arguments both scripts (steamcmd and valheim_server.x86_64) allow?

Thanks for clarification.

**Comment by lloesche** [comment]
They are more for future proofing than anything else. In case you would want to customize either the steamcmd or valheim_server cli args you could. When I added them I just assumed that maybe others will want to use this container in ways different from how I use it. If so, I didn't want to be in the way. If Valheim tomorrow releases a new version of the server that has a feature flag which allows you to do an awesome thing, you won't have to wait for me to update the container, you can just turn that feature on yourself by setting the corresponding env var. 🙂

**Comment by schloram** [comment]
Thank you for your quick response!
