### ISSUE TITLE
Question about public status.json

### ISSUE THREAD

**Issue by schloram** [lloesche/valheim-server-docker#450]
Hi,
me again.  I have a question about the `status.json` and how to access it from the web.

I have these two env variables set:

```
SERVER_PUBLIC=true
STATUS_HTTP=true
```
(`STATUS_HTTP_PORT` is left untouched)

Shouldn't then the `status.json` file be publicly available via `my.valheim-server.com/status.json`? Am I missing something or do I have to set something else? Because I can't get this to work. 🤔 I can connect to the server from the Valheim Server list with `my.valheim-server.com` so the DNS shouldn't be a problem (I guess).

I currently use the [systemd service](https://github.com/lloesche/valheim-server-docker#deploying-with-docker-and-systemd) to run the container.

Where can I check if the "status web server" mentioned in [this section](https://github.com/lloesche/valheim-server-docker#status-web-server) os up and running?

Any help would be appreciated. Thank you :)

**Comment by schloram** [comment]
@ericljiang Thanks for your help.

I tried that already and unfortunately it returns

```
curl: (7) Failed to connect to localhost port 80: Connection refused
``` 

Do I have to include the `-v` parameter for port 80 in the [valheim service](https://github.com/lloesche/valheim-server-docker/blob/main/valheim.service) as well?

**Comment by schloram** [comment]
Okay it was just the line `-p 80:80/tcp \` inside the systemd service I was missing. I could have figured that out earlier. 🙈

**Comment by ericljiang** [comment]
Ah yes I forgot about that too
