### ISSUE TITLE
After update valheim not working any more.

### ISSUE THREAD

**Issue by thijsjek** [lloesche/valheim-server-docker#456]
Recently i updated (through watchtower) to the latest on 15-02.  Afterwards Valheim container is not working anymore.
<details>
  <summary>Docker logs</summary>

```
today at 20:34:09INFO - Setting timezone Etc/UTC
today at 20:34:09INFO - Setting up syslogd - logging to stdout
today at 20:34:09INFO - Supervisor http server activated
today at 20:34:09Traceback (most recent call last):
today at 20:34:09  File "/usr/local/bin/supervisord", line 6, in <module>
today at 20:34:09    from pkg_resources import load_entry_point
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
today at 20:34:09    @_call_aside
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
today at 20:34:09    f(*args, **kwargs)
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
today at 20:34:09    working_set = WorkingSet._build_master()
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
today at 20:34:09    ws.require(__requires__)
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
today at 20:34:09    needed = self.resolve(parse_requirements(requirements))
today at 20:34:09  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
today at 20:34:09    raise DistributionNotFound(req, requirers)
today at 20:34:09pkg_resources.DistributionNotFound: The 'setuptools' distribution was not found and is required by supervisor
today at 20:34:47Container stopped
```
</details>

**Comment by jpmarcotte** [comment]
This was fixed as part of #448 on 18-02. Try updating again.

**Comment by pdxgeek421** [comment]
After I did a manual ```docker pull lloesche/valheim-server``` after the fix was released,  both the updated fixed image from #448 and the the broken image had the "latest" tag on them when viewed with ```docker images```, and it would choose the broken old image over the current new image.

I ran ```dc stop valheim; dc rm -f valheim```,  removed the old image with ```docker image rm 219a20e14ed7``` and then re-ran ```dc up -d valheim``` and that fixed it.

**Comment by DragonQ** [comment]
Same problem here, had to do a `dc down; docker image rm 219a20e14ed7; dc up -d`.

**Comment by caretakerscurse** [comment]
Was having this issue, switching from `lloesche/valheim-server` to `ghcr.io/lloesche/valheim-server` fixed the issue for me.

**Comment by themightylc** [comment]
I have this exact issue. 
I'm pulling ghcr.io/lloesche/valheim-server
Never got the server to run.

**Comment by dfibuch** [comment]
I cant get a brand new server to run at all using the latest pull link. Just keeps shutting down and coming back up again every 3 minutes
