### ISSUE TITLE
Possible to run on rPi4?

### ISSUE THREAD

**Issue by C0untZero** [lloesche/valheim-server-docker#46]
Hi,
I just tried running this container on an rPi4 and I'm getting the following error in the logs once it starts:
`standard_init_linux.go:219: exec user process caused: exec format error`

I'm using Portainer with this compose:
> version: "2.1"
> services:
>   valheim:
>     image: lloesche/valheim-server
>     container_name: myserv
>     environment:
>       - SERVER_NAME=myserv
>       - SERVER_PORT=2456
>       - WORLD_NAME=myserv
>       - SERVER_PASS=myserv
>       - SERVER_PUBLIC=1
>       - UPDATE_INTERVAL=86400
>       - BACKUPS_INTERVAL=3600
>       - BACKUPS_DIRECTORY=/config/backups
>       - BACKUPS_MAX_AGE=5
>     volumes:
>       - $HOME/valheim-server-config:/config
>     ports:
>       - 2456-2458:2456-2458/udp
>     restart: unless-stopped

Am I doing something wrong? Or is this just not intended for ARM/rPi?

**Comment by C0untZero** [comment]
Seems the dedicated server is x64 only :(

**Comment by Addyvan** [comment]
@lloesche We might want to reopen this issue?

**Comment by Addyvan** [comment]
@C0untZero If there was an ARM executable released, the docker container could be built to support ARM using buildx and tagged accordingly. After doing a small search I found a user running the client on a pi; however, it seems far from stable.

**Comment by C0untZero** [comment]
> @C0untZero If there was an ARM executable released, the docker container could be built to support ARM using buildx and tagged accordingly. After doing a small search I found a user running the client on a pi; however, it seems far from stable. 

Could you please link to the example of a user running it on pi? I couldn't find it the other day, and I'd lile to see the performance for myself.

**Comment by Addyvan** [comment]
@C0untZero Found this reddit post: https://www.reddit.com/r/valheim/comments/llvkgr/how_to_run_valheim_dedicated_server_on_raspberry/

**Comment by C0untZero** [comment]
> @C0untZero Found this reddit post: https://www.reddit.com/r/valheim/comments/llvkgr/how_to_run_valheim_dedicated_server_on_raspberry/
> 
> Seems like more trouble than its worth though...

Thanks!
