### ISSUE TITLE
the debug mode

### ISSUE THREAD

**Issue by tophlcvf** [lloesche/valheim-server-docker#465]
hi, 
how to allow the debug mod ?   admins can 't use the consol, but not the devcommands and debug mod.

thx

**Comment by schloram** [comment]
@tophlcvf Did you set the `-console` launch option in Steam? 

Have a look here: https://github.com/lloesche/valheim-server-docker#enable-admin-console

**Comment by tophlcvf** [comment]
yes, but i just got the console, not the debug mode

**Comment by schloram** [comment]
@tophlcvf Ah, now I get it. The `devcommands` (and therefore also the `debugmode`) command does not work on dedicated servers. You can just use simple commands like `kick` or `ban`. Type `help` in the console to to see which commands can be used.

**Comment by Gby56** [comment]
ah I was wondering why this was not working, is there any way that ValheimPlus or some mods can give back commands to admins ? Simple stuff like weather or whatever

**Comment by schloram** [comment]
@Gby56 Yes I've seen some mods that enable devcommands on dedicated servers. Not sure qhich one is the best. Just search for them in [Thunderstore](https://valheim.thunderstore.io/) (or Nexus) and pick the one that fits you best.
