### ISSUE TITLE
Option to have data volume in a custom location

### ISSUE THREAD

**Issue by joells101** [lloesche/valheim-server-docker#47]
currently the server data volume seem to be located in dockers volumes. I like to keep container data located in 1 spot. any way we could add an option to have have the data volume customized so I can put it where I want

**Comment by lloesche** [comment]
I'm not sure I understand. All the configuration is located in `/config` and the Valheim server download in `/opt/valheim_dl`. At the very least `/config` should be volume mounted from a host directory. Optionally, depending on ones Internet bandwidth it makes sense to also volume mount `/opt/valheim_dl` so the container does not have to download the 1 GB server binary upon each fresh start.

As to where those directories come from on the host is up to you. Like if you have all your container data located at `/data` on your container host you could volume mount e.g. `-v /data/valheim/config:/config -v /data/valheim/server:/opt/valheim_dl`.

Does that make sense? Was that the question? 🙂

**Comment by joells101** [comment]
super new to this docker stuff, can you tell? However I think you did manage to answer my question. I'll play around with it. thank you. this wasnt really an issue for your container it turns out so i do appreciate the answer.
