### ISSUE TITLE
[upstream bug] valheim-plus-updater breaking due to release mismatch

### ISSUE THREAD

**Issue by SlightlyOffSync** [lloesche/valheim-server-docker#474]
See https://github.com/valheimPlus/ValheimPlus/issues/701

Quick dirty hack: bash into your docker container and modify the valheim updater script(/usr/local/bin/valheim-plus-updater) to download 0.9.9.8 by tag

**Comment by Gyran** [comment]
update url to be to download 0.9.9.8
```
https://api.github.com/repos/valheimPlus/ValheimPlus/releases/tags/0.9.9.8
```

**Comment by SlightlyOffSync** [comment]
looks like they fixed it upstream
