### ISSUE TITLE
Kubernetes Deployments - More advanced Helm Logic

### ISSUE THREAD

**Issue by brandtkeller** [lloesche/valheim-server-docker#482]
## Context
(Need to mark this as a question)

## Question
Wanted to gauge interest in referencing a Helm Chart that I am building for this image.

The current helm chart referenced in the readme was not as extensible as I would like, and limited discoverability of configurations.

I am creating a helm chart [Here](https://github.com/brandtkeller/helm-valheim) and beginning to iterate on applying more extensible options with best practices for kubernetes deployments. I plan either way to reach out with some queries about how we can orchestrate this application image most effectively for end-users.

Feel free to say no, will not offend me. Just offering this up as a possible option.  
Thanks!

**Comment by lloesche** [comment]
Hi @brandtkeller, I looked at your code. Looks great! Thank you for your work! Feel free to open a PR that adds a link to your repo in the README's Kubernetes install section. Or if you'd like to take over the responsibility of maintaining an "official" helm chart I can add you as a committer and you could add the entire chart to this repo, up to you.

**Comment by brandtkeller** [comment]
Sounds great. I will go the separate repository route for the time being - and we can decide if there would be value in merging the content at a future date.
