### ISSUE TITLE
backup script no longer working since patch 0.209.8

### ISSUE THREAD

**Issue by galinette-34** [lloesche/valheim-server-docker#487]
Valheim **Patch 0.209.8** introduced a new directory `/config/worlds_local` to store the world files and no longer use the old directory `/config/worlds`.

Scripts `/usr/local/bin/valheim-backup` and `/usr/local/etc/valheim/common` need an update.

**Comment by manuman94** [comment]
Plus, when the server is auto-updated and auto-restarted creates a new world in "worlds_local" folder not respecting the original world.

**Comment by manuman94** [comment]
Note from Irongate Studios regarding the latest patch: https://store.steampowered.com/news/app/892970/view/6128850732740078767

```
Dedicated-server world loading fix.  This patch fixes the world load issue introduced in 0.209.8, causing dedicated servers to fail to load worlds saved in the now legacy “worlds/” directory (and instead creating a new empty world)  Unfortunately if you already got a world-reset caused by this, try removing the broken world from "worlds_local/" (but don’t touch “worlds/” ). This will make the server load the original working world from “worlds/” instead.  Shit happens 😦 sorry
```

This is why is happening what I said in my latest comment.

**Comment by manuman94** [comment]
haha @galinette-34 thanks for the info!

So my fix was the one proposed by Irongate and it worked (by stopping the server, deleting the "worlds_local" folder and restarting the server).

So there is no need to fix the world path for us. But maybe new server installations will start using the "worlds_local" folder and need to patch the backup system to backup that one.

Maybe the schema is "if <worlds_local> exist, backup that folder, else backup the classic <worlds> folder".

Thank you all! ;)

**Comment by Toblun** [comment]
Patch 0.209.9 dont fix this issue it just copy the save from worlds to worlds_local at server start if no save exist in worlds_local
backup script still just backup the old save in worlds

**Comment by bewczardski** [comment]
There is a pull request to solve this issue: https://github.com/lloesche/valheim-server-docker/pull/490

**Comment by lloesche** [comment]
The PR has been merged, please see if this fixes the issue! ty!

**Comment by UponABlackStar** [comment]
On my end the backup script is still looking for a `worlds` folder. The backups are empty.

- When the worlds are mounted to the `worlds` directory then backups are made correctly (world is not loaded for playing).
- When the worlds are mounted to the `worlds_local` directory then backups are empty (world is loaded for playing).

**Comment by lloesche** [comment]
> On my end the backup script is still looking for a `worlds` folder. The backups are empty.
> 
> * When the worlds are mounted to the `worlds` directory then backups are made correctly (world is not loaded for playing).
> * When the worlds are mounted to the `worlds_local` directory then backups are empty (world is loaded for playing).

Did you update the container? As in `docker pull` the latest version.

**Comment by galinette-34** [comment]
`docker-compose up --force-recreate` only recreate the container without updating the used image (`lloesche/valheim-server`)

you need tu update image, with  docker pull `lloesche/valheim-server`, before to recreate container.

`docker images --digests` should then list:
`lloesche/valheim-server   latest    sha256:8d910b15e3ab645a31c85799338d3dc043cabe891a34b43cbd574a1453837205`
this the digest of the last and corrected version.

**Comment by galinette-34** [comment]
Thanks everyone!
