### ISSUE TITLE
Performance Problems with large Maps

### ISSUE THREAD

**Issue by iocron** [lloesche/valheim-server-docker#494]
Some users can't connect to the server from time to time due to a timeout. Is there any way to increase max. timeout to login? The server has a very big map, so sometimes its possible to login, other times not. I haven't found any option to do that, I am currently running the docker container through the official docker-compose file from https://raw.githubusercontent.com/lloesche/valheim-server-docker/main/docker-compose.yaml

**Comment by lloesche** [comment]
This is a question for the Valheim developers. This Docker container has no way of influencing the client or server side connection timeouts.

**Comment by iocron** [comment]
@lloesche Thank you for the info, I didn't know it was hardcoded in the game :D I'll have to dig deeper to find a option to enable or increase the timeout (or I hope at least they will add it in the future).
