### ISSUE TITLE
failed to create symbolic link

### ISSUE THREAD

**Issue by Carsenik** [lloesche/valheim-server-docker#498]
I am using a Proxmox VM with Portainer and when I try and enable the Valheim Plus the logs are showing.

ln: failed to create symbolic link '/opt/valheim/plus.tmp/BepInEx/config': Operation not supported

Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/System.Runtime.Serialization.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/System.Security.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/System.Xml.Linq.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/System.Xml.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/System.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AIModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ARModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AccessibilityModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AndroidJNIModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AnimationModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AssetBundleModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.AudioModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ClothModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ClusterInputModule.dll
Aug 28 12:44:14 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ClusterRendererModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.CoreModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.CrashReportingModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.DSPGraphModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.DirectorModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.GIModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.GameCenterModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.GridModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.HotReloadModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.IMGUIModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ImageConversionModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.InputLegacyModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.InputModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.JSONSerializeModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.LocalizationModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ParticleSystemModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.PerformanceReportingModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.Physics2DModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.PhysicsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ProfilerModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.ScreenCaptureModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.SharedInternalsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.SpriteMaskModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.SpriteShapeModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.StreamingModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.SubstanceModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.SubsystemsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TLSModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TerrainModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TerrainPhysicsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TextCoreModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TextRenderingModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.TilemapModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UI.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UIElementsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UIElementsNativeModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UIModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UNETModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UmbraModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityAnalyticsModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityConnectModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityCurlModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityTestProtocolModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityWebRequestAssetBundleModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityWebRequestAudioModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityWebRequestModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityWebRequestTextureModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.UnityWebRequestWWWModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.VFXModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.VRModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.VehiclesModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.VideoModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.VirtualTexturingModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.WindModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.XRModule.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/UnityEngine.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/mscorlib.dll
Aug 28 12:44:15 /supervisord: valheim-updater >f+++++++++ unstripped_corlib/netstandard.dll
Aug 28 12:44:15 /supervisord: valheim-updater DEBUG - [132] - Ensuring /config/valheimplus/plugins exists
Aug 28 12:44:15 /supervisord: valheim-updater DEBUG - [132] - Storing BepInEx.cfg as /config/valheimplus/BepInEx.cfg.default
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - [132] - Writing BepInEx config
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - Reading mod config from env variables prefixed with BEPINEXCFG_
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - Found [Logging.Console] Enabled = true in environment
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - Reading existing mod config /config/valheimplus/BepInEx.cfg
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - Processing section Logging.Console
Aug 28 12:44:16 /supervisord: valheim-updater DEBUG - Setting Enabled = true in config section Logging.Console
Aug 28 12:44:16 /supervisord: valheim-updater INFO - Writing mod config /config/valheimplus/BepInEx.cfg.tmp
Aug 28 12:44:17 /supervisord: valheim-updater INFO - Moving old config /config/valheimplus/BepInEx.cfg -> /config/valheimplus/BepInEx.cfg.old
Aug 28 12:44:17 /supervisord: valheim-updater INFO - Moving new config /config/valheimplus/BepInEx.cfg.tmp -> /config/valheimplus/BepInEx.cfg
Aug 28 12:44:17 /supervisord: valheim-updater INFO - Syncing BepInEx plugins from /config/valheimplus/plugins/ -> /opt/valheim/plus.tmp/BepInEx/plugins
Aug 28 12:44:17 /supervisord: valheim-updater .d..t...... ./
Aug 28 12:44:17 /supervisord: valheim-updater /opt/valheim/dl/plus
Aug 28 12:44:17 /supervisord: valheim-updater DEBUG - [132] - Removing /opt/valheim/plus.tmp/BepInEx/config and symlinking from /config/valheimplus
Aug 28 12:44:17 /supervisord: valheim-updater ln: failed to create symbolic link '/opt/valheim/plus.tmp/BepInEx/config': Operation not supported
Aug 28 12:44:17 /supervisord: valheim-updater ERROR - Failed to extract and install ValheimPlus - retrying later
Aug 28 12:44:17 /supervisord: valheim-updater DEBUG - [42] - Writing file to start Valheim server
2022-08-28 12:44:17,631 INFO spawned: 'valheim-server' with pid 189
Aug 28 12:44:17 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting
Aug 28 12:44:24 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting
2022-08-28 12:44:27,661 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Aug 28 12:44:27 /supervisord: valheim-updater valheim-server: started
Aug 28 12:44:31 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting
Aug 28 12:44:38 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting
Aug 28 12:44:45 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting
Aug 28 12:44:52 /supervisord: valheim-server DEBUG - [189] - Valheim Server is not yet downloaded - waiting

**Comment by lloesche** [comment]
```
ln: failed to create symbolic link '/opt/valheim/plus.tmp/BepInEx/config': Operation not supported
```

Indicates that the filesystem you're trying to run Valheim Server on does not support creation of symlinks. This is likely just a flag you can toggle, unless the filesystem itself is one that doesn't support symbolic links (unlikely).

**Comment by fueleh** [comment]
what should this symlink be? how can i create it manually maybe? i also get supervisord: valheim-updater ln: failed to create symbolic link '/opt/valheim/plus.tmp/BepInEx/config': Operation not permitted
