### ISSUE TITLE
Synology App hangs

### ISSUE THREAD

**Issue by littleneutrino** [lloesche/valheim-server-docker#5]
I have followed the instructions to the letter, using a Synology DS1019+ Running the Latest official release firmware.
It hangs on the 

 DungeonDB Start 182 | stdout

After that it does another debug step but never continues. I can see it has created the world files, and the start_server.sh file is present as well as the adminlist, bannedlist, and permittedlist, and a prefs file. it just neter continues. even after letting it sit there for 30 minutes.

**Comment by lloesche** [comment]
That sounds correct. `DungeonDB Start` is the last message the server will output after startup. This means the server is ready to accept connections. Once you connect to the server there will be more log messages.
