### ISSUE TITLE
Guide for deploying to Azure?

### ISSUE THREAD

**Issue by SammyIsra** [lloesche/valheim-server-docker#517]
Is there a guide on deploying to Azure? If so, can it be linked to the Deployment header on the Readme? There's a guide that uses this image here: https://jakelunn.medium.com/host-a-valheim-dedicated-server-using-azure-container-instances-81d35b061f08, but it was written in May 2021 so I'm not sure if it's up to date or not. I tried going thru the guide but I am still unable to connect to the server.

**Comment by jjohnson2k1** [comment]
Hey @SammyIsra Just as a quick FYI I followed this exact same guide and was able to get a server up and running in about 20 minutes with Azure Container Instances. 

Are you getting any errors on deployment? Are you using Az CLI or portal?

**Comment by theCrius** [comment]
You can also use a simple VM deployment, install docker on it and follow the default instructions.

Doing it all the time with some free credit I've got.

**Comment by falkoro** [comment]
I was trying to deploy on Azure app service, unfortunately it was harder to open ports. I will now try container instance and will let you know.

A VM also works, but it more of a hassle and a bit more expensive.

**Comment by falkoro** [comment]
Okay, I got it tested. It runs. Unfortunately, I am not able to find it on Xbox yet. I can find it on Steam though in the server browser. 

The guide still works!

**Comment by SammyIsra** [comment]
So it turns out that my issue was that I had to enable crossplay in the server args. This was actually very recently added to the documentation, too: #584.

Therefore I will be closing this. Thank you all!
