### ISSUE TITLE
valheim-status reports 0 players online with -crossplay, resulting in lack of backups

### ISSUE THREAD

**Issue by recursiveGecko** [lloesche/valheim-server-docker#521]
It seems like the player count isn't reported correctly (it's always 0) when crossplay is enabled, resulting in backups not being created due to "the server being idle".

https://github.com/lloesche/valheim-server-docker/blob/f47432bfcc9de4308cfe78346bbfa579dbe4317b/common#L155-L169

A potential temporary fix to get the backups working again is to set `SERVER_PUBLIC=false` which forces UDP packet counting logic.

It might be worth falling back to UDP packet counting when `-crossplay` flag is present unless there's a better solution.

**Comment by lloesche** [comment]
Sounds like a sensible workaround. Would you like to submit a PR?
