### ISSUE TITLE
How can make the server run on public test?

### ISSUE THREAD

**Issue by NigelvanDuijvendijk** [lloesche/valheim-server-docker#524]
I want to make the server run on the new public test, how can i do this?

**Comment by NigelvanDuijvendijk** [comment]
i already tried adding  -beta public-test -betapassword "yesimadebackups" in download_valheim() in valheim-updater

**Comment by bagvendt** [comment]
It works for me by setting the environment variable like so

`STEAMCMD_ARGS="-validate -beta public-test -betapassword ****"

**Comment by koosc** [comment]
@bagvendt Does that work for you with the mistlands update? I had that previously and it worked fine but I currently see it crashing at start.

**Comment by zuned11** [comment]
Going to chime in and mention that I don't use the docker-compose version, and this line in my /etc/sysconfig/valheim-config worked for me:
`STEAMCMD_ARGS=-beta public-test -betapassword yesimadebackups`

**Comment by bagvendt** [comment]
> @bagvendt Does that work for you with the mistlands update? I had that previously and it worked fine but I currently see it crashing at start.

Yes!

This starts a mistlands public-test server:


```bash
docker run -d \
    --name valheim-server \
    --cap-add=sys_nice \
    --stop-timeout 120 \
    -p 2456-2457:2456-2457/udp \
    -v $HOME/valheim/config:/config \
    -v $HOME/valheim/data:/opt/valheim \
    -e SERVER_NAME="foobar" \
    -e WORLD_NAME="test" \
    -e SERVER_PASS="foobar" \
    -e STEAMCMD_ARGS="-validate -beta public-test -betapassword *****" \
    lloesche/valheim-server
```

**Comment by lloesche** [comment]
Hmm maybe we should just add a var like "PUBLIC_TEST=true" which adds those steamcmd args?
Seems like it would be convenient.

**Comment by koosc** [comment]
The only downside to that is it would need to assume the test and passwords will always have the same value, although this could very well be true. I think the current way works well but should maybe have an explicit example in the documentation?

**Comment by makarov-roman** [comment]
How to figure out the current installed version?
