### ISSUE TITLE
No server info

### ISSUE THREAD

**Issue by Diyagi** [lloesche/valheim-server-docker#525]
Hello,
I am having an issue where there is no server info on Favorite tab when I add the server, it shows fine thru steam server list, but not in game, I also can connect just fine to it, its just the server info thats not showing, any idea why ?

![server](https://user-images.githubusercontent.com/9062212/204054021-9f29f578-ecf0-431d-809d-684c9940cf6d.png)

**Comment by wcdanh2** [comment]
Is your server set as a public server?

**Comment by Diyagi** [comment]
> Is your server set as a public server?

Yes, it was, the server was shutdown tho, my friends decided to play it later this year.

**Comment by Djaytan** [comment]
Hello,
I have the same issue
The server is public as well
The port 2456 and 2457, and about what I understood this is the port 2457 which is involved for the retrieving of these information

**Comment by nitrodzen** [comment]
same issue, public=true

**Comment by Diyagi** [comment]
This is an issue with valheim itself, if you find you server in the community tab and add it to favorites, it shows the server info.
My guess is that the client itself dont query the server for info but rather pulls it from steam server list, and it does this by matching the server name itself rather than the ip whenever it gets the server from steam server list.

You can kinda notice this behavior by refreshing the server while in favorite tab, it will take a while for the server to show online, meanwhile the community tab is being populated.
