### ISSUE TITLE
valheim-updater do not update anything

### ISSUE THREAD

**Issue by maximuss** [lloesche/valheim-server-docker#536]
I can't figure out what I have done wrong, but it seems that the updater don't update anything.

This log-statement continues for at lot of lines:
supervisord: valheim-updater [  0%] Downloading update (0 of 57,385 KB)...
I have attached my entire log, so I hope somebody can help me.
[_valheim-server_logs.txt](https://github.com/lloesche/valheim-server-docker/files/10201005/_valheim-server_logs.txt)

**Comment by robinodling** [comment]
Getting the same result.

**Comment by billputer** [comment]
I was able to fix this with the following:
```
# open a bash shell inside the docker container
docker exec -i -t valheim-server /bin/bash
# stop the borked update command
pkill steamcmd
# run the update command
/opt/steamcmd/steamcmd.sh +force_install_dir "/opt/valheim/dl/server" +login anonymous +app_update 896660 -validate +quit
# wait until that finishes and then exit docker container
exit
# stop valheim
docker stop valheim-server
# start valheim
docker start valheim-server
```
This may or may not work for you. I didn't exactly find out why valheim-updater was hanging, but this worked for me.

**Comment by lloesche** [comment]
@billputer thanks, I'll make a PR that uses your solution every time before it tries to run the steamcmd updater. Seems the most pragmatic.

**Comment by maximuss** [comment]
> I was able to fix this with the following:
> 
> ```
> # open a bash shell inside the docker container
> docker exec -i -t valheim-server /bin/bash
> # stop the borked update command
> pkill steamcmd
> # run the update command
> /opt/steamcmd/steamcmd.sh +force_install_dir "/opt/valheim/dl/server" +login anonymous +app_update 896660 -validate +quit
> # wait until that finishes and then exit docker container
> exit
> # stop valheim
> docker stop valheim-server
> # start valheim
> docker start valheim-server
> ```
> 
> This may or may not work for you. I didn't exactly find out why valheim-updater was hanging, but this worked for me.

Sorry for the late response :)

It's also working for me - so thank you a lot!
