### ISSUE TITLE
Question about Bepinex and ValheimPlus

### ISSUE THREAD

**Issue by desidia26** [lloesche/valheim-server-docker#562]
For the sake of furthering my understanding of things, why are Bepinex and ValheimPlus mutually exclusive?

Also, thanks so much for this image. It has made life much easier.

Cheers!

**Comment by desidia26** [comment]
Also, apologies in advance if there are docs out that there that explicitly state the reasoning, that I have managed to miss.

**Comment by wcdanh2** [comment]
From what I understand Valheim plus is based on bepinex and they are packaged together. So you can either install just bepinex, or install v+ which will install its recommended version of bepinex.

**Comment by desidia26** [comment]
That answers that! Thank you!
