### ISSUE TITLE
Can't Access via LAN, but WAN Works Fine

### ISSUE THREAD

**Issue by mphintz2** [lloesche/valheim-server-docker#563]
I host a home server running this docker image, with BepInEx and ValheimPlus. It's worked great until this evening. And it still works fine for those accessing it from outside my home network. I've even verified that I can activate a VPN on my local PC and connect to my external IP through the VPN tunnel. No issues, logged in fine.
However, starting this evening, when connecting through my local network, I'm always getting an Incompatible version message: "You can only join servers running version 0.212.9@0.9.9.11". What's even stranger is that after a couple seconds of viewing the Select Server window, the IP address of my server resolves its name to "VikingQuest" (not the name of my server).
Anyone have any insight on this? For now I guess I'm using a VPN, but it's not a good long-term solution.

**Comment by JohnLahr** [comment]
I am on 0.214.2, and I'm seeing this same behavior. I can reach the server when using my WAN IP, but using the IP of the server results in a timeout when connecting in game. Interestingly, I can access the supervisor and status ports over LAN without issue, so I know the ports are open and listening correctly.

My ConfigMap:

```yaml
BACKUPS: 'true'
BACKUPS_CRON: 0 * * * *
BACKUPS_DIRECTORY: /config/backups
BACKUPS_IDLE_GRACE_PERIOD: '3600'
BACKUPS_IF_IDLE: 'false'
BACKUPS_MAX_AGE: '3'
BACKUPS_MAX_COUNT: '0'
BEPINEX: 'true'
PERMISSIONS_UMASK: '022'
PGID: '1000'
PUID: '1000'
RESTART_CRON: 20 6 * * *
RESTART_IF_IDLE: 'true'
SERVER_ARGS: '-crossplay'
SERVER_NAME: Valheimr
SERVER_PORT: '2456'
SERVER_PUBLIC: 'true'
STATUS_HTTP: 'true'
STATUS_HTTP_CONF: /config/httpd.conf
STATUS_HTTP_HTDOCS: /opt/valheim/htdocs
STATUS_HTTP_PORT: '80'
STEAMCMD_ARGS: validate
SUPERVISOR_HTTP: 'true'
SUPERVISOR_HTTP_PORT: '9001'
SUPERVISOR_HTTP_USER: admin
TZ: America/Chicago
UPDATE_CRON: '*/15 * * * *'
UPDATE_IF_IDLE: 'true'
VALHEIM_PLUS: 'false'
WORLD_NAME: dedicated
```
