### ISSUE TITLE
Failed to download Valheim server from Steam

### ISSUE THREAD

**Issue by DaleCavender** [lloesche/valheim-server-docker#566]
I'm not sure if it's relevant, but I'm trying run this container in podman, and it is giving the following message:
valheim-updater ERROR - Failed to download Valheim server from Steam - retrying later - check your networking and volume access permissions
![image](https://user-images.githubusercontent.com/99927637/212566953-b392e287-3f05-4cfd-b84e-6688e42ab67b.png)
I'm not all that familiar with podman or docker, so I apologize if I messed something up. Also, ENV variables from PATH to HOME seem to have been automatically added by podman.

**Comment by DaleCavender** [comment]
I was able to resolve my issue. It seems to have been a couple of different issues. First, I had the volumes pointing to directories that were owned by root, which caused some issues. Second, when running through cockpit-podman, podman seemed to be running it as non-root, which doesn't allow it to connect to outside networks. Third, it's trying to run as what cockpit-podman calls "System" which seems to be breaking things.

My solution was to create the correct directory structure, then if I just run the command "podman run" with all of my options and ENV variables, it works correctly.

**Comment by lloesche** [comment]
@DaleCavender glad you were able to figure it out. Consider contributing an update to the README so others can learn from your experience.
