### ISSUE TITLE
Server crash with BepInEx and mods to true after around 5min of playing

### ISSUE THREAD

**Issue by J0HNN1E** [lloesche/valheim-server-docker#579]
Hi everybody!

I tryed to launch a server following lloesche's tutorial,, which worked well for me... for around 5min.
I mean I was able to play on the server then after 4-5min, the server crashed (everytime I checked, around 12 or 13 times).

**Here are the lines the server is stucked on, in the bash I mean :** 

`valheim_1  | Feb  3 16:15:58 supervisord: valheim-server WackysDatabase Jsons files have changed and access is either on a dedicated server or singleplayer with autoreload on therefore reloading everything`
`valheim_1  | Feb  3 16:15:58 supervisord: valheim-server [Debug  :WackysDatabase] CustomSyncEventDetected was called `
`valheim_1  | Feb  3 16:15:58 supervisord: valheim-server WackysDatabase  You did reload SERVER Files`
`valheim_1  | Feb  3 16:15:58 supervisord: valheim-server WackysDatabase  You are not an admin`

There are few cfg's lines in json following, I can paste here if needed.

I tryed some env variables different and some other things, nothing worked.

_NB: The server is running well on Windows _(I just went to Ubuntu few days ago on my dedicated server because I wanted to run multiple servers modded and for it, I need docker)_ or a VM but it should be less well-optimized._
_NB2: I'm admin working ingame with "devcommands" and lot of others commands ("upgrade world mod", "edit world" from JereKusela and so on..), so don't know why there's this "echo" of a non admin state.._
Thanks for your time :) !
Cya

_JOHNN1E_
[bug_linux_wackydb.txt](https://github.com/lloesche/valheim-server-docker/files/10608273/bug_linux_wackydb.txt)

**Comment by wcdanh2** [comment]
If you can please post your config, and mod list I can try to recreate this on my machine.

**Comment by J0HNN1E** [comment]
Thanks for your fast answer!

Here is all the folder of the container "docker_valheim-server_community"
https://mega.nz/file/zY0FnaJD#1Lt1Z8A2WPiuFu-OqJp_fIjvxG39vGrJSsZtgg5am8k

Thanks a lot!
JOHNN1E

**Comment by J0HNN1E** [comment]
I can ZIP the admin client also, if needed.
Don't forget to change my STEAMID64 in config/bepinex/adminlist.txt with yours. :)

**Comment by J0HNN1E** [comment]
Here is the logfile also, attached piece.
[LogOutput.log](https://github.com/lloesche/valheim-server-docker/files/10608466/LogOutput.log)

**Comment by J0HNN1E** [comment]
> If you can please post your config, and mod list I can try to recreate this on my machine.

Thanks for your fast answer! I run it on Ubuntu 20.04 LTS on OVH DEDICATED SERVER (64Go RAM & AMD Ryzen 5 5600X)

Here is all the folder of the container "docker_valheim-server_community"
https://pastebin.com/wqYCakXt

Here is the logfile also, attached piece.
[LogOutput.log](https://github.com/lloesche/valheim-server-docker/files/10608900/LogOutput.log)


I can ZIP the admin client also, if needed.
Don't forget to change my STEAMID64 in config/bepinex/adminlist.txt with yours. :)

You can pm me on discord if needed JOHNN1E#1885.
Cya!

**Comment by J0HNN1E** [comment]
Yep I’ll try without, but the strange thing is this is perfectly running on Windows Server 2019 but not on Ubuntu Server 20.04 LTS

**Comment by J0HNN1E** [comment]
Issue resolved, the updater was crashing the server when it tries to reload (when server online). 
Thanks a lot to @wcdanh2 for your help!
