### ISSUE TITLE
Synology 7.1.1 with crossplay enabled

### ISSUE THREAD

**Issue by jrwhitehead** [lloesche/valheim-server-docker#595]
It's unclear from reading other issues if this should work or not.

Running a server instance (latest) on a Synology DS420+ on version 7.1.1. It works fine without crossplay enabled and I'm able to connect via my steam version of the game.

When I enable crossplay, by adding the environment variable SERVER_ARGS with the value -crossplay, the server starts but I'm unable to connect to it.

The following is shown in the server logs every 30 seconds after the server has started:

Mar 21 14:23:34 supervisord: valheim-server 03/21/2023 14:23:34: PlayFab reconnect server 'ThogsLegacy'
Mar 21 14:23:34 supervisord: valheim-server 03/21/2023 14:23:34: Server 'ThogsLegacy' begin PlayFab create and join network for server 
Mar 21 14:24:04 supervisord: valheim-server 03/21/2023 14:24:04: PlayFab reconnect server 'ThogsLegacy'
Mar 21 14:24:04 supervisord: valheim-server 03/21/2023 14:24:04: Server 'ThogsLegacy' begin PlayFab create and join network for server 
Mar 21 14:24:34 supervisord: valheim-server 03/21/2023 14:24:34: PlayFab reconnect server 'ThogsLegacy'
Mar 21 14:24:34 supervisord: valheim-server 03/21/2023 14:24:34: Server 'ThogsLegacy' begin PlayFab create and join network for server 
Mar 21 14:25:04 supervisord: valheim-server 03/21/2023 14:25:04: PlayFab reconnect server 'ThogsLegacy'
Mar 21 14:25:04 supervisord: valheim-server 03/21/2023 14:25:04: Server 'ThogsLegacy' begin PlayFab create and join network for server

Env Variables
SERVER_NAME ThogsLegacy
SERVER_PORT 2456
WORLD_NAME ThogsLegacy
SERVER_PASS thepassword
SERVER_PUBLIC true

Am I doing something wrong or are there issues with crossplay on Synology NAS with this docker?

@lloesche Thanks for your work on this!

**Comment by RonerBent** [comment]
You have to install  libpulse-dev libatomic1 libc6
Afterwards it should work :)
else remove the -crossplay functionality

**Comment by adz4u28** [comment]
i also have the same problem

**Comment by IslandJohn** [comment]
Is this for "latest" or the "debian10" pinning? I can't seem to connect to the "latest" (either host or bridged) on a DS920+.

**Comment by jrwhitehead** [comment]
> Is this for "latest" or the "debian10" pinning? I can't seem to connect to the "latest" (either host or bridged) on a DS920+. It works if I enable crossplay, but that proxies everything over the Internet (and need to use invite code or server list).

Latest. That appears to be an entirely different issue.

**Comment by jrwhitehead** [comment]
> You have to install libpulse-dev libatomic1 libc6
> Afterwards it should work :)

How would you do that? There's no apt-get, no yum, etc style package manager on a Synology NAS.

**Comment by jrwhitehead** [comment]
> You have to install libpulse-dev libatomic1 libc6
> Afterwards it should work :)

How would you do that? There's no apt-get, no yum, etc style package manager on a Synology NAS.

**Comment by jrwhitehead** [comment]
From my container logs it appears that it's failing to acquire it's external IP. Then fails to generate/acquire a join code. Then fails to register the server with PlayFab as it doesn't know the external IP.

Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Exception while waiting for respons from https://wtfismyip.com/text -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:27 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:27 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:27 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:27 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Specified argument was out of the range of valid values.
Mar 27 12:21:27 supervisord: valheim-server Parameter name: i
Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Audioman already exist, destroying self
Mar 27 12:21:28 supervisord: valheim-server Unloading 100 unused Assets to reduce memory usage. Loaded Objects now: 142137.
Mar 27 12:21:28 supervisord: valheim-server Total: 233.026448 ms (FindLiveObjects: 22.522203 ms CreateObjectMapping: 31.586545 ms MarkObjects: 176.732881 ms  DeleteObjects: 2.182386 ms)
2023-03-27 12:21:29,311 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Mar 27 12:21:29 supervisord: valheim-updater valheim-server: started
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: PlayFab logged in as "PlayFab_"ThogsLegacy"_2456_0c70228289b772735bd003cdb7fd8994"
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: PlayFab local entity ID is B5180C216A839362
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: New session server ""ThogsLegacy"" that has join code , now 0 player(s)
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: Register PlayFab server ""ThogsLegacy"" with IP 
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: Server '"ThogsLegacy"' begin PlayFab create and join network for server 
Mar 27 12:21:32 supervisord: valheim-server 03/27/2023 12:21:32: Exception while waiting for respons from http://checkip.dyndns.org/ -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:32 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:32 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:32 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:32 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:32 supervisord: valheim-server 03/27/2023 12:21:32: Specified argument was out of the range of valid values.
Mar 27 12:21:32 supervisord: valheim-server Parameter name: i
Mar 27 12:21:37 supervisord: valheim-server 03/27/2023 12:21:37: Exception while waiting for respons from https://checkip.amazonaws.com/ -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:37 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:37 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:37 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:37 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:37 supervisord: valheim-server 03/27/2023 12:21:37: Specified argument was out of the range of valid values.
Mar 27 12:21:37 supervisord: valheim-server Parameter name: i

**Comment by jrwhitehead** [comment]
From my container logs it appears that it's failing to acquire it's external IP. Then fails to generate/acquire a join code. Then fails to register the server with PlayFab as it doesn't know the external IP.

Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Exception while waiting for respons from https://wtfismyip.com/text -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:27 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:27 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:27 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:27 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Specified argument was out of the range of valid values.
Mar 27 12:21:27 supervisord: valheim-server Parameter name: i
Mar 27 12:21:27 supervisord: valheim-server 03/27/2023 12:21:27: Audioman already exist, destroying self
Mar 27 12:21:28 supervisord: valheim-server Unloading 100 unused Assets to reduce memory usage. Loaded Objects now: 142137.
Mar 27 12:21:28 supervisord: valheim-server Total: 233.026448 ms (FindLiveObjects: 22.522203 ms CreateObjectMapping: 31.586545 ms MarkObjects: 176.732881 ms  DeleteObjects: 2.182386 ms)
2023-03-27 12:21:29,311 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
Mar 27 12:21:29 supervisord: valheim-updater valheim-server: started
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: PlayFab logged in as "PlayFab_"ThogsLegacy"_2456_0c70228289b772735bd003cdb7fd8994"
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: PlayFab local entity ID is B5180C216A839362
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: New session server ""ThogsLegacy"" that has join code , now 0 player(s)
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: Register PlayFab server ""ThogsLegacy"" with IP 
Mar 27 12:21:30 supervisord: valheim-server 03/27/2023 12:21:30: Server '"ThogsLegacy"' begin PlayFab create and join network for server 
Mar 27 12:21:32 supervisord: valheim-server 03/27/2023 12:21:32: Exception while waiting for respons from http://checkip.dyndns.org/ -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:32 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:32 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:32 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:32 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:32 supervisord: valheim-server 03/27/2023 12:21:32: Specified argument was out of the range of valid values.
Mar 27 12:21:32 supervisord: valheim-server Parameter name: i
Mar 27 12:21:37 supervisord: valheim-server 03/27/2023 12:21:37: Exception while waiting for respons from https://checkip.amazonaws.com/ -> System.Net.WebException: The operation has timed out.
Mar 27 12:21:37 supervisord: valheim-server   at System.Net.HttpWebRequest+<RunWithTimeout>d__237`1[T].MoveNext () [0x00123] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:37 supervisord: valheim-server --- End of stack trace from previous location where exception was thrown ---
Mar 27 12:21:37 supervisord: valheim-server   at System.Net.HttpWebRequest.GetResponse () [0x00013] in <da4b11c274e64fae96aabebcec110a1f>:0 
Mar 27 12:21:37 supervisord: valheim-server   at Utils.DownloadString (System.String downloadUrl, System.Int32 timeoutMS) [0x0001a] in <e9303a9eb7f343c0a3d5175c2bfa5a6d>:0 
Mar 27 12:21:37 supervisord: valheim-server 03/27/2023 12:21:37: Specified argument was out of the range of valid values.
Mar 27 12:21:37 supervisord: valheim-server Parameter name: i

**Comment by jrwhitehead** [comment]
> You have to install libpulse-dev libatomic1 libc6 Afterwards it should work :) else remove the -crossplay functionality

These are all installed via the DockerFile. I've double checked and they are all installed/uptodate by default.
