### ISSUE TITLE
Server is constantly restarting

### ISSUE THREAD

**Issue by corbin-lounsbury** [lloesche/valheim-server-docker#607]
After getting the new update, my server seems to be in a restart loop. Looking at the logs, I found this:

![image](https://user-images.githubusercontent.com/22720997/228311054-2f342076-375b-4aae-bc24-ffc25916c8de.png)

In another thread, it looks like this was resolved by updating to the newest bepinex [thread](https://github.com/valheimPlus/ValheimPlus/pull/793#issuecomment-1487220362). 

Whenever I refresh the container, the version I get is 5.4.21 and the "fixed" version mentioned above is 5.4.2101. 

log file attached 
[cdt8g31y69oswt7nnvja2fuf2_logs.txt](https://github.com/lloesche/valheim-server-docker/files/11092258/cdt8g31y69oswt7nnvja2fuf2_logs.txt)

**Comment by markownik** [comment]
My solution was to save world backups, remove all files from mapped server volumes, restart server, shut it down, restore all plugins and world backups, start and it works.

**Comment by corbin-lounsbury** [comment]
I was able to get it working by doing the following:
Updated compose doc to use this repo: https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.13
Copied world files
Deleted config and server
created new, empty server and config folders
started container
Confirmed stability
Shut down container
Copied world back in

Here's what the environment vars look like in my compose doc
```
      # Valheim Plus configs
      - VALHEIM_PLUS=true
      - VALHEIM_PLUS_REPO=Grantapher/ValheimPlus
      - VALHEIM_PLUS_RELEASE=tags/0.9.9.13
 ```
