### ISSUE TITLE
Can't join server from an XBOX console.

### ISSUE THREAD

**Issue by manutaitrmn** [lloesche/valheim-server-docker#623]
- supervisord: valheim-server The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
- supervisord: valheim-server The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
- supervisord: valheim-server The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
- supervisord: valheim-server The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
- supervisord: valheim-server The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.

**Comment by torlivar** [comment]
Have you tried adding the following in valheim.env?:
`SERVER_ARGS=-crossplay`

**Comment by manutaitrmn** [comment]
> Have you tried adding the following in valheim.env?: `SERVER_ARGS=-crossplay`

I have added SERVER_ARGS="-crossplay" and also used his github hosted image and now it's working fine ;) thx
