### ISSUE TITLE
High idle load - 40-50% of CPU (i9 8700)

### ISSUE THREAD

**Issue by draconb** [lloesche/valheim-server-docker#626]
Hey I've noticed that my server has gotten pretty loud the last few days and realized that even when idle (no one connected) the valheim docker container is using 40-50% or more of the CPU so its constantly under load.

I've checked it with both sudo top and portainer stats and both track it in the 40-50 range constantly.

I'm not sure if a recent valheim update caused an issue or what as I didn't start tracking it until the last few days. I'm using valheim+ grantapher edition

I saw older posts which said you had to frame cap to 30/60 but that was then defaulted on year+ ago, is there still a way to do this manually to see if maybe they broke the fps cap in linux recently?

**Comment by lloesche** [comment]
This should probably be reported to the Valheim developers, as this container just executes the Valheim server. Though we've seen this behaviour for years and it's still there, so I suspect there's not much they can or will do about it. We had discussions about building a proxy that would shutdown the server when no players are connected and then spin it back up when someone connects but so far nobody has volunteered the considerable amount of time required to build and maintain this functionality.

**Comment by ciphersimian** [comment]
I'm not too familiar with the internals of all this, but I suspect this could be accomplished relatively easily by someone who does using systemd socket activation:

https://blog.developer.atlassian.com/docker-systemd-socket-activation/
