### ISSUE TITLE
Add support for Valheim Plus Mod

### ISSUE THREAD

**Issue by alec-hs** [lloesche/valheim-server-docker#63]
Adding support for Valheim Plus mod via an ENV Variable would be great. Stuff probably needed to make this work:

- ENV Variable to enable/disbale
- New volume with Valheim Plus config 
- Removal of "validate" command to stop steam overwriting mod files

<https://github.com/nxPublic/ValheimPlus>

**Comment by armanatz** [comment]
@lloesche I am actually working on this as we speak

**Comment by kachunkachunk** [comment]
Woo, glad to hear (and see this submitted)! I think the big gotcha in my view surrounds the supervisor bits and loading BePinEx, but I think it'd be a bunch of hours/days for me to figure out, if I can even get to that point.

**Comment by nxPublic** [comment]
Dawm you guys are great, thanks for taking the effort into it. ❤️ 

This is a great documentation and i will make sure to link it in the V+ repo as soon as its ready to.

Thank you!

**Comment by armanatz** [comment]
@lloesche PR submitted for this. Let me know what you think

**Comment by wedol** [comment]
See https://github.com/lloesche/valheim-server-docker/issues/72#issuecomment-783307733

**Comment by lloesche** [comment]
If you guys would like to test ValheimPlus support you can use the dev tag of the Docker image `lloesche/valheim-server:dev`

Updated README is here https://github.com/lloesche/valheim-server-docker/tree/dev

Let us know in https://github.com/lloesche/valheim-server-docker/pull/91 if everything works.

Thanks to all testers!

**Comment by lloesche** [comment]
@nxPublic I'd very much like your input on #91 
I tried using the included `start_game_bepinex.sh` the issue however is that it has no process control meaning if I kill the script the server keeps on running. One way of solving this would be to `exec` the server and just not reset LD_LIBRARY_PATH. Or track the server process and trap SIGINT/SIGTERM and bubble them up to the server PID.
Anyhow, I just took the contents and added them to the `valheim-server` start script.

**Comment by NoobTaco** [comment]
Testing now. One question, what about other mods? For example, the Craft from All Containers mod? If I drop the dll in the data/plus/plugins directory, will it be overwritten on update?

**Comment by lloesche** [comment]
@NoobTaco it'll work however anything in the data directory is regenerated when updates happen. We could add something that allows to add additional mods. That's a separate issue though.

**Comment by lloesche** [comment]
ValheimPlus support has been merged into main
