### ISSUE TITLE
Feature Request: configurable restart interval for the game server

### ISSUE THREAD

**Issue by GMBridge** [lloesche/valheim-server-docker#65]
Just in case there's an issue with a memory leak or similar in some release of the dedicated server, could we get a configurable restart interval (every X days or something?) to stop & start the game server? obviously a value of 0 (which would be the 'default' if not specified) would not restart the game server ever

**Comment by lloesche** [comment]
Thank you for the suggestion! I had actually noticed a slowdown of the server after a day or two of running continuously and at least on my server we've performed restarts every 12 or so hours.

I've implemented the feature and created a schedule that by default will automatically restart the server at 5:00 am. I feel that is a good default for most users. The env variable `RESTART_CRON` either takes a cron schedule ala `0 5 * * *` or an empty string which will disable the automatic restart.
