### ISSUE TITLE
Map seed integration

### ISSUE THREAD

**Issue by mnisyif** [lloesche/valheim-server-docker#651]
The ability to integrate seed specification when creating a valheim server

**Comment by lloesche** [comment]
@mnisyif hi there, good suggestion. From what I could find there is no server option to specify a seed though. All the tutorials I found suggest creating a world with a specific seed on your desktop and copying that world to the server.

**Comment by Sleavely** [comment]
In case someone else ends up on this issue like I did:

If you are using Docker Compose you can run a separate Docker image that creates the seed before the server container starts. I've shared the 2 new files needed for the additional image and changes to the docker-compose.yml in this gist: https://gist.github.com/Sleavely/9821e658a9d9d0679dbadb591bcf9d18
