### ISSUE TITLE
No Authentication Option For BepInEx ?

### ISSUE THREAD

**Issue by fclante** [lloesche/valheim-server-docker#652]
Hi @lloesche - I've been using this image alot :-) Thanks :-) Is there a way to let people login to the game without a password for the BepInEx Config as well just like there is for Valheim Plus Config? and if so - how?

**Comment by lloesche** [comment]
> Is there a way to let people login to the game without a password for the BepInEx Config

Hi there @fclante -- BepInEx is just a generic Unity game patcher. It doesn't have any in-game functionality itself. Valheim Plus for instance uses BepInEx to patch Valheim and remove the password.
