### ISSUE TITLE
Ashlands Public Release

### ISSUE THREAD

**Issue by oneproxima** [lloesche/valheim-server-docker#676]
Ashlands has been release, wondering if there will be an update soon? 

https://www.valheimgame.com/news/patch-0-218-15-ashlands

**Comment by losuler** [comment]
Is it working for you now? I pulled the container just now, after not running it since January, and it updated and now has Ashlands (confirmed by going to the biome).

**Comment by oneproxima** [comment]
I did a container restart and it seems to have trigger the update cron job. So it's working. DOn't know why it did update following the 15 min trigger before but I'll investigate to see if I can find something. I'll close this for now.

**Comment by ngraham20** [comment]
not to necro, but this solution also worked for me. Restarting the container triggered an update

**Comment by qwerty01** [comment]
If you're still having an issue with the new update: ValheimPlus has not been updated yet, so if you enable valheim plus when you create the container, it will give you a version mismatch error when you try to connect.
