### ISSUE TITLE
Server is still not visible

### ISSUE THREAD

**Issue by Dahmos** [lloesche/valheim-server-docker#69]
Hi, first - thx for this wonderful container! Server is running perfectly for more than 8h now and updates/backups are working fine.

But Ive got a problem to make this server visible in the community browser... also tried to set SERVER_PUBLIC 1 to get sure, but still cant find it in Valheim or Steam Server browser. I saved it via favorite server in Steam and its working this way, but it would be wonderful if I could make it visible directly too... any ideas?! 

Thx in advance... 
Dahmos

Oder ist das noch dem EA geschuldet?

**Comment by Toucan-Sam** [comment]
The default setting is public and it definitely works. I'm currently running two containers on the same machine on different ports and both are showing up in the list.

Valheim requires you to open three(3) ports for the game to work. Whatever you set as SERVER_PORT (eg, 2456), you need to make sure you open your firewall or port forward the next two(2) sequential ports. So, 2456, 2457, and 2458 in total (aka 2456-2458) via UDP.

Also, the in game server browser needs some work. You may have to choose 'Community' and refresh the server list a couple of times for all the servers to come up.

**Comment by Dahmos** [comment]
Yeah, I know default is 1. It was only a try to see if something changes. But I'm completly new to this.

Ive set the 2456-2458 UDP in the docker contqiner as shown in the screens. The server runs on my NAS and I forwarded the 2456-2458 UDP ports in my router to the NAS and allowed it to port forward by itself. I also allowed the firewall on my NAS any connection via TCP and UDP as well...  did I forgot something?

! I'm a bit confused about the firewall on my NAS. Im only able to allow all connections and cant specify ports. Its a Terramaster f2 220. Any suggestions about this?

**Comment by Toucan-Sam** [comment]
It sounds like you've done all the right things. I've never used a Terramaster NAS before so I can't offer any advice there.

If one of your friends is able to join it from the public internet, then I'd say it's probably in the list and you scrolled past it or the in-game server browser is being dumb. :)
