### ISSUE TITLE
~/valheim-server/data/dl/server/ is a 2gb waste of space on a running server

### ISSUE THREAD

**Issue by ryanturcotte** [lloesche/valheim-server-docker#699]
Deleting the following folder while server is live saves 2gb of space and does not appear to break the game.

~/valheim-server/data/dl/server/

I'm assuming this is what downloads the data when server is started. If this folder could be deleted after the server starts (and I have a script to do this), it would save space, but it seems to redownload itself.

Could this be optimized? Optimizing this could save money for folks hosting on Amazon if you need less disk space.

Before clearing:
/dev/xvda1      10473452 8506112   1967340  82% /
After clearing:
/dev/xvda1      10473452 6206444   4267008  60% /

**Comment by lloesche** [comment]
This is where the vanilla version of Valheim is stored. When you apply mods this folder gets merged with the mod into a new folder. This folder could be deleted at the expense of having to re-download it on every restart. In my case disk space is cheaper than traffic so I don't delete it, but you could use the `POST_START_HOOK` to automatically have it cleaned after startup.
