### ISSUE TITLE
Can't access Supervisor

### ISSUE THREAD

**Issue by Schalmeier** [lloesche/valheim-server-docker#706]
Hi,
the server works fine in all regards, but the supervisor HTTP page. I just want to be able to restart the server and also monitor its state. 

`SUPERVISOR_HTTP=true` and `SUPERVISOR_HTTP_PASS="password"` are set. 
![Bild_2024-11-04_160434081](https://github.com/user-attachments/assets/37cc3356-26a5-4c74-a94a-e8b0cb7abb5a)

The server obviosly got restarted as well. When navigating in a web browser to http://192.168.xxx.xxx:9001 i don't get any response. 
The container port 9001 is of course forwarded to 9001, and the IP is correct :)

![Bild_2024-11-04_160333272](https://github.com/user-attachments/assets/adeabd9d-4418-481f-8a40-e4c6de3d287a)

Is there anything i need to look for in the log?

> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,996 INFO supervisord started with pid 1
> -- | -- | --
> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,995 INFO RPC interface 'supervisor' initialized
> 2024/11/04 15:40:26 | stdout | Unlinking stale socket /var/run/supervisor.sock
> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,694 INFO RPC interface 'supervisor' initialized
> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,668 INFO Set uid to user 0 succeeded
> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,668 INFO Included extra file "/usr/local/etc/supervisor/conf.d/syslog.conf" during parsing
> 2024/11/04 15:40:26 | stdout | 2024-11-04 15:40:26,668 INFO Included extra file "/usr/local/etc/supervisor/conf.d/http_server.conf" during parsing
> 2024/11/04 15:40:26 | stdout | INFO - Supervisor http server activated

Thanks :)

**Comment by itezlo** [comment]
If your contaier is run in a virtualized environment, like VMware WS or VirtualBox on a linux host, then don't forget to open port on your firewall: firewall-cmd --add-port=9001/tcp --zone=public --permanent.

**Comment by sidaxel** [comment]
did you add a user for the supervisor?
I have everything working on DSM6.
![2024-11-18_20-16-35](https://github.com/user-attachments/assets/95009978-de8b-487d-ad39-9e6cf2fe3715)

**Comment by sidaxel** [comment]
here are all my settings, I got everything working...
and even the server updated to the latest version, although yesterday it refused to do so!
but the server name in the list is still “my server”, although I specified the name and everything was correct before.... Well, it's not critical, the login password works. 
![2024-11-18_21-39-02](https://github.com/user-attachments/assets/4b5c1f73-2251-41d5-b3e2-e1f53fdb7288)
![2024-11-18_21-40-19](https://github.com/user-attachments/assets/4922e045-9305-4028-92ba-4c124d150208)

**Comment by sidaxel** [comment]
I think publicly available it should be only to be visible in the list of servers and get join code...
try to specify the local port the same as the container port, unfortunately I have no other ideas....
![2024-11-18_22-05-01](https://github.com/user-attachments/assets/5bdeff53-46fe-4b6a-9f7d-862e1db23edd)
