### ISSUE TITLE
Failed to update Valheim server from Steam

### ISSUE THREAD

**Issue by itezlo** [lloesche/valheim-server-docker#709]
Since 01:00 UTC+3, 14 Nov, 2024, valheim-updater receives error message: ERROR! Password check for AppId 896660 returned error Access Denied. Possibly container update with new client config needed.

**Comment by opello** [comment]
Seems like it could be related to [these recent changes](https://steamdb.info/app/896660/history/) that seem to line up in time with your start time.

I also see it with a simple test case:

```
$ docker run --rm -it steamcmd/steamcmd:latest +login anonymous +app_update 896660 validate -beta public-test -betapassword yesimadebackups +quit
Redirecting stderr to '/root/.local/share/Steam/logs/stderr.txt'
Logging directory: '/root/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1731433425
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
ERROR! Password check for AppId 896660 returned error Access Denied.
```

So it doesn't seem related to this repo, but maybe as good a place as any to keep track.

**Comment by itezlo** [comment]
Thanks, @opello. This is the exact reason, why we all receive such error message. Anyway, the container needs to be modified. I see 2 ways: 1. add steam_login and steam_password as a ENV variables, 2. As far as I know, any valid credentials will work with steamcmd, so why not @lloesche create an account and integrate login/password to valheim-updater. I assume, that there is no need to have valheim bought on a account, it's just a matter or authentication(hope not authorization), but I can be wrong. In such case - only 1st method will work. Also we need to secure credentials.

**Comment by opello** [comment]
Sure, you should probably post a feature request issue asking for an alternative that uses an authenticated steamcmd invocation.  I think that's a pretty big lift given the interactive requirements with Steam Guard[1].

This is working again for me though.  Looks like there were updates a while ago [according to SteamDB](https://steamdb.info/app/896660/history/).

[1] https://github.com/CM2Walki/steampipe/tree/master?tab=readme-ov-file#how-to-use-this-image

**Comment by itezlo** [comment]
valheim-updater is updating again! Looks like that devs reverted anonymous access, so no need to change anything.
