### ISSUE TITLE
Couldn't create a Convex Mesh from source mesh "RearBig" within the maximum polygons limit (256)

### ISSUE THREAD

**Issue by Xav-Pe** [lloesche/valheim-server-docker#71]
Hi,

I tried to launch the container with ``docker run -d --name valheim-server -p 2456-2458:2456-2458/udp -p 2456-2458:2456-2458 -v config:/config -e SERVER_NAME="myserver" -e WORLD_NAME="myworld" -e SERVER_PASS="mypassword" lloesche/valheim-server``, but the server doesn't show up and at the end of the logs i have this :

```
2021-02-21 09:28:41,827 INFO spawned: 'valheim-server' with pid 71
Running Valheim Server
Found path: /opt/valheim/valheim_server.x86_64
Mono path[0] = '/opt/valheim/valheim_server_Data/Managed'
Mono config path = '/opt/valheim/valheim_server_Data/MonoBleedingEdge/etc'
Preloaded 'libsteam_api.so'
Initialize engine version: 2019.4.20f1 (6dd1c08eedfa)
[Subsystems] Discovering subsystems at path /opt/valheim/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.067 seconds
UnloadTime: 1.641811 ms
02/21/2021 09:28:42: Starting to load scene:start

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2021-02-21 09:28:43,272 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
valheim-server: ERROR (not running)
valheim-server: started
Couldn't create a Convex Mesh from source mesh "RearBig" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)
```

How can I fix it?

**Comment by Xav-Pe** [comment]
The container ended with "out of memory", so here is my problem.

**Comment by lloesche** [comment]
This all looks good so far. Does it load any further than that though? I get the same messages on my server. It's normal for the server not to show up in the browser ever since the game got popular. The game only loads like 5k servers anything more than that is discarded. Can you connect using direct IP?

**Comment by Xav-Pe** [comment]
We wrote at the same time :) I close this issue as it was a memory problem. Thanks for your work.
