### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by CptHowdy2012** [lloesche/valheim-server-docker#711]
No matter how simple or complex I set the password, when I connect, it always tells me wrong password. Is this a bug or did I overlook something?

**Comment by itezlo** [comment]
Do you mean this: -e SERVER_PASS="123456789" or something else? Didn't you forget about quotes? Maybe some wrong symbol somewhere?

**Comment by CptHowdy2012** [comment]
i tried with and without quotes. . . same outcome

**Comment by itezlo** [comment]
I had almost the same problem. The problem was in a text copied from windows to linux terminal. For some reason there were symbols making part of startup script unreadable and therefore discarded by in my case podman. I used midnight commander and its mcedit utility to track that symbols. After deletion, everything worked like sharm. I don't know how do you start your container, but in my case everything is working correctly, so SERVER_PASS arguement is working correctly out-of-the-box.

**Comment by itezlo** [comment]
Looks good, but are you sure "- WORLD_NAME=WorldName" is correct? You really have a file with your world in config/worlds_local with this name? I bet you don't! ls -la worlds_local, please.

**Comment by CptHowdy2012** [comment]
its a different name. . . i changed it for this post. . . no special characters

**Comment by CptHowdy2012** [comment]
ls -la outputted this:
```shell
total 3340
drwxr-xr-x  2 1000 1000   4096 Nov 18 09:34  .
drwxr-xr-x+ 5 1000 1000   4096 Nov 17 23:34  ..
-rw-r--r--  1 1000 1000     51 Nov 17 23:14  MostWanted_backup_auto-20241117231428.fwl
-rw-r--r--  1 1000 1000     53 Nov 17 23:48 '"MostWanted"_backup_auto-20241117234856.fwl'
-rw-r--r--  1 1000 1000 560083 Nov 18 08:00  MostWanted_backup_auto-20241118080032.db
-rw-r--r--  1 1000 1000     51 Nov 18 08:00  MostWanted_backup_auto-20241118080032.fwl
-rw-r--r--  1 1000 1000 845908 Nov 18 00:14 '"MostWanted".db'
-rw-r--r--  1 1000 1000 560083 Nov 18 09:34  MostWanted.db
-rw-r--r--  1 1000 1000 845908 Nov 18 00:08 '"MostWanted".db.old'
-rw-r--r--  1 1000 1000 560083 Nov 18 09:30  MostWanted.db.old
-rw-r--r--  1 1000 1000     53 Nov 18 00:14 '"MostWanted".fwl'
-rw-r--r--  1 1000 1000     51 Nov 18 09:34  MostWanted.fwl
-rw-r--r--  1 1000 1000     53 Nov 18 00:08 '"MostWanted".fwl.old'
-rw-r--r--  1 1000 1000     51 Nov 18 09:30  MostWanted.fwl.old

```

**Comment by itezlo** [comment]
Ok, so I hope that  "- WORLD_NAME=MostWanted" is in your startup script/yaml/etc. Are you using permittedlist.txt? Sadly I don't have enough knowledge in portainer, but file looks ok. There maybe some other reasons, why you can't connect. I use podman and usually use something like podman logs valheim-server | grep connect (or blacklist). Why not try portainer logs valheim?

**Comment by itezlo** [comment]
OK, do you use permittedlist.txt? If not, check that it is empty, or lines commented.

**Comment by CptHowdy2012** [comment]
no, contents of that file is:

```shell
cat permittedlist.txt
// List permitted players ID ONE per line
```

**Comment by CptHowdy2012** [comment]
ok i just tried including the " when typing the password and it connected. . . for some reason it is including the quotes as part of the password.

**Comment by itezlo** [comment]
I've checked my config, I don't have quotes, but I'm not sure this is the case. I'd check environment inside container. Like portainer exec -it valheim export. Sorry, don't have any other ideas.

**Comment by itezlo** [comment]
Congrats!

**Comment by CptHowdy2012** [comment]
thanks for your input. i believe using the quotes was the mistake i made.

**Comment by CptHowdy2012** [comment]
now to break it again as i want bepinex. . . lol
