### ISSUE TITLE
Add ddns support

### ISSUE THREAD

**Issue by lloesche** [lloesche/valheim-server-docker#74]
In service of solving situations like https://github.com/lloesche/valheim-server-docker/discussions/73#discussioncomment-390619
where a user's server doesn't show up in the list of servers and the user has a dynamic IP address we should add ddns support to the container. It'll help those users tremendously.

**Comment by lloesche** [comment]
Actually looking into the complexity of doing this properly instead of adding it to the valheim-server container users with dynamic IPs should run a second container dedicated to updating the DNS record like: https://github.com/qdm12/ddns-updater

**Comment by Dahmos** [comment]
Uhhh... well Im completly new to all this stuff and I was happy enough to get the valheim server running with docker :-)

Ive got no idea how to add this and how to configure. I think getting a static IP with my provider will be easier for me or Im wrong and this is easy?!

**Comment by lloesche** [comment]
I just tested it and it's a number of steps but fairly straight forward.

First I chose a free dynamic dns provider from the list at [https://github.com/qdm12/ddns-updater#configuration](https://github.com/qdm12/ddns-updater#configuration)
I went with https://noip.com for no particular reason.

When signing up I chose the free tier and the domain name `lloesche.ddns.net`. Provider my email and a password. After signup I confirmed my email address and logged in. Then I was asked to choose a username for which I also chose `lloesche`.

I then followed the configuration steps in the containers README and created a file `data/config.json` with the following contents:
```
{
    "settings": [
        {
            "provider": "noip",
            "domain": "ddns.net",
            "host": "lloesche",
            "username": "lloesche",
            "password": "XXXXXXXXXXXXX",
            "ip_version": "ipv4",
            "provider_ip": true
        }
    ]
}
```
and changed its permissions as described in the README like so
```
chown -R 1000 data
chmod 700 data
chmod 600 data/config.json
```

Then I ran the container using the command
```
docker run --rm -it -p 8000:8000 -v $PWD/data:/updater/data qmcgaw/ddns-updater
```

and opened my browser at http://localhost:8000/ which showed this:
![image](https://user-images.githubusercontent.com/2124094/108625370-e1d27480-744a-11eb-9420-42cc94dff8e9.png)

When I now check on the shell I can see that
```
lukas@MACROMI:~$ host lloesche.ddns.net
lloesche.ddns.net has address 84.46.29.31
```
the domain resolves to the correct IP address.

Hope these steps help you and your friends. That said a static IP has a number of advantages over dynamic dns so if you have the option I'd probably do that regardless.
