### ISSUE TITLE
Feature Request: timezone configuration via env variable

### ISSUE THREAD

**Issue by GMBridge** [lloesche/valheim-server-docker#77]
With the new scheduled restart, it'd be nice to be able to configure the timezone the server is running in via an environment variable passes to the container (I'm not sure if there is an existing 'standard' ENV all docker containers have like -TZ or if has to be exposed intentionally).

**Comment by lloesche** [comment]
@GMBridge  thanks for the suggestion. Added in https://github.com/lloesche/valheim-server-docker/commit/cd2a9740e4d37f99c28336fb86ccf923ee309bb8
