### ISSUE TITLE
Option to disable updater

### ISSUE THREAD

**Issue by leepfrog-ger** [lloesche/valheim-server-docker#81]
Thanks for your work on this, seems to work great for now.

I have a small enhancement request (not realls familar with docker, otherwise I'd submit a PR): Can you add a flag to disable the updater alltogether? From what I understand at the moment it will run once on each start, there is no way to disable it (even if increasing the interval, it will execute once on server start).

Use case: I'd like the server to run with a modified assembly_valheim.dll (which has `m_dataPerSec` increased to combat the lagging), but the modified dll gets purged by the updater (for obvious reasons) on each start.

**Comment by lloesche** [comment]
See https://github.com/lloesche/valheim-server-docker/discussions/58 for how we're currently doing it. Once https://github.com/lloesche/valheim-server-docker/issues/63 lands it will be taken care of by ValheimPlus mod. As per https://github.com/nxPublic/ValheimPlus/issues/58 the option to increase outbound send rate will be part of v0.8.5.
