### ISSUE TITLE
Desync/lag possible improvement

### ISSUE THREAD

**Issue by rcomanne** [lloesche/valheim-server-docker#82]
Hi, I am aware that this is more an issue of how Valheim is setup right now, but I do see some adjustments being made on the Steam forums that could help with the network issues and I was wondering if and how we could implement those changes on this image.
As you may be aware, you can adjust the data send rate of the server and clients to a higher value than the hardcoded 60kb/s, however this is done by editing a .dll assembly file of the game itself.
So, if we want to adjust the settings, I have no actual clue on how to do this, as the server is being downloaded on startup and is not statically provided, so we can't make a static change.
We could overwrite the downloaded file with a different prepared file, but this is not guaranteed to work over different versions and may cause other issues.
I do not know if we can edit it in place after it has been downloaded, I know I was able to edit my files locally with [dnSpy](https://github.com/dnSpy/dnSpy)
So, does anyone see a possibility where we can adjust this value? Preferably dynamically, as the value depends on the available upload bandwith available.

**Comment by InB4DevOps** [comment]
See #58

**Comment by rcomanne** [comment]
Was not aware there was already a discussion point about this topic.
