### ISSUE TITLE
Saving causes server to disconnect, sometimes lost progress?

### ISSUE THREAD

**Issue by nodu** [lloesche/valheim-server-docker#84]
Periodically we disconnected after a blinking connection icon in the top left.  Sometimes we seem to lose progress in the world.

No clue what it was, did a bit of debugging, now I can manually reproduce the issue by opening the console, manually saving, client disconnects.

Container: latest/49c71d4e4253

 See attached logs.

    02/22/2021 23:27:06: clone 1018
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:10: Saved 331406 zdos
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:10: World saved ( 4211.948ms )
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    /usr/local/bin/valheim-server: line 28:  2201 Killed                  "$valheim_server" -nographics -batchmode -name "$SERVER_NAME" -port $SERVER_PORT -world "$WORLD_NAME" -password "$SERVER_PASS" -public $SERVER_PUBLIC
    2021-02-22 23:27:42,916 INFO exited: valheim-server (exit status 0; expected)
    2021-02-22 23:27:43,948 INFO spawned: 'valheim-server' with pid 2372
    Running Valheim Server
    Found path: /opt/valheim/valheim_server.x86_64
    Mono path[0] = '/opt/valheim/valheim_server_Data/Managed'
    Mono config path = '/opt/valheim/valheim_server_Data/MonoBleedingEdge/etc'
    Preloaded 'libsteam_api.so'
    Initialize engine version: 2019.4.20f1 (6dd1c08eedfa)
    [Subsystems] Discovering subsystems at path /opt/valheim/valheim_server_Data/UnitySubsystems
    Forcing GfxDevice: Null
    GfxDevice: creating device client; threaded=0
    NullGfxDevice:
        Version:  NULL 1.0 [1.0]
        Renderer: Null Device
        Vendor:   Unity Technologies
    Begin MonoManager ReloadAssembly
    - Completed reload, in  0.069 seconds
    UnloadTime: 1.211916 ms
    02/22/2021 23:27:44: Starting to load scene:start
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    Couldn't create a Convex Mesh from source mesh "RearBig" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh. 
    (Filename:  Line: 91)
    
    2021-02-22 23:27:45,455 INFO success: valheim-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    HDR Render Texture not supported, disabling HDR on reflection probe. 
    (Filename:  Line: 277)
    
    HDR Render Texture not supported, disabling HDR on reflection probe. 
    (Filename:  Line: 277)
    
    Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
    UnloadTime: 5.141160 ms
    Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu). 
    (Filename:  Line: 509)
    
    HDR Render Texture not supported, disabling HDR on reflection probe. 
    (Filename:  Line: 277)
    
    02/22/2021 23:27:54: Initializing world generator seed: ( 0 )   menu:True  worldgen version:1
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Using mountain distance: 1000
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Render threading mode:SingleThreaded
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Get create world xxxxxxxxx
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Using environment steamid 892970
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Using steam APPID:xxxxxxxxx
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
    CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
    RecordSteamInterfaceCreation (PID 2373): SteamGameServer012 / GameServer
    RecordSteamInterfaceCreation (PID 2373): SteamUtils009 / Utils
    Setting breakpad minidump AppID = xxxxxxxxx
    RecordSteamInterfaceCreation (PID 2373): SteamGameServer012 / GameServer
    RecordSteamInterfaceCreation (PID 2373): SteamUtils009 / Utils
    RecordSteamInterfaceCreation (PID 2373): SteamNetworking005 / Networking
    RecordSteamInterfaceCreation (PID 2373): SteamGameServerStats001 / GameServerStats
    RecordSteamInterfaceCreation (PID 2373): STEAMHTTP_INTERFACE_VERSION002 / HTTP
    RecordSteamInterfaceCreation (PID 2373): STEAMINVENTORY_INTERFACE_V002 / Inventory
    RecordSteamInterfaceCreation (PID 2373): STEAMUGC_INTERFACE_VERSION010 / UGC
    RecordSteamInterfaceCreation (PID 2373): STEAMAPPS_INTERFACE_VERSION008 / Apps
    02/22/2021 23:27:54: Server ID 123
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Steam game server initialized
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
    
    02/22/2021 23:27:54: Missing audio clip in music respawn

**Comment by nodu** [comment]
Any assistance here?

**Comment by brcoding** [comment]
I have seen the same issue, but it is always isolated to a single player.
On voice we can determine that only one person has an issue.

**Comment by nodu** [comment]
Happened several times: Disconnected while finding body, re-connect, world is reset body/loot lost 😢

**Comment by lloesche** [comment]
Never seen this or had any blinking connection icon or disconnects. Regular restarts will save the world. You should be able to restore the world from the hourly backups. The player inventory is stored client side so that is lost if the player hasn't created a local backup.

**Comment by johnposten** [comment]
We noticed this last night and got stranded in the middle of the ocean with no boat because of it.  

My log output is very similar (although I don't have it handy right now-- I will try and update later).  I'm hosting this as an Azure Container Instance, with /config volume mounted to a Azure File storage account

My gut feeling is that it seemed like it was related to the frequent server restarts, and it doesn't seem to save the last 5 minutes or so of progress before the restart in our case.

**Comment by lloesche** [comment]
> seemed like it was related to the frequent server restarts

@johnposten can you elaborate on this? I do not have frequent restarts on my server. By default there should be one scheduled restart once per night at 5am and then whenever a server update is available which is currently every couple of days. If you see more than like two restarts in a day something is wrong.

Also, during a regular restart the server is shut down gracefully and will 100% save the world. No 5 minutes lost.

That said, if the server crashes for whatever reason it will automatically get restarted and would likely not have saved the past couple of minutes.

Can you gather from your logs the reason for the restarts? Also how much core memory are you allowing the server to use? On my system the idle(!) server currently consumes 3 GB RSS and 10 GB VSZ.

**Comment by johnposten** [comment]
Ahh, very interesting.  Thanks for the summary of info, sorry I haven't had much time to get fully acquainted with your project yet, I just discovered this gem yesterday :)

Perhaps it has to do with how I deployed the ACI.  I'll get more detailed information later tonight.

**Comment by lloesche** [comment]
Just an FYI, on our server where we've built a little village with around 8 friends the server constantly consumes 3 GB RSS and 10 GB VSZ.

> /usr/local/bin/valheim-server: line 65: 21772 Killed                  "$valheim_server" -nographics -batchmode -name "$SERVER_NAME" -port $SERVER_PORT -world "$WORLD_NAME" -password "$SERVER_PASS" -public $SERVER_PUBLIC > >(filter stdout) 2> >(filter stderr >&2)

This line means that the server process did not crash it was killed by an external process. The only thing that comes to mind going around doing that usually is the Linux kernel OOM killer.

**Comment by pjbates** [comment]
I've got a similar issue. Running on ACI as well, 
Starts and runs fine, can connect and play with no issues. 

Whenever I stop / start the container the world is resetting. Same seed, but all build is missing from the world. 
World files and backups are all persisting in /config just fine. 

I can see it loading the world files on start

`2021-02-28 06:06:04 [13] (INFO) Downloading/updating/validating Valheim server from Steam
  adding: worlds/ (stored 0%)
  adding: worlds/Helios.db (deflated 66%)
  adding: worlds/Helios.db.old (deflated 66%)
  adding: worlds/Helios.fwl (deflated 5%)
  adding: worlds/Helios.fwl.old (deflated 5%)
2021-02-28 06:06:04 [11] (INFO) Removing backups older than 3 days`

It's just not persisting anything I've built. 

I've seen some references pointing to this been an issue with how the server is shutdown. 
Could Azure Container Instances be doing something crazy and ignoring the 
shutdown procedure you've specified in the container? (Assuming that's how its done, docker nub here)

Any logs I can grab that would help?
Thanks

**Comment by lloesche** [comment]
@pjbates if Azure is sending a normal `docker stop` to the container resulting in a `SIGTERM` inside of it then valheim will shut down gracefully. If they `docker kill` (or whatever the equivalent of their containerizer) then the server will be killed and not have a chance to save the world. The servers save interval I believe is every 20 minutes.

**Comment by lloesche** [comment]
@pjbates what happens if you use admin commands to save the world manually. Are world changes persisted then?

**Comment by pjbates** [comment]
> @pjbates what happens if you use admin commands to save the world manually. Are world changes persisted then?

Good suggestion. Just tried it and the game states persists properly with the manual save command then a container restart. 

Sounds like Azure Container Instances is not using docker stop in the expected fashion. 
I'll see if I can find any documentation from MS that clarifies.

**Comment by pjbates** [comment]
Sounds like someone else has a similar issue 
https://stackoverflow.com/questions/66377009/gracefully-stop-azure-container-instance

No answer though.

**Comment by lloesche** [comment]
Question to the group. How are you running this container in Azure? For debugging of https://github.com/lloesche/valheim-server-docker/issues/120 I just tried to run the container using `az container create` but I'm getting the same result as @Nirco96 `/opt/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error`. I'm unable to run any 32bit binaries on the Azure Linux container host. So storage and restart issues aside, how did you get Azure to even run 32bit `steamcmd`?
Is this an extra option that needs to be provided upon container creation? A quick search did not yield any results for me.

**Comment by pjbates** [comment]
I used the template from https://github.com/jtucker/valheim-aci
Automates the storage and networking setup then pulls your image. 
Runs fine for me in ACI, just doesn't save properly.

**Comment by johnposten** [comment]
Mine is running fine in West Central US.  I use the following command:
```
az container create \
     --cpu 2 \
     --memory 4 \
     --resource-group dev \
     --name something \
     --image lloesche/valheim-server \
     --dns-name-label something \
     --ports 2456 2457 2458 \
     --protocol UDP \
     --restart-policy Never \
     --environment-variables SERVER_NAME=something SERVER_PASS=secret WORLD_NAME=something \
     --azure-file-volume-account-name something \
     --azure-file-volume-account-key blah123 \
     --azure-file-volume-share-name something \
     --azure-file-volume-mount-path /config
```

**Comment by lloesche** [comment]
Interesting. So that means Azure is using 32bit capable container hosts in the US but 64bit only kernels in Europe? I couldn't find any documentation on this, but through trial and error this seems to be the case. Maybe we need to create a separate image that has the game server already downloaded in it. `steamcmd` is the only 32 bit program in the container. Valheim server as well as the steam library it's linked against are 64 bit.

**Comment by lloesche** [comment]
@nodu were you able to figure this out? Are the disconnects still happening? Were you able to test with more RAM (~8 GB) or on a different Cloud provider? If you found a solution would be great if you can share it here so others can learn from your work.

**Comment by nodu** [comment]
Heya, Yes as soon as I expanded Docker's total available memory/cpu
resources the server started running smoothly. Thanks for the help folks!
