### ISSUE TITLE
Create Unraid Community Application

### ISSUE THREAD

**Issue by lloesche** [lloesche/valheim-server-docker#86]
As per https://github.com/lloesche/valheim-server-docker/discussions/80 it would be neat if an Unraid user would put in the work to make this available as a community application. I'd be willing to support them if there's any questions about the image or if any modification is required to make it work with Unraid.

**Comment by armanatz** [comment]
@lloesche There actually is a pretty similar Unraid container already out there by ich777 which I am using. Has almost all of the same features as this one (including V+ mod support). Not sure if you would want to put effort in to this

**Comment by lloesche** [comment]
Ah no then definitely not. Let's update the Discussion with a link to the ich777 thread.
