### ISSUE TITLE
Modify server to alleviate bandwidth throttling

### ISSUE THREAD

**Issue by nminchow** [lloesche/valheim-server-docker#92]
[This reddit comment](https://www.reddit.com/r/valheim/comments/lkea78/valheim_dedicated_server_lag/gnomadg/) and [this response](https://www.reddit.com/r/valheim/comments/lkea78/valheim_dedicated_server_lag/gnor4p8/) detail changes to the server that can be made to increase server network performance. Hopefully this is soon patched, but it would be nice to have until an update is published.

Implementation would require modifications to files after updates, so this may be out of the scope of this image. I wanted to bring it up as I have been getting experiencing network issues whenever we surpass 4 or 5 players.

**Comment by InB4DevOps** [comment]
Check #58

**Comment by nminchow** [comment]
> Check #58

Ah, I didn't look through "discussions" (I'm so used to solely issues and PRs)! I'll close in favor of that.
