### ISSUE TITLE
Trim Waste information from console log?

### ISSUE THREAD

**Issue by Zedifuu** [lloesche/valheim-server-docker#96]
Hey folks, 

Not sure  if its something that can be fixed or filtered out via docker but is it possible to remove the following line from the console log, to make reading logs a little less eye melting ? :) More for just QoL

`(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)` _Repeated after every console log_
![image](https://user-images.githubusercontent.com/73708675/109146320-94f8e180-775b-11eb-9318-3fff2c432604.png)

**Comment by lloesche** [comment]
I suppose we could add an option to send Valheim servers stdout/stderr through some filter that can remove those lines. It'll use a bit more memory and CPU cycles to do the string matching but nothing major. I'm usually not a fan of removing information the developer put in on purpose but those log lines seem pretty useless indeed to anyone but the devs themselves.

**Comment by Zedifuu** [comment]
Excellent! Thanks for the speedy reply! 

Yeah I'm the same with removing things intended by the dev, but as that line just repeats and doesn't change from what I can see, It may help the readability of the logs haha If it's not too much hassle/resource intensive it'd be a great addition! Feel free to close if it's something you'll be looking into :>

Also I'm not sure if it's an issue my end or if the update today regarding sockets borked something, but I just checked the containers logs there and it was filled with thousands of entries detailing the following:

**```src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1276) : Assertion Failed: SDR service thread gave up on lock after waiting 72ms.  This directly adds to delay of processing of network packets!```**

**Comment by InB4DevOps** [comment]
@Zedifuu what cpu are you running the container on?
I'm also seeing quite a few of those log messages although not thousands...
Intel N3060 Dual Core 1,6GHz with 8GB RAM here (in Synology DS416play NAS)

**Comment by lloesche** [comment]
@Zedifuu filter is added as an undocumented default env variable:
https://github.com/lloesche/valheim-server-docker/blob/d14c05b434b8ca025acebc25c8b18fe3d0774034/defaults#L46-L50

The default will filter those garbage lines as well as empty lines.
Default filter can be overridden using the `SERVER_LOG_FILTER` or more specific `SERVER_LOG_STDOUT_FILTER` and `SERVER_LOG_STDERR_FILTER` env variables.
The server output just gets piped into whatever commands you specify there.
E.g. `SERVER_LOG_FILTER=cat` would give you back the full server output.

**Comment by Zedifuu** [comment]
@lloesche Absolute hero! Thanks very much!

**Comment by Zedifuu** [comment]
@InB4DevOps I run a _Intel i5-3210M (4) @ 3.100GHz w/ 16GB RAM_, though it does run a few other services.. Think its a resources thing maybe?

**Comment by Zedifuu** [comment]
Can confirm it looks great now! 
![image](https://user-images.githubusercontent.com/73708675/109329590-ad97f300-7852-11eb-8638-d705b90b6781.png)
