### ISSUE TITLE
Inconsistent documentation across dockerhub and github

### ISSUE THREAD

**Issue by ShintoTuna** [lloesche/valheim-server-docker#97]
In Docker registry it says that this server has V+ support
https://registry.hub.docker.com/r/lloesche/valheim-server/
but in github repo it seems to be missing and when passing `VALHEIM_PLUS=true` it does not create a valheimplus directory under /config folder as it is stated in docker docs. 

I would really like to modify the server data rate value but it seems that i cant at the moment.

**Comment by Hydeo** [comment]
The V+ support is still in review here #91 

If you want to have the V+ support with this docker image, you hall to `docker pull lloesche/valheim-server:dev`
For the latest corresponding documentation, check the 'dev' branch on github.

Keep in mind that Valheim updated this morning with : 
* Updated socket-backend
That will probably have an impact on the data rate workaround we could use until now.

**Comment by lloesche** [comment]
@ShintoTuna Dockerhub is set up for automated builds for this repo. Dockerhub will display the README.md of whatever branch it last built. It just so happens you opened Dockerhub after it had built the `dev` branch. Not much to be done about.
